azure-pipelines.yml
azure/template.json

Added two files to the repo for CI pipelines:
- azure-pipelines.yml for Build pipeline
- azure/template.json for infra deployment

Added build yml and infra deployment  files

---

azure/template.json

Removed unnecessary resources from ARM template

removed FD from ARM template

---

azure-pipelines.yml

Updated the build pipeline to include  pull request branch name and merge comments in the artifacts. This information will be later used when creating and removing PR based test environment

2443-Build pipeline updated

---

.github/auto-comment.yml

Add a config file for Auto-Comment app https://probot.github.io/apps/auto-comment/

2443-Add auto-comment.yml file

---

Gemfile
Gemfile.lock

[2649] Add Sentry

---

config/settings/production.yml
config/settings/qa.yml
config/settings/staging.yml
config/settings/test.yml

[XXXX] Add Backend API url for all environments

---

.rubocop.yml
.scss-lint.yml
Gemfile
Gemfile.lock
README.md
app/controllers/errors_controller.rb
azure-pipelines.yml
config/environments/development.rb
config/environments/pentest.rb
config/environments/qa.rb
config/environments/staging.rb
config/initializers/assets.rb
lib/tasks/govuk_lint.rake
spec/rails_helper.rb

Linting
Replace `govuk-lint` with `rubocop-govuk` and `scss_lint-govuk`
🚢

[0000] Replace deprecated govuk-lint

---

app.json

Reliable review apps
Fix up app.json file for Heroku review apps
Proof that it works - https://find-teacher-heroku-rev-qeoxwn.herokuapp.com/course/T92/X130

Strip back app.json for heroku review apps

---

azure/template.json

Add resource tags
Update ARM template to enable resource tagging during deployment

2729-Apply Tags to resources

---

app/views/courses/_apply.html.erb
app/views/layouts/application.html.erb
app/webpacker/packs/application.js
app/webpacker/scripts/locations-map.js
app/webpacker/scripts/map-popup.js
app/webpacker/styles/_map.scss
app/webpacker/styles/application.scss

Location map
Setup for location maps - completely missed from my previous PR. This code is the same as https://github.com/DFE-Digital/manage-courses-frontend/pull/796
If your data has lat/long's for the providers/sites then the map should display

[2738] Fix location maps

---

azure/template.json

Fix maps 
Add Google maps API parameter and app settings

2738-Add GCP API key parameter

---

config/initializers/config.rb

Enable settings to be overridden with an environment variable
Setup "settings" so they can be overridden with an environment variable
🚢

Fix settings config

---

azure/template.json

Remove `SETTINGS__DFE_SIGNIN__SECRET` and `SETTINGS__MANAGE_BACKEND__SECRET` app settings

2738-updated app settings

---

app/views/courses/_apply.html.erb
app/views/layouts/application.html.erb
app/webpacker/styles/application.scss

Course page
Fix loading of maps and styling of paragraphs inside lists
🚢

2737 remove ref to turbolinks and load js last

---

app/models/provider.rb

:shipit: https://github.com/DFE-Digital/search-and-compare-ui/pull/483
Same as in C# but more DRY.
:shipit:

Send more providers to the Apply service

---

app/controllers/filters/vacancy_controller.rb
app/views/filters/vacancy/new.html.erb
config/routes.rb
spec/features/results/filters/vacancy_spec.rb
spec/site_prism/page_objects/page/result_filters/vacancy.rb
spec/support/helpers.rb

Reimplementing the vacancy page in Rails
- Add the vacancy controller
- Add the new vacancy page

[2346] Add vacancy filter page

---

azure-pipelines.yml

Fix Publish Test Results task in the build pipeline.

2831 fix find teacher training build tests

---

app/views/layouts/application.html.erb

Analytics
Add Google Tag Manager
🚢

[2849] Add google tag manager

---

azure/template.json

Add google geocode api key to app settings

2885-add an app setting

---

app/views/result_filters/provider/new.html.erb

[2341] Add page title and fix styling of location filter

---

Rakefile
app/controllers/provider_suggestions_controller.rb
app/models/provider_suggestion.rb
app/views/result_filters/location/new.html.erb
app/webpacker/packs/application.js
app/webpacker/scripts/__snapshots__/autocomplete.spec.js.snap
app/webpacker/scripts/autocomplete.js
app/webpacker/scripts/autocomplete.spec.js
config/routes.rb
lib/tasks/js_spec.rake
package.json
spec/factories/provider_suggestion.rb
spec/models/provider_suggestion_spec.rb
spec/support/resource_list_to_jsonapi.rb
spec/support/serializers/provider_suggestion_serializer.rb
yarn.lock

Location filter page performs lookup when the option "By school, university or other training provider" is selected.
Separate ticket to be created for running JS tests on CI (note this needs to be done for Publish Teacher Training also). 
To run the JS tests, either:
1. `bundle exec rake` (also runs ruby specs and linters)
2. `yarn jest` (JS test only).

[2817] - Location filter: live provider lookup

---

app/views/courses/_apply.html.erb

Recommended from the Accessibility audit completed by DAC in
December 2019

2897 - Add missing caption to table

---

azure/template.json

env var for SETTINGS__REDIRECT_RESULTS_TO_C_SHARP
Added env var for SETTINGS__REDIRECT_RESULTS_TO_C_SHARP
`SETTINGS__REDIRECT_RESULTS_TO_C_SHARP`
let me see results page

[2965] Added env var for SETTINGS__REDIRECT_RESULTS_TO_C_SHARP

---

Gemfile
Gemfile.lock
app/controllers/location_suggestions_controller.rb
app/services/location_suggestion.rb
app/views/result_filters/location/_form.html.erb
app/webpacker/packs/application.js
app/webpacker/scripts/__snapshots__/autocomplete.spec.js.snap
app/webpacker/scripts/autocomplete.js
app/webpacker/scripts/autocomplete.spec.js
config/initializers/geocoder.rb
config/routes.rb
config/settings.yml
spec/models/provider_spec.rb
spec/services/location_suggestion_spec.rb
spec/support/resource_list_to_jsonapi.rb

When a user searches by 'postcode, town or city' on the location filter page, location suggestions are now displayed.
I expect _DependaSau_ will break this

[2839] - live location lookup

---

app/views/layouts/application.html.erb
app/webpacker/packs/application.js
app/webpacker/scripts/analytics.js
app/webpacker/scripts/analytics.spec.js
app/webpacker/scripts/copy-tracking.js
app/webpacker/scripts/no-results-tracking.js
app/webpacker/scripts/scroll-tracking.js
package.json
yarn.lock

Google Analytics and user interaction Tracking
Add Google Analytics and user interaction Tracking
🚢

[2981] Add google analytics and tracking

---

app/models/base.rb
config/settings.yml
config/settings/development.yml
config/settings/production.yml
config/settings/qa.yml
config/settings/staging.yml
config/settings/test.yml
spec/features/result_filters/provider_spec.rb
spec/support/stub_v3_helper.rb

Update settings from manage_backend to api

---

app/views/courses/qualification/_pgce.html.erb
app/views/courses/qualification/_pgce_with_qts.html.erb
app/views/courses/qualification/_pgde.html.erb
app/views/courses/qualification/_pgde_with_qts.html.erb
app/views/courses/qualification/_qts.html.erb
spec/features/courses/show_spec.rb

This reverts commit 294aa7d756433b69bea6faa7f172885ea11ec82c, reversing
changes made to bd3567d7df8a50d0e03315254d48c7d0a728d275.

Revert "Merge pull request #96 from DFE-Digital/2896-abbr"

---

app/helpers/view_helper.rb
app/views/courses/show.html.erb
config/settings/development.yml
config/settings/production.yml
config/settings/qa.yml
config/settings/staging.yml
config/settings/test.yml
spec/features/courses/show_spec.rb
spec/helpers/view_helper_spec.rb

Back link on course page is broken.
Fix back link on course page.
Tricky to test locally, but hopefully the tests are correct now.

[2992] fix back link on course show page

---

app/webpacker/scripts/toggle.js

[3024] Removed leftovers console log

---

app/view_objects/results_view.rb
app/views/result_filters/provider/new.html.erb
app/views/results/_location.html.erb
app/views/results/_provider.html.erb
app/views/results/index.html.erb
spec/features/result_filters/location_spec.rb
spec/features/result_filters/provider_spec.rb
spec/features/results_spec.rb
spec/site_prism/page_objects/page/result_filters/provider_page.rb
spec/site_prism/page_objects/page/results.rb

Ongoing work to implement filtering.
* Update some page object references to make them consistent
* Hook up provider filtering
* Move some specs from results that are now covered in the provider feature specs
* Remove some unused page object references
Feature specs only cover the non-javascript versions of functionality. I did have a quick go turning javascript specs on but there were some issues with the app startup hanging so to avoid a rabbit hole I've left it for this PR. There is a card to add them https://trello.com/c/30imjCHG/290-add-js-feature-test-coverage-for-autocomplete .

2957 m provider filter do the filtering

---

app/views/courses/show.html.erb
app/views/result_filters/funding/new.html.erb
app/views/result_filters/location/_form.html.erb
app/views/result_filters/provider/new.html.erb
app/views/result_filters/qualification/new.html.erb
app/views/result_filters/study_type/new.html.erb
app/views/result_filters/subject/_form.html.erb
app/views/result_filters/vacancy/new.html.erb

Tracking and analytics
Add data modules required for JS modules to work
`/courses/XXX/XXXX` watch console for events on scroll and when you copy text.
Ignore whitespace i.e. https://github.com/DFE-Digital/find-teacher-training/pull/123/files?utf8=%E2%9C%93&diff=unified&w=1

[2981] Init page scroll and copy tracking

---

app/controllers/results_controller.rb
spec/features/results_spec.rb

The requirements for stubbing on this spec have changed but the test seems to have made it into master without being updated.

[3045] Fix failing spec

---

.github/PULL_REQUEST_TEMPLATE.md

- https://trello.com/c/F2lmEIDW/3083-update-pull-request-template
- The pull request template in this repo does not align with the others we have
- This makes them the same
- Add checklist to pull request template
- This aligns with the other pull request templates we have
- pull request template should match api and publish

[3083] Update pull request template

---

app/view_objects/results_view.rb
spec/features/result_filters/vacancy_spec.rb
spec/support/results_page_parameters.rb

[3091] Vacancies were not being filtered correctly

---

app/services/unescaped_query_string_service.rb
app/view_objects/results_view.rb
app/view_objects/suggested_search_link.rb
app/views/results/index.html.erb
spec/features/result_filters/funding_spec.rb
spec/features/result_filters/location_spec.rb
spec/features/result_filters/qualifications_spec.rb
spec/features/result_filters/study_type_spec.rb
spec/features/result_filters/subjects_spec.rb
spec/features/result_filters/vacancy_spec.rb
spec/features/suggested_searches_spec.rb
spec/fixtures/api_responses/empty_courses.json
spec/fixtures/api_responses/four_courses_with_sites.json
spec/fixtures/api_responses/one_course_with_sites.json
spec/fixtures/api_responses/ten_courses.json
spec/fixtures/api_responses/ten_courses_with_sites.json
spec/fixtures/api_responses/two_courses.json
spec/fixtures/api_responses/two_courses_with_sites.json
spec/services/unescaped_query_string_service_spec.rb
spec/site_prism/page_objects/page/results.rb
spec/view_objects/results_view_spec.rb
spec/view_objects/suggested_search_link_spec.rb

https://trello.com/c/V4IecruO/3027-m-add-search-suggestion-when-searching-by-location
Adds suggested searches for location search. This shows higher radius search counts for searches that have fewer than 3 results. Additional details are in the Trello ticket!

3027 add search suggestion when searching by location

---

.github/PULL_REQUEST_TEMPLATE.md

Unashamedly copied from https://github.com/DFE-Digital/publish-teacher-training/pull/929
We now do product review on review-apps before merging.
Add product review to PR checklist
This will be a handy reminder in the right place.
Consider if we like this as a team.
🚢

Add 'product review' to PR checklist

---

Gemfile
Gemfile.lock
config.ru

Setup application insights for Azure

---

app/views/pages/accessibility.html.erb
spec/features/view_pages_spec.rb

Update accessibility statement after an audit

[3065] Update accessibility statement after audit

---

azure/template.json

Main story: Being able to manually view and test the results page [https://github.com/DFE-Digital/find-teacher-training/pull/211]
Fix to ARM template json syntax
use jsonlint

[2933] Fix ARM template json syntax

---

app/models/subject.rb
app/view_objects/results_view.rb
spec/features/cookie_banner_spec.rb
spec/features/courses/results_spec.rb
spec/features/result_filters/funding_spec.rb
spec/features/result_filters/location_back_link_spec.rb
spec/features/result_filters/location_spec.rb
spec/features/result_filters/provider_spec.rb
spec/features/result_filters/qualifications_spec.rb
spec/features/result_filters/study_type_spec.rb
spec/features/result_filters/subjects_spec.rb
spec/features/result_filters/vacancy_spec.rb
spec/features/results_spec.rb
spec/features/suggested_salary_searches_spec.rb
spec/features/suggested_searches_spec.rb
spec/fixtures/api_responses/subjects_sorted_name_code.json
spec/requests/results_spec.rb
spec/support/stub_subjects_request.rb
spec/view_objects/results_view_spec.rb

https://github.com/DFE-Digital/teacher-training-api/pull/1291
Get rid of the hack for getting all subjects

[3210] Use new subjects endpoint

---

config/environments/pentest.rb
config/environments/research.rb

New research environment
- Add `research` environment
Nothing to see here

3384 Add research env

---

config/settings/research.yml

[3384] Add research settings

---

app/views/results/index.html.erb
app/webpacker/styles/application.scss

Hint: when viewing file changes change the settings to ignore whitespace changes which will make it easier to understand what actually changed in this PR

Fix spacing issues on Results page for mobile users

---

config/application.rb

https://github.com/DFE-Digital/govuk-rails-boilerplate/pull/255
https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training/pull/2048
GZip HTML and JSON responses
Check the Azure/Heroku review app to see if this was successful.

[XXXX] Compress HTML and JSON

---

Gemfile
Gemfile.lock

We are no longer using sprockets as of this PR
https://github.com/DFE-Digital/find-teacher-training/pull/320
closes #329

Remove sprockets

---

README.md

- Adds Code Climate badge
- Adds missing Azure badge

[3502] Add Code Climate Badges to README

---

config/environments/rollover.rb
config/settings/rollover.yml

We are building a rollover environment to test rollover.
Add a `rollover` Rails env.

[3510] add rollover env

---

app/controllers/courses_controller.rb
config/brakeman.ignore
spec/controllers/courses_controller_spec.rb

🚢 
Change apply URL from `education` to `service`
🚢

[3697] Update URL for apply

---

app/views/courses/qualification/_pgce.html.erb
app/views/courses/qualification/_pgce_with_qts.html.erb
app/views/courses/qualification/_pgde.html.erb
app/views/courses/qualification/_pgde_with_qts.html.erb
app/views/courses/qualification/_qts.html.erb
app/views/result_filters/qualification/new.html.erb

https://trello.com/c/rLs2TBct/3584-change-qts-pgce-definitions-on-find

[3584]-qts-pgce-find-definitions-updated

---

README.md

@AgaDufrat wrote this, I just added it to the repo.
:shipit:
:shipit:

Add shipit instructions

---

app/views/result_filters/provider/new.html.erb
spec/features/result_filters/provider_spec.rb
spec/site_prism/page_objects/page/result_filters/provider_page.rb

Fix invalid HTML on Pick a provider page

---

terraform/resources.tf
terraform/terraform_prod.tfvars
terraform/terraform_qa.tfvars
terraform/terraform_staging.tfvars

configure the `/ping` as the health check endpoint in statuscake.
~- [ ] Product review~

use /ping as statuscake healthcheck url

---

azure/template.json

Fix up typos in Azure template
https://trello.com/c/pF2NLAY9/2070-add-azure-config-for-end-of-cycle-feature-flags

Fix typos in Azure template

---

azure/template.json

Typo fix required in Azure template.
I will pay more attention in future 😅 
https://trello.com/c/vQRmFS25/2067-find-dev-apply-for-this-course-button-changes-18-9-13-10

Correction to environment variable (SETTINGS__DISPLAY_APPLY_BUTTON)

---

azure/template.json

Hopefully the last typo 🤞 
Fix typo in Azure template
https://trello.com/c/s7Hj3oH0/2058-dev-find-cycle-ending-soon-interim-page

Fix azure template typo

---

app/views/pages/cycle_ending_soon.html.erb

- Avoid "some" repetition
- Fix casing of service name
- Add 6pm to deadlines
(Ran these by @emmafrith)

Content tweaks to ending cycle page

---

README.md

There are three feature flags relating to the end of cycle process. 
Update README with instructions on how to toggle End of Cycle feature flags locally and on a deployed environment
Feedback welcome! Make sense?
https://trello.com/c/38YrjNzp/2079-add-information-about-end-of-cycle-feature-flags-to-readme

Update README with information about End of Cycle feature flags

---

.github/workflows/build-deploy.yml

Currently we don't build the docker image as part of the github action workflow.
New GitHub action workflow file to build Docker image.
Existing `terraform.yml` will be merged into this file as part of a later PR.
https://trello.com/c/qzwK2xZP/1434-build-tag-docker-image-in-github-actions

GitHub Action to build docker image

---

.github/workflows/build-deploy.yml
Makefile

GitHub actions doesn't execute tests.
Run ruby & javascript tests in the actions workflow.
https://trello.com/c/FFhdoR9m/2245-run-unit-tests-in-github-actions-workflow

Run linter and tests in GitHub Actions workflow

---

app/views/courses/_apply.html.erb

Content in the apply section on Course details page will be inaccurate once find reopens from 6th Oct.
Update copy in apply section
https://trello.com/c/9ehUxrmQ/2255-course-details-page-content-chg

Update copy in ‘apply’ section

---

app/webpacker/packs/application.js

This is hitting the service for every keypress, and causing too much load on our system.

Disable the autocomplete JS temporarily

---

azure/template.json

Fix for Skylight configuration
Fix template env var declarations in template
https://trello.com/c/tfpDMdkZ/2295-add-skylight-to-find

Fix Skylight config

---

app/decorators/course_decorator.rb
spec/decorators/course_decorator_spec.rb

Teacher Reward and Incentives Division aren't happy with the Financial Support summaries on Find.
Financial support summary copy updated
https://trello.com/c/LGwCVZa4/2373-edit-fi-content-summary-lines-on-find-search-results-course-details

Update financial support summaries

---

.github/workflows/deploy.yml
config/environments/production.rb
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/terraform.tf
terraform/variables.tf
terraform/workspace_variables/app_config.yml
terraform/workspace_variables/production.tfvars
terraform/workspace_variables/production_backend.tfvars
terraform/workspace_variables/qa.tfvars
terraform/workspace_variables/staging.tfvars
terraform/workspace_variables/staging_backend.tfvars

Config to deploy to staging and production in PaaS
Move application environment variables to a YAML variable (stored in GitHub secrets for now).
Read and apply above yaml config using terraform as app environment variables.
Change deploy pipeline to use correct secret value depending on `environment` being deployed.
Example deployments :
qa                : https://github.com/DFE-Digital/find-teacher-training/runs/1285870337
staging        : https://github.com/DFE-Digital/find-teacher-training/actions/runs/318283816
production  : https://github.com/DFE-Digital/find-teacher-training/actions/runs/318284149
https://trello.com/c/A4528lno/2382-deploy-to-staging-and-production-in-paas

Pipeline & Terraform changes to deploy to staging & production

---

terraform/workspace_variables/app_config.yml

Enable Skylight in PaaS
Configure enable skylight flag value and set skylight token in secrets.

Enable Skylight in PaaS

---

app/controllers/courses_controller.rb
config/brakeman.ignore
spec/controllers/courses_controller_spec.rb

This behaviour is now being dealt with on the Apply service.
- Just sent everyone to Apply. We deal with courses only on Apply in the Apply codebase.

Remove University of Bolton specific behaviour from Find

---

.github/workflows/deploy.yml
.github/workflows/smoke-test.yml

Alert smoke test failures on slack

Alert smoke test failures on slack

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Input parameters to control deployment to individual environment.
Deployment to each of the environments can be controlled
by passing a boolean value.
Allow option to control manual deployments to individual environment.

Select individual environment during deployment

---

Gemfile
Gemfile.lock
config/application.rb

View components are a great tool. We use them on Apply and should use them on Find as well. 
- Add the view_component gem

Add view_component gem

---

.github/workflows/deploy.yml

Wait for other inprogress run in the matrix selection job.

Wait for other in-progress runs inside matrix job

---

Gemfile

remove File.join in Gemfile

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Use DFE-Digital/github-actions/turnstyle

Use DFE-Digital/github-actions/turnstyle action

---

app/views/result_filters/subject/_form.html.erb

GiT updated the Subject Knowledge Enhancement page on their site on 10th Dec, but we didn't know, so we're still displaying old data.
- Update paragraph on Subject Knowledge Enhancement courses
https://trello.com/c/u2DWnWVQ/2766-dev-remove-ske-paragraph-on-find

Update section on subject knowledge enhancement courses

---

app/views/courses/_fees.html.erb
app/views/result_filters/location/_form.html.erb
app/views/result_filters/qualification/new.html.erb
app/views/results/_location.html.erb
app/views/results/index.html.erb

Some typo corrections and small content changes were required following a recent bug party.
See diff.
- Check the acceptance criteria on the card and contrast with the diff
- Note that change to SKE copy has not been applied as the copy in question was removed in commit d476f4925a6eb19c2b7f
https://trello.com/c/4JjtvvUi

Make several copy changes identified during a bug party

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/smoke-test.yml
Makefile
config/environments/sandbox.rb
config/settings/sandbox.yml
terraform/modules/paas/data.tf
terraform/modules/paas/variables.tf
terraform/terraform.tf
terraform/variables.tf
terraform/workspace_variables/app_config.yml
terraform/workspace_variables/qa.tfvars
terraform/workspace_variables/sandbox.tfvars
terraform/workspace_variables/sandbox_backend.tfvars
terraform/workspace_variables/staging.tfvars

Create sandbox environment for application
Change workflow to deploy to sandbox in prod space
Add terraform configuration to create sandbox environment

Deploy app to sandbox environment

---

terraform/workspace_variables/app_config.yml

Temporarily switch on ucas_only_locations feature in QA

---

app/views/courses/_advice.html.erb

Update content in support section on course details page to closely match the language we are now using within Apply.

Update GIT content on course details page

---

config/settings.yml

The feature is not working as intended

Switch filters flag off

---

terraform/workspace_variables/app_config.yml

A new filters bug requires investigation
Switch of 'new search filters' feature flag in prod during bug investigation

Turn off 'new filters' feature flag in prod

---

config/settings.yml
config/settings/test.yml
terraform/workspace_variables/app_config.yml

Slack approval - https://ukgovernmentdfe.slack.com/archives/CP18YJXPY/p1614080299017100
- Switch on 'ucas_only_locations' feature flag in all environments
NA

Switch on 'ucas_only_locations' feature flag in all environments

---

terraform/workspace_variables/app_config.yml

Rachel is happy for the new search results filters be turned on in production. 
NA

Turn on new search filters in production

---

Makefile

Add the propensity to ssh console to application via the `make` command
Add the propensity to ssh console to application via the `make` command

Add make console to Makefile

---

config/settings/staging.yml

Point staging to TTAPI staging
Point to TTAPI staging on PaaS.
To be merged once TTAPI is live on PaaS

Update TTAPI staging url

---

app/views/courses/_fees_and_financial_support.html.erb
app/views/courses/financial_support/_bursary.html.erb
app/views/courses/financial_support/_loan.html.erb
app/views/courses/financial_support/_salaried.html.erb
app/views/courses/financial_support/_scholarship_and_bursary.html.erb

As a... user researching courses on Find
I need to... know what financial support is available
So that... I know if I can afford to train to be a teacher
Content updated as per document attached to Trello card.
https://trello.com/c/LEvlFXMH/

Update content for standard financial support guidance

---

Dockerfile
Gemfile.lock

Bump mimemagic

---

app/views/cookie_preferences/_cookie_preferences_form.html.erb
app/views/cookie_preferences/new.html.erb
spec/features/cookie_consent_spec.rb

As part of overhaul of this page I have rearranged and updated content to reflect the prototype provided.
check content against: https://find-prototype.herokuapp.com/cookies
https://trello.com/c/slpIdWMK/3060-%F0%9F%8D%AA-update-banner-and-page-to-follow-gds-cookie-guidance-find

Update Cookie guidance page content

---

package.json
yarn.lock

Remove set-value library as it is not used

Remove set-value library as it is not used

---

app/components/feedback_component.html.erb
app/controllers/courses_controller.rb
config/brakeman.ignore
config/settings.yml
config/settings/production.yml
config/settings/qa.yml
config/settings/rollover.yml
config/settings/sandbox.yml
config/settings/staging.yml

Apply from find, always links to prod apply address.
Use corresponding Apply URL for each environment.

Use correct Apply url for each environment

---

Makefile
README.md

Update docs to include instructions for updating KeyVault secrets using the make commands.
Update Readme

Documentation  for updating environment variables

---

Makefile

Add `plan` to make plan target.

add terraform plan to plan make target

---

Gemfile
Gemfile.lock
app/lib/redis.rb
terraform/modules/paas/data.tf
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/terraform.tf
terraform/variables.tf
terraform/workspace_variables/production.tfvars
terraform/workspace_variables/qa.tfvars
terraform/workspace_variables/sandbox.tfvars
terraform/workspace_variables/staging.tfvars

Create a new backing redis instance
Terraform config for creating a new redis service.
Add redis gem
Library to create a Redis client instance using VCAP connection string
https://trello.com/c/zlFGEPjZ/3659-create-redis-service-instance-for-find

Configure redis service for find

---

app/services/cycle_timetable.rb
spec/features/result_filters/location_and_provider_spec.rb
spec/requests/cycle_ending_soon_spec.rb
spec/requests/start_spec.rb
spec/services/cycle_timetable_spec.rb

We need to update the Apply2 deadline to the 21/09 as we previously had the incorrect deadline
- Update the apply 2 deadline to have the correct date

Update the apply2 deadline in the CycleTimetable

---

.github/workflows/build.yml
Dockerfile
Makefile

Improve docker caching and build time
- Use PR branch sha as docker tag
- Replace builx cahe with standard registry cache
- Reorder Dockerfile

[2313] Use PR branch sha as docker tag

---

app/views/courses/show.html.erb

We need to update the content that replaces the apply button after the apply2 deadline.
- Update the EOC content that replaces the apply button
Emma provided the content 🙌

Update the EOC content on the apply section of the course page

---

app/components/deadline_banner_component.html.erb
spec/components/deadline_banner_component_spec.rb
spec/features/cycle_switcher_spec.rb

Reverts DFE-Digital/find-teacher-training#887

Revert "Edit 'Apply 1' deadline banner"

---

Gemfile.lock

Reverts DFE-Digital/find-teacher-training#898

Revert "Bump webpacker from 5.4.0 to 5.4.2"

---

package.json
yarn.lock

Reverts DFE-Digital/find-teacher-training#900

Revert "Bump @rails/webpacker from 5.4.0 to 5.4.2"

---

Gemfile
Gemfile.lock
Procfile
config/application.rb
config/sidekiq.yml

Reverts DFE-Digital/find-teacher-training#891

Revert "Use sidekiq for async jobs"

---

Gemfile
Gemfile.lock
Procfile
config/application.rb
config/initializers/sidekiq.rb
config/sidekiq.yml
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/terraform.tf
terraform/variables.tf
terraform/workspace_variables/production.tfvars
terraform/workspace_variables/qa.tfvars
terraform/workspace_variables/sandbox.tfvars
terraform/workspace_variables/staging.tfvars

A background worker is required for sidekiq jobs.
Terraform config for creating background worker container app.
Sidekiq configuration

Background worker for sidekiq jobs

---

.gitignore
Makefile
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/terraform.tf
terraform/variables.tf

Make terraform run with passcode when running locally.
Makefile commands for terraform runs.

Make terraform work with cf passcode

---

.github/workflows/build.yml
.github/workflows/delete-review-app.yml
.github/workflows/deploy.yml
.github/workflows/smoke-test.yml
Makefile
config/environments/review.rb
config/settings/review.yml
docker-compose.yml
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/terraform.tf
terraform/variables.tf
terraform/workspace_variables/app_config.yml
terraform/workspace_variables/production.tfvars
terraform/workspace_variables/qa.tfvars
terraform/workspace_variables/review.sh
terraform/workspace_variables/review.tfvars
terraform/workspace_variables/review_backend.tfvars
terraform/workspace_variables/sandbox.tfvars
terraform/workspace_variables/staging.tfvars

Review apps on PaaS.
Use make commands to deploy in deploy workflow
Terraform config changes for deploying review apps
Delete workflow to delete review app on PR close/merge

Deploy review apps

---

Gemfile
Gemfile.lock
config/initializers/rack_profiler.rb

To provide some quick metrics in development when analysing performance issues.
https://trello.com/c/qqZRrmQg

Add rack-mini-profiler

---

app/views/courses/_contact_details.html.erb

I got a little hasty with the commas in #929
- Remove erroneous commas

Fix formatting of address for 28T X104

---

config/environments/production.rb
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf

Merge assets-domain to load-test

Merge assets-domain to load-test

---

config/initializers/rack_profiler.rb

Correct qa check for rack profiler

---

config/settings.yml

TTAPI DB plan upgrade
Turn off maintenance banner
Merge after 8:00 AM on 23 September 2021

Turn off maintenance banner

---

config/environments/production.rb
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf

Planning to use redis cache store
Add a redis instance for caching with LRU policy.
Change existing sidekiq redis instance to noeviction max memory policy
Set redis_store and rails cache store.

Configure redis cache store

---

config/settings/production.yml

Cache responses to any requests that go through the Course model.
Relevant code: 
https://github.com/DFE-Digital/find-teacher-training/blob/master/app/models/course.rb#L4-L12

Switch course caching on

---

Gemfile
config/initializers/big_query.rb
config/initializers/semantic_logger.rb

Reverts DFE-Digital/find-teacher-training#997

Revert "Don’t use SemanticLogger in local dev"

---

config/settings.yml
config/settings/production.yml

These are the settings that we want at launch tomorrow
- toggle off the provider autocomplete and bursary/scholarship/SKE flags
- toggle on the new filters 
Are we agreed these are the correct flags?

[DO NOT MERGE BEFORE 12:05am 05/10/2021] Toggle the correct flags for launch

---

.github/workflows/deploy.yml

These are broken while Find is closed: https://github.com/DFE-Digital/find-teacher-training/runs/3797399940?check_suite_focus=true

Do not run smoke tests

---

app/views/courses/show.html.erb
app/views/pages/cycle_has_ended.html.erb

Content change only – Updating view with smart quotes

Use smart quotes on the cycle has closed page

---

.github/workflows/deploy.yml

This reverts commit c73d3481d7df3ce1cf149aa516d74db77cffcc08 and #1021

Revert "Do not run smoke tests"

---

app/services/cycle_timetable.rb
app/views/courses/_entry_requirements_qualifications.html.erb
spec/features/courses/show_spec.rb
spec/services/cycle_timetable_spec.rb

Some dates were not hard coded and started failing as the new cycle opened

fix tests failing in new cycle

---

app/models/course.rb

Temporarily bump the course cache expiry

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml
.github/workflows/delete-review-app.yml
Makefile
README.md

We want to use `main`, not `master`.
Replace all incidences of `master` in actions and `Makefile` with `main` and hope for the best 😬.
Once this is in, we'll need to tell GitHub `main` is the primary branch: https://github.com/github/renaming
Remove the redundant link to Azure DevOps while we're here
🤷

Use `main`, not `master`

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Fixes following recent changes to workflows
- Includes test job in deploy_all dependencies
- Corrects input type on deploy workflow
- Review recent workflow runs to check they are behaving as expected (with the exception of issues fixed in this PR)
https://trello.com/c/grpMynpF

Fixes for recent changes to workflows

---

app/views/result_filters/_study_type_filter.html.erb

This is a tiny copy amend identified by @EmmaFrith 
18 - 24 -> 18 to 24
https://trello.com/c/y1iiKizM/4443-dev-copy-edit-find-filter

Update copy on filter

---

app/components/results/results_component.html.erb
spec/components/results/results_component_spec.rb

Updating copy in this new CTA.

Quick copy edit

---

.github/workflows/deploy.yml

Add rollover to deploy workflow dispatch so it can be deployed manually
Update deploy.yml
Check deploy.yml

Add rollover to deploy workflow dispatch

---

package.json
yarn.lock

Reverts DFE-Digital/find-teacher-training#1353

Revert "Bump cypress from 9.6.0 to 10.0.3"

---

app/components/courses/contents_component.html.erb
app/views/courses/_about_course.html.erb

https://trello.com/c/yWS8jIfT/273-change-about-this-course-to-course-summary-on-find
Update heading on course info. Corresponding PR for Publish preview is here https://github.com/DFE-Digital/publish-teacher-training/pull/2815
Review app - https://find-pr-1394.london.cloudapps.digital/
Search and view a course's information

[273] Update content on course info

---

app/views/courses/_advice.html.erb

Fix a couple of headings which have the wrong heading level.

fix or remove illogical headings

---

.github/workflows/deploy.yml
Makefile
config/environments/loadtest.rb
config/settings/loadtest.yml
terraform/modules/paas/variables.tf
terraform/workspace_variables/app_config.yml
terraform/workspace_variables/loadtest.tfvars.json
terraform/workspace_variables/loadtest_backend.tfvars

New loadtest environment for find in bat-prod space
- same infrastructure as prod
- manual deploy via deploy workflow or make (not automated)
- Add new env to Makefile
- Add to deploy workflow 
- terraform updates
- Add required rails configuration files
Also added outside of this PR
- required gh secrets
- AZ KV secrets
- AZ storage container

Create loadtest environment

---

terraform/.terraform.lock.hcl
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/terraform.tf
terraform/variables.tf
terraform/workspace_variables/loadtest.tfvars.json

Load tests filled up Logit.io
Make external logging optional and disable it for the loadtest environment
Run terraform plan against the existing environments
https://trello.com/c/7WBnFwdk/292-load-test-find

[292] Disable external logging in load test environment

---

app/components/courses/international_students_component.html.erb
app/components/courses/international_students_component.rb
config/locales/en.yml
spec/components/courses/international_students_component_spec.rb
spec/factories/courses.rb
spec/features/courses/show_spec.rb

Update international visa component
Amended to use the course vs provider version of `can_sponsor_student_visa` & `can_sponsor_skilled_worker_visa`
Requires  https://github.com/DFE-Digital/publish-teacher-training/pull/2964

[0438] Update international visa component

---

app/components/courses/search_result_component.rb
app/components/results/search_result_component.rb
app/view_objects/results_view.rb
spec/components/courses/search_result_component_spec.rb
spec/components/results/search_result_component_spec.rb
spec/factories/providers.rb
spec/fixtures/api_responses/four_courses.json
spec/fixtures/api_responses/one_course.json
spec/fixtures/api_responses/sixty_courses.json
spec/fixtures/api_responses/ten_courses.json
spec/fixtures/api_responses/thirty_courses.json
spec/fixtures/api_responses/two_courses.json
spec/support/results_page_parameters.rb

https://trello.com/c/FqQN9KZt/439-update-visa-search-filter-on-find-api
- Updates the search results view to query the visa fields on courses
- Update the specs
Linked to https://github.com/DFE-Digital/publish-teacher-training/pull/2980

[439] Fix visa filters to query fields on courses

---

app/services/cycle_timetable.rb

[xxxx] Fixed badyear

---

spec/decorators/course_decorator_spec.rb

The linter is failing on CI due to new cops, this is the fix.
🚢

Fix linting issues from new cop

---

Gemfile
app/components/courses/entry_requirements_component.html.erb
app/components/courses/entry_requirements_component.rb
app/decorators/course_decorator.rb
spec/components/courses/entry_requirements_component_spec.rb
spec/decorators/course_decorator_spec.rb
spec/factories/courses.rb

ETP courses
Updated qualifications needed content for ETP courses
Search for an ETP course

[0784] Updated qualifications needed content for ETP courses

---

app/views/result_filters/_degree_required_filter.html.erb
app/views/result_filters/_engineers_teach_physics_filter.html.erb
app/views/result_filters/_qualifications_filter.html.erb
app/views/result_filters/_salary_filter.html.erb
app/views/result_filters/_send_filter.html.erb
app/views/result_filters/_study_type_filter.html.erb
app/views/result_filters/_vacancy_filter.html.erb
app/views/result_filters/_visa_filter.html.erb
spec/features/result_page_filters/engineers_teach_physics_spec.rb
spec/features/result_page_filters/qualifications_spec.rb
spec/features/result_page_filters/required_degree_spec.rb
spec/features/result_page_filters/salary_spec.rb
spec/features/result_page_filters/send_spec.rb
spec/features/result_page_filters/study_type_spec.rb
spec/features/result_page_filters/vacancies_spec.rb
spec/features/result_page_filters/visa_spec.rb

https://trello.com/c/pptKsZYi/823-update-filter-legends-to-make-more-descriptive
Add visually hidden text ("filter") to the filter legends
- Review the markup
Corresponding New Find version https://github.com/DFE-Digital/publish-teacher-training/pull/3145

[823] Add more descriptive context to filter legends

---

app/components/courses/about_schools_component.html.erb
config/locales/en.yml

Add a GIT link To "Where will you train section" for SCITT's and HEI's
Find a SCITT course on the review app and scroll down to the "Where you will train" section.
https://trello.com/c/SCOj6cWU/847-updating-content-and-links-to-git-from-find

Add GIT link to "Where will you train section"

---

cypress/e2e/find-teacher-training/basic.cy.ts
cypress/e2e/find-teacher-training/geocoding.cy.ts

Smoke test
These smoke tests shared states
Cypress is a pain, and caused grief

[XXXX] Fixed CI

---

app/views/pages/accessibility.html.erb
spec/features/view_pages_spec.rb

accessibility statement
Amended accessibility statement
Does it read fine?
https://find-pr-1650.london.cloudapps.digital/accessibility

[0846] Amended accessibility statement

---

app/components/results/search_result_component.rb

Removing unnecessary full stops. 
https://trello.com/c/zTiDlNUc/955-remove-full-stop-at-the-end-of-degree-required

Remove full stops

---

app/views/errors/not_found.html.erb

Updating the 404 page content in line with the prototype
https://trello.com/c/T42G3Stf/959-update-error-pages

Update 404 page content

---

app/views/errors/internal_server_error.html.erb

Updating the 500 page content in line with the prototype
https://trello.com/c/T42G3Stf/959-update-error-pages

Update 500 page content

---

app/views/pages/maintainance.html.erb

Update 503 page content
https://trello.com/c/T42G3Stf/959-update-error-pages

Update 503 page content
