- README.md
- config/initializers/canonical_rails.rb
- config/puma.rb
The publish/manage apps run on `3000` and `3001` already
Change default port to `3002`
🚢
> Update port to 3002

- app/mailers/application_mailer.rb
[Re-raising this PR on the correct branch]
ActionMailer is not yet configured so it blows up in non-dev as code is eager loaded.
> Remove Rails generated ActionMailer file

- Gemfile
- Gemfile.lock
- app/controllers/pages_controller.rb
- azure-pipelines.yml
We want to ensure any newly deployed code is safe
- Add Brakeman gem
- Run Brakeman as part of the build pipeline
> [2642] - Run static analysis as part of the build pipeline

- app/decorators/provider_decorator.rb
- spec/decorators/provider_decorator_spec.rb
Website was returning "http://" if `nil`
Return `nil` from the decorator is website is `nil`
> Fix up website if nil

- app/models/provider.rb
- app/views/courses/_apply.html.erb
- spec/models/provider_spec.rb
DfE Apply Pilot
Add CTA for DfE Apply if the provider is opted in to the DfE Apply Pilot
Find a course for the following providers `R55 1N1 S31 24L 1HQ L06 2LR 254 12K 1OT` then check in the apply section for a button linking to DfE Apply. All other courses should have a link to UCAS.
Best reviewed if you ignore the whitespace changes i.e. https://github.com/DFE-Digital/find-teacher-training/pull/39/files?utf8=%E2%9C%93&diff=unified&w=1.
Note: I also had to add the missing vacancies if statement
> [2744] Add cta for dfe apply

- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
- config/settings.yml
- config/settings/production.yml
- config/settings/qa.yml
- config/settings/staging.yml
- spec/features/view_pages_spec.rb
- spec/requests/pages_spec.rb
Ensure users land back on current FIND if they click the home link or navigate to the root path
- Add search and compare base URL to settings
- Remove redundant pages#show route and controller actions
- Redirect root path to current FIND
- Add request spec to assert redirect
Navigate to the root path or click "Find postgraduate teacher training" in the header
> [2744] Ensure root path is redirected to old find

- app/views/courses/show.html.erb
- app/views/layouts/application.html.erb
- app/webpacker/packs/application.js
- app/webpacker/scripts/back-link.js
New FIND 💃 
Add the same backlink as the current FIND. We can probably do this server-side some once we're fully moved over to Rails.
Click on a course from the results page and watch the backlink appear. Navigate directly to a course and the backlink shouldn't appear.
> [2746] Add back to search results link

- app/views/courses/_about_course.html.erb
- app/views/courses/_about_schools.html.erb
- app/views/courses/_about_the_provider.html.erb
- app/views/courses/_entry_requirements_qualifications.html.erb
- app/views/courses/_fees.html.erb
- app/views/courses/_salary.html.erb
- app/views/courses/_train_with_disabilities.html.erb
- app/views/courses/show.html.erb
- config/locales/en.yml
New course page
- Fix course outcome/qualification
- Remove "Missing" sections accidentally copied from the preview page in manage courses frontend
- An FE course to check the qualification displays
- A course with missing information i.e. about this course shouldn't render the section or in the anchor 
- Changes best viewed ignoring white space - https://github.com/DFE-Digital/find-teacher-training/pull/42/files?utf8=%E2%9C%93&diff=unified&w=1
> 2737 spot check fixes

- app/controllers/filters/study_type_controller.rb
- app/views/filters/study_type/new.html.erb
- config/routes.rb
- spec/features/results/filters/study_type_spec.rb
- spec/site_prism/page_objects/page/result_filters/study_type.rb
- spec/site_prism/page_objects/page/results.rb
We need to mirror the study type filter page on the C# application
- Add a new study type filter page
- Add error handling to filter page
> [2343] Add filters for study type

- app/models/provider.rb
- app/views/courses/_apply.html.erb
- spec/features/courses/show_spec.rb
- spec/models/provider_spec.rb
- spec/site_prism/page_objects/page/course.rb
Apply now has logic in place to direct the appropriate users to
the UCAS Apply service.
-  All users should now see the big green apply button which directs them to the Apply service
**Do not merge as the implementation has not been deployed on Apply yet**
> Send all applicants to Apply

- app/controllers/filters/funding_controller.rb
- app/controllers/results_controller.rb
- app/views/filters/funding/new.html.erb
- config/routes.rb
- config/settings.yml
- config/settings/test.yml
- spec/features/courses/results_spec.rb
- spec/features/result_filters/funding_spec.rb
- spec/requests/results_spec.rb
- spec/site_prism/page_objects/page/result_filters/funding.rb
- spec/support/stub_results_page.rb
A user needs to be able to filter courses based on whether they offer a salary or not.
This card implements the salary filter page. 
Passing on additional params is out of scope for this card.
- Redirect results page to C# in all environments except test
- Disable the redirect in the results page feature spec
- Add salary filter page
> [2345] Build salary filter page

- app/controllers/concerns/filter_parameters.rb
- app/controllers/result_filters/qualification_controller.rb
- app/controllers/results_controller.rb
- app/view_objects/result_filters/qualification_view.rb
- app/views/result_filters/_error_message.html.erb
- app/views/result_filters/qualification/new.html.erb
- azure-pipelines.yml
- config/routes.rb
- spec/features/result_filters/qualifications_spec.rb
- spec/requests/results_spec.rb
- spec/site_prism/page_objects/page/result_filters/qualification.rb
- spec/view_objects/result_filters/qualification_view_spec.rb
Part of the rebuild find epic. This adds the qualification filter page.
* Add `/results/filter/qualification`
* Add a view object for qualification to handle the checkbox state logic and parameters
* Update `FilterParams` to strip `authenticity_token`. This hasn't come up in the tests as it doesn't seem to be passed by I spotted it when running the app.
* Update azure-pipelines.yml with some magic from @rizzkhan1 as CI was failing this PR.
The view object `ResultFilters::QualificationView` is a new pattern for the app. I've added it as it is cleaner and allows us to test the logic that would otherwise be in the view template. This reduces the number of feature specs we need to write to test all scenarios. Performance isn't an issue with the test suite here yet but I think reducing …
> 2344 add qualifications filter

- app/controllers/result_filters/location_controller.rb
- app/views/result_filters/location/new.html.erb
- config/routes.rb
- spec/features/result_filters/location_spec.rb
- spec/site_prism/page_objects/page/result_filters/location.rb
In order to rewrite find we need to recreate the existing [locations filter](https://find-postgraduate-teacher-training.education.gov.uk/results/filter/location)
As the other two filters require additional support, this PR is only for the easiest option (Across England).
- Add the location filter page
- Add support for the parameter `l`
- Remove unsupported parameters 
- Display an error when no option is selected
> [2340] Location filter (Across england)

- app/decorators/course_decorator.rb
- spec/decorators/course_decorator_spec.rb
Apprenticeships come with a salary so the information shown for these courses should match a standalone salaried course i.e.
https://www.find-postgraduate-teacher-training.service.gov.uk/course/2BZ/39NZ#section-financial-support
Return `salaried?` true for apprenticeships 
Should match -
https://www.find-postgraduate-teacher-training.service.gov.uk/course/2BZ/39NZ#section-financial-support
> [2848] Fix financial information for apprenticeships

- app/views/result_filters/location/new.html.erb
- app/views/result_filters/study_type/new.html.erb
We are replacing the search and compare UI filter pages. As they have been built concurrently there are some inconsistencies.
Make the error message consistent across filters -> 
* User the `result_filters/error_message` partial
* Link in to the error
* Render error messages in the 2/3 column of the page
> Make filter error messages consistent

- app/controllers/results_controller.rb
- app/view_objects/results_view.rb
- app/views/results/index.html.erb
- azure-pipelines.yml
- config/routes.rb
- spec/site_prism/page_objects/page/results.rb
- spec/view_objects/results_view_spec.rb
We are rebuilding the results page. The links to the filter pages on the results page need to pass the querystring into the filter pages but also populate some default values if they aren't present.
* Add `ResultsView` to handle this logic
* Add links for each of the filters. The filter boxes themselves are out of scope for this work. There aren't any feature specs in this PR for the links as they can be added to the filter feature specs once the full feature 'journey' (ie visit results, click filter, fill filter, return to results, check courses returned) is present to test.
* Update the azure config again as the fix we put in seems to no longer be required and now actually breaks CI. 
The results page redirects to `localhost:5000` in development by default. Temporarily update …
> 2853 add links for filter pages with default filtering params

- app/views/courses/financial_support/_bursary.html.erb
- app/views/courses/financial_support/_loan.html.erb
- app/views/courses/financial_support/_scholarship_and_bursary.html.erb
To get a loan, postgrad teacher training applicants must apply for UNDERGRADUATE student finance. 
The GOV.UK pages on student finance don't make this clear: https://www.gov.uk/student-finance and https://www.gov.uk/student-finance/new-fulltime-students. (These pages are linked to from the student finance pages on Get into Teaching). 
We contacted GDS about this lack of clarity. As a result, they made an edit to this page: https://www.gov.uk/teacher-training-funding (under 'Postgraduates'). So it's clear there, at least, that postgrads need to apply for undergrad loans - but it's not clear anywhere else. 
We should change the text on course pages in Find to address this. Currently we say "You may also be eligible for a loan while you study" and link to GiT: …
> [2734] Add info to loan text on course page

- app/view_objects/results_view.rb
- app/views/result_filters/study_type/new.html.erb
- app/views/results/_study_type.html.erb
- app/views/results/index.html.erb
- spec/features/result_filters/study_type_spec.rb
- spec/features/results_spec.rb
- spec/site_prism/page_objects/page/results.rb
The study type filter on the results page
Added the study type filter on the results page
if both 'fulltime' and `partime` is omitted or is `False`, the default it to be `true`
:confounded: 
go to `/results` and 
`/results/filter/studytype?`
apart from the actual filtering of the results
> [2771] Added study type filter on the results page

- app/view_objects/results_view.rb
- app/views/results/_vacancy.html.erb
- app/views/results/index.html.erb
- spec/features/results_spec.rb
- spec/site_prism/page_objects/page/results.rb
The vacancies filter on the results page
Added vacancies filter on the results page
go to `/results` and
`/results/filter/vacancy?`
apart from the actual filtering of the results
> [2781] Added vacancies filter on the results page

- app/controllers/result_filters/subject_controller.rb
- app/views/result_filters/subject/new.html.erb
- spec/features/result_filters/subjects_spec.rb
- spec/site_prism/page_objects/page/result_filters/subject_page.rb
```
As a user
I need/want to filter my search by whether or not the subject is a SEND course
So that I can find SEND courses
```
Add the accordion Special educational needs and disabilities (SEND) with a single checkbox: 'Show only courses with a SEND specialism' that passes the `senCourses` parameter as true/false.
<kbd>
</kbd>
:ship:
* https://s121d02-2843-find-as.azurewebsites.net/results/filter/subject?qualifications=QtsOnly,PgdePgceWithQts,Other&fulltime=False&parttime=False&hasvacancies=True&senCourses=True
> [2843] Add SEND to subject filter

- app/controllers/concerns/filter_parameters.rb
- app/controllers/result_filters/location_controller.rb
- app/controllers/result_filters/provider_controller.rb
- app/views/result_filters/_error_message.html.erb
- app/views/result_filters/funding/new.html.erb
- app/views/result_filters/location/new.html.erb
- app/views/result_filters/provider/new.html.erb
- app/views/result_filters/qualification/new.html.erb
- app/views/result_filters/study_type/new.html.erb
- app/views/result_filters/vacancy/new.html.erb
- app/webpacker/styles/application.scss
- config/routes.rb
- spec/features/result_filters/location_spec.rb
- spec/features/result_filters/provider_spec.rb
- spec/site_prism/page_objects/page/result_filters/funding.rb
- spec/site_prism/page_objects/page/result_filters/location.rb
- spec/site_prism/page_objects/page/result_filters/provider_page.rb
- spec/site_prism/page_objects/page/result_filters/qualification.rb
- spec/site_prism/page_objects/page/result_filters/study_type.rb
- spec/site_prism/page_objects/page/result_filters/subject_page.rb
- spec/site_prism/page_objects/page/result_filters/vacancy.rb
- spec/site_prism/page_objects/page/results.rb
- spec/support/api_v3_url.rb
- spec/support/stub_api_v3_resource.rb
As of yet users cannot filter by provider as they can on Search and Compare, in order to replace Search and Compare this functionality should be implemented.
https://www.find-postgraduate-teacher-training.service.gov.uk/?l=3
Implement a search without Javascript and a filter/search results page for searching by provider.
> [2341] Add no-js search and filter page for provider filtering

- app/view_objects/results_view.rb
- app/views/results/_funding.html.erb
- app/views/results/index.html.erb
- spec/features/results_spec.rb
- spec/site_prism/page_objects/page/results.rb
* Displays the filter state as it exists on the [C# results page](https://find-postgraduate-teacher-training.education.gov.uk/results?lat=55.953252&lng=-3.188267&rad=100&loc=Edinburgh,%20UK&lq=Edinburgh,%20UK&l=1&subjects=44&sortby=2&funding=8&qualifications=QtsOnly,PgdePgceWithQts,Other&fulltime=False&parttime=False&hasvacancies=True&senCourses=False).
* Wording is (as appropriate):
- "Courses with and without salary"
- "Only courses with a salary"
* Defaults to "Courses with and without salary"
Co-authored with @faissalMT
> [2776] Add the salary filter display to the results page

- app/controllers/result_filters/funding_controller.rb
- app/controllers/result_filters/location_controller.rb
- app/controllers/result_filters/qualification_controller.rb
- app/controllers/result_filters/study_type_controller.rb
- app/controllers/result_filters/subject_controller.rb
- app/controllers/result_filters/vacancy_controller.rb
- app/views/result_filters/funding/new.html.erb
- app/views/result_filters/location/new.html.erb
- app/views/result_filters/qualification/new.html.erb
- app/views/result_filters/study_type/new.html.erb
- app/views/result_filters/subject/new.html.erb
- app/views/result_filters/vacancy/new.html.erb
- spec/features/result_filters/funding_spec.rb
- spec/features/result_filters/location_spec.rb
- spec/features/result_filters/qualifications_spec.rb
- spec/features/result_filters/study_type_spec.rb
- spec/features/result_filters/subjects_spec.rb
- spec/features/result_filters/vacancy_spec.rb
- spec/site_prism/page_objects/page/result_filters/subject_page.rb
Filter pages needs to have default or updated query parameters otherwise you lose the agility to go back to the previous search result page
Fixed backlink for filter pages
transverse the site from 
1. results page to a filter, 
2. change the filter value / valid and invalid values
3. click back to search results
4. go back to 1 and repeat
> [2901] Fixed backlink for filter pages

- Gemfile
- Gemfile.lock
- app/controllers/result_filters/location_controller.rb
- app/controllers/result_filters/provider_controller.rb
- app/form_objects/result_filters/location_filter_form.rb
- app/helpers/result_filters/location_helper.rb
- app/views/result_filters/_error_message.html.erb
- app/views/result_filters/location/new.html.erb
- config/initializers/geocoder.rb
- config/locales/en.yml
- config/settings.yml
- spec/features/result_filters/location_spec.rb
- spec/form_objects/result_filters/location_filter_form_spec.rb
- spec/site_prism/page_objects/page/result_filters/location.rb
- spec/site_prism/page_objects/page/result_filters/location_filter_results.rb
- spec/support/geocoder_helper.rb
Adds an option to the `/results/filter/location` to allow users to filter requests by location.
- Upon submitting the form, the location query is geocoded and the params are populated with additional key/values (:lq, :lat, :lng)
- If a user's location query returns no results from the Google API then the user is redirected back to the page and an error displays
- Same deal if no option is selected
- After some feedback on the approach taken in certain areas. See comments below
> [2783] - Filter courses by location

- app/view_objects/results_view.rb
- app/views/results/_qualifications.html.erb
- app/views/results/index.html.erb
- spec/features/results_spec.rb
- spec/site_prism/page_objects/page/results.rb
- spec/view_objects/results_view_spec.rb
* Displays the filter state as it exists on the [C# results page](https://www.find-postgraduate-teacher-training.service.gov.uk/results?l=2&subjects=0&qualifications=QtsOnly,PgdePgceWithQts,Other&fulltime=False&parttime=False&hasvacancies=True&senCourses=False).
* Defaults to "All qualifications"
* When all three qualifications, the UI displays "All qualifications"
* When not all three qualifications, the UI lists the qualifications selected.
[https://www.find-postgraduate-teacher-training.service.gov.uk/results](https://www.find-postgraduate-teacher-training.service.gov.uk/results?l=2&subjects=0&qualifications=QtsOnly,PgdePgceWithQts,Other&fulltime=False&parttime=False&hasvacancies=True&senCourses=False)
Co-authored-by: Faissal Bensefia <faissal@madetech.com>
> [2778] Add the qualifications filter display to the results page

- app/views/result_filters/location/new.html.erb
Red legend was not displaying on left hand side when a validation error occurred.
Now it does!
> [2902] - Add validation error legend

- app/views/result_filters/subject/new.html.erb
- app/webpacker/styles/application.scss
The subject page does not style the names of subjects to be bold as is done on Search and Compare.  
Copy the application specific styling from C#.
https://github.com/DFE-Digital/search-and-compare-ui/blob/master/src/Assets/Styles/site.scss#L295  
https://www.find-postgraduate-teacher-training.service.gov.uk/start/subject
> [2904] Fix subject filter styling

- app/views/result_filters/subject/new.html.erb
- spec/features/result_filters/subjects_spec.rb
Subject filtering
Ensure all subjects are ordered A-Z
Example - `http://localhost:3002/results/filter/subject?l=2&subjects=31&qualifications=QtsOnly,PgdePgceWithQts,Other&fulltime=False&parttime=False&hasvacancies=True&senCourses=False`
> [2924] Order subjects list by A-Z

- app/controllers/results_controller.rb
- app/helpers/csharp_rails_subject_conversion_helper.rb
- app/view_objects/results_view.rb
- app/views/results/_subjects.html.erb
- app/views/results/index.html.erb
- spec/features/courses/results_spec.rb
- spec/features/result_filters/funding_spec.rb
- spec/features/result_filters/qualifications_spec.rb
- spec/features/results_spec.rb
- spec/site_prism/page_objects/page/results.rb
- spec/spec_helper.rb
- spec/support/stub_results_page.rb
- spec/view_objects/results_view_spec.rb
Displays the filter state as it exists on the [C# results page](https://find-postgraduate-teacher-training.education.gov.uk/results).
* Subjects are listed in alphabetical order
* "Further education" is treated as just another subject.
* When more than 4 subjects are selected, the first 4 (alphabetically) are listed an the rest are summarised as "and N more..."
* When SEND is selected the UI displays "Only SEND courses" at the top of the list of subjects, and it does not count towards the list of 4 subjects and the "and N more..." rule.
* Defaults to all subjects, without "Only SEND courses".
Compare with [C# version](https://find-postgraduate-teacher-training.education.gov.uk/results?l=3&query=Essex%20Teacher%20Training&qualifications=QtsOnly,PgdePgceWithQts,Other&fulltime=False&parttime= …
> [2779] Add the subjects filter display to the results page

- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_prev_page.html.erb
- app/webpacker/styles/patterns/_pagination.scss
Part of https://trello.com/c/hfgbMP9N/2896-2d-accessibility-audit-followup-find
While looking at [accessibility ticket](https://trello.com/c/hfgbMP9N) I noticed that Rails version of the pagination links were not styled correctly. Along with the text colour the focus styling was not consistent with the rest of the site and it would also fail WCAG 2.1 colour contrast check.
It will not be fixed in the C# version which currently looks like this:
- May need to test this locally so that you can access the rails version on prot 3002 without being redirected to the C# version
> 2896 fix focus colour for pagination link

- app/views/result_filters/subject/new.html.erb
Subjects list
Temporarily remove Philosophy from subjects list until the results page can support it
Example - `http://localhost:3002/results/filter/subject?l=2&subjects=31&qualifications=QtsOnly,PgdePgceWithQts,Other&fulltime=False&parttime=False&hasvacancies=True&senCourses=False`
> [2931] Temp remove Philosophy from subjects list

- app/controllers/result_filters/location_controller.rb
- azure-pipelines.yml
- spec/features/result_filters/location_spec.rb
Radius, a parameter used when searching by location, was being included when searching across England
When across England is selected, reject unneeded parameters
> [2948] Don't include radius when across England search is selected

- app/views/result_filters/subject/new.html.erb
- spec/features/result_filters/subjects_spec.rb
Relates to https://trello.com/c/hfgbMP9N/2896-2d-accessibility-audit-followup-find 
A recent accessibility audit completed in December 2019, revealed
that our accordion component was using aria-controls attribut on the
accordion section headings button but no elements on the page had an id
that matched the aria-controls values.
Aria-controls attribute is used by assistive tech to help users understand
what they are interacting with and what elements are responsible for various
actions.
I used govuk-frontend accordion as a reference for this fix. There are
no visual differences but the html should be reviewed to see the changes.
Buttons aria-control value matches the accordion content section for
the specific section it relates too.
Add a unique id to each accordion section content div and …
> 2896 - Add missing id for aria-controls (Accordion component)

- azure-pipelines.yml
https://dfe-ssp.visualstudio.com/Become-A-Teacher/_build/results?buildId=44747&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=f8ed7bd8-2a7f-56f6-9385-7fc29a8b5b7b
This broken test seems to indicate we have problems when a PR has a single-quote in the title.
Use `cat` and a here-doc instead of `echo` when creating `merge.info` in the pipeline step.
🚢
> Protect pipeline step against PR's containing single quotes in title

- app/helpers/result_filters/subject_helper.rb
- app/views/result_filters/subject/new.html.erb
- spec/features/result_filters/subjects_spec.rb
We were under the impression that the accordions were expanding due to `aria-expanded=` being set but this was incorrect.  
Set the class `govuk-accordion__section--expanded` when a subject area is selected.
Example behaviour from C#:
https://www.find-postgraduate-teacher-training.service.gov.uk/results/filter/subject?l=2&subjects=0,1,2&qualifications=QtsOnly,PgdePgceWithQts,Other&fulltime=False&parttime=False&hasvacancies=True&senCourses=False
> [2895] Refactor accordion and checkbox into components

- app/decorators/subject_decorator.rb
- app/views/result_filters/subject/new.html.erb
- spec/decorators/subject_decorator_spec.rb
- spec/factories/subjects.rb
- spec/features/result_filters/subjects_spec.rb
- spec/site_prism/page_objects/page/result_filters/subject_page.rb
Information about financial incentives and subject knowledge enhancement course availability is not showing on the Subject Filter page.
Add information under each subject that includes:
- Bursaries 
- Scholarships
- SKE courses
| Before       | After          | 
| ------------- |:-------------:| 
| <img width="572" alt="Screenshot 2020-02-12 at 11 03 34" src="https://user-images.githubusercontent.com/38078064/74332020-d0ad4d00-4d8c-11ea-99fb-e48e381cf774.png">| <img width="587" alt="Screenshot 2020-02-12 at 11 02 55" src="https://user-images.githubusercontent.com/38078064/74332035-d7d45b00-4d8c-11ea-8bf9-421ed21f4314.png"> |
Dependent on https://github.com/DFE-Digital/teacher-training-api/pull/1168
- run 2905-add-ske-attribute-to-subject branch of teacher-training-api locally
- visit …
> [2905] Add financial and SKE course availability info on Subjects filter page

- app/views/result_filters/location/_form.html.erb
- spec/features/result_filters/location_spec.rb
- spec/site_prism/page_objects/page/result_filters/location.rb
When the location was preselected in the query string, the content of the 'By postcode, town or city' radio was not showing.
Selecting 'By postcode, town or city' sets the `l` query param to "1". When this param appears in the query we want to reveal the content of this radio.
| Before       | After          | 
| ------------- |:-------------:| 
| <img width="1084" alt="Screenshot 2020-02-12 at 15 03 21" src="https://user-images.githubusercontent.com/38078064/74350965-60172800-4dae-11ea-8bd4-89f450eb3bf2.png">| <img width="1039" alt="Screenshot 2020-02-12 at 15 03 53" src="https://user-images.githubusercontent.com/38078064/74350976-64434580-4dae-11ea-9605-7ad0445bf5be.png">|
- visit http://localhost:3002/results/filter/location?l=1&lat=51.4980188&lng=-0.1300436&loc=Westminster,+London+SW1P …
> [2950] Conditionally reveal the content of Location page radios

- app/view_objects/results_view.rb
- app/views/results/_location.html.erb
- app/views/results/index.html.erb
- app/webpacker/styles/patterns/_filters.scss
- config/settings.yml
- spec/features/results_spec.rb
- spec/site_prism/page_objects/page/results.rb
- spec/view_objects/results_view_spec.rb
[This trello card](https://trello.com/c/I3JgPSeB/2787-l-location-filter-show-filter-on-results-page)
As part of rebuilding this application, adding a location filter to the results page.
Added a location filter to the ResultsView
Add components to render it to the results page
> 2787 l location filter show filter on results page

- app/views/result_filters/subject/_form.html.erb
- spec/factories/subjects.rb
- spec/features/result_filters/subjects_spec.rb
We need to display additional content for "Design and technology" on Subject page.
| Before       | After          | 
| ------------- |:-------------:| 
|<img width="550" alt="Screenshot 2020-02-13 at 09 50 01" src="https://user-images.githubusercontent.com/38078064/74422366-66f17980-4e46-11ea-9a49-b4daa5e2a9e7.png">|<img width="554" alt="Screenshot 2020-02-13 at 09 49 45" src="https://user-images.githubusercontent.com/38078064/74422384-6bb62d80-4e46-11ea-8918-b40c1b04e99b.png">|
- visit http://localhost:3002/results/filter/subject?subjects=8
> [2955] Display additional content for Design and tech on Subject page

- app/views/result_filters/subject/_form.html.erb
- spec/features/result_filters/subjects_spec.rb
- spec/site_prism/page_objects/page/result_filters/subject_page.rb
After an accessibility audit in December 2019, It was suggested
that each subject area should be placed inside its own fieldset
to help screen reader users understand the context of each
subject area options. It was also suggested that we remove the
main fieldset/legend.
No visual changes but you should be able to see the fieldset wrapped around the each group of subject are checkboxes
> 2896 - Place subject areas inside a fieldset

- app/views/courses/qualification/_pgce.html.erb
- app/views/courses/qualification/_pgce_with_qts.html.erb
- app/views/courses/qualification/_pgde.html.erb
- app/views/courses/qualification/_pgde_with_qts.html.erb
- app/views/courses/qualification/_qts.html.erb
- spec/features/courses/show_spec.rb
An issue raised in a recent accessibility audit.
There are abbreviated words present on the page (PGCE with QTS) that have
not been explained in their first instance.
> 2896 - Explain abbreviations for the first time.

- azure/template.json
This is because the rails settings were updated in https://github.com/DFE-Digital/find-teacher-training/pull/94 .
> [2839] - Update Azure template for accessing Google geocode api key

- app/controllers/results_controller.rb
- app/models/course.rb
- spec/features/courses/results_spec.rb
Co-authored-by: Faissal Bensefia <faissal@madetech.com>
[This](https://trello.com/c/tvPnfnbr/2966-find-breaks-when-making-api-call-using-provider-code) Trello card has it
Change the course model to use the shallow_path flag for course codes
> [2966] change course model link to provider code

- app/view_objects/results_view.rb
- app/views/results/_location.html.erb
- app/views/results/_provider.html.erb
- app/views/results/index.html.erb
- spec/features/results_spec.rb
- spec/site_prism/page_objects/page/results.rb
- spec/view_objects/results_view_spec.rb
[See this Trello Card](https://trello.com/c/wjtu9XYW/2829-m-provider-filter-show-filter-on-results-page) for more details. We're adding the provider filter to the page, which is done through a partial. Have also got some logic on the page to determine which filter is shown (location or provider) depending on the "l" param passed through based on the radio button selected. 
Adds a provider partial, and a method to the ResultsView to pull through the query param with the provider name. 
Selecting Across England will show the location filter on the results page 
Whereas selecting a provider shows the provider filter instead
> 2829 provider filter show filter on results page

- app/views/layouts/_cookie-banner.html.erb
- app/views/layouts/application.html.erb
- app/webpacker/styles/components/_cookie-banner.scss
- spec/features/cookie_banner_spec.rb
- spec/site_prism/page_objects/page/results.rb
This is the initial markup and styling needed to support our cookies feature. The banner should not be shown just yet as there is some css that hides it by default. There will be some javascript added later that will determine whether or not to show the banner.
The banner should not be visible at this point but you can review it by doing the following (examples of what it should look can be found below):
1. Visit any page
2. Open the dev tools
3. Remove `app-cookie-banner--hidden` class from the cookie banner
Alternatively,
1. edit `app/views/layout/_cookie-banner.html.erb
2. Remove `app-cookie-banner--hidden` css class on the first line
> 2968 - Initial markup and styling of the cookie banner

- app/controllers/result_filters/subject_controller.rb
- app/helpers/result_filters/subject_helper.rb
- app/views/result_filters/subject/_form.html.erb
- config/locales/en.yml
- spec/features/result_filters/subjects_spec.rb
- spec/helpers/result_filters/subject_helper_spec.rb
- spec/site_prism/page_objects/page/result_filters/subject_page.rb
There is no validation on the subject filter, that exists in the [C# version](https://find-postgraduate-teacher-training.education.gov.uk/start/subject?l=2).
Add validation and display an error to the user. Error messages is linked to the first checkbox.
- visit http://localhost:3002/start/subject?l=2
- click Continue
- _error should appear_
- click Please choose at least one subject
- _it should be linked to the first checkbox ([like in this example](https://design-system.service.gov.uk/components/error-summary/linking-checkboxes-radios/index.html)) and the first accordion should be expanded_
**Review questions:**
- Do we need to be testing the error text "Please choose at least one subject" ?
- Should `no_subject_selected_error?` return `false` instead of `nil`?
Note: I will wait for …
> [2960] Add subject filter validation

- app/controllers/result_filters/location_controller.rb
- spec/features/result_filters/location_spec.rb
Return user back to location wizard on validation error if they started on location wizard and vice versa for location filter page
Fixed validation
After validation users ends up on the root path instead of location path
:shipit:
> [2970] Return user back to location wizard on validation error

- app/controllers/result_filters/subject_controller.rb
- app/views/result_filters/subject/start.html.erb
- spec/features/result_filters/subjects_spec.rb
After validation users ends up on the subject path vs start subject path
Return user back to subject wizard on validation error if they started on subject wizard and vice versa for subject filter page
Fixed validation
After validation users ends up on the start subject path instead of subject path
:shipit:
> [2954] Return user back to subject wizard on validation error

- app/views/layouts/application.html.erb
- app/webpacker/packs/application.js
- app/webpacker/scripts/__snapshots__/analytics.spec.js.snap
- app/webpacker/scripts/analytics.js
- app/webpacker/scripts/analytics.spec.js
We used to automatically add in Google Analytics (GA), we now 
have to ask users for consent before adding cookies to their devices.
At the same time we should only inject GA if the user consents
otherwise they are downloading more javascript that will not be
used or needed.
This commit removes GTM (we decided to not replace GA with GTM).
GA should still load as before but we will add the cookie policy
control to this to ensure it only gets used if the user consents
to cookies
> 2968 - Change how we load in Google Analytics

- app/views/result_filters/funding/new.html.erb
User should be able to click the label to select the inputs on the results funding view.
Match radio and inputs on Results Funding view.
`/results/filter/funding?l=2&subjects=32&qualifications=QtsOnly,PgdePgceWithQts,Other&fulltime=True&parttime=False&hasvacancies=True&senCourses=False`
> [2994] Ensure results filter funding input and radios match

- app/views/layouts/application.html.erb
- spec/features/cookie_banner_spec.rb
Users should not be prompted with the cookie banner on the cookie page. They can set their preferences using the new form which will be added to it.
Currently the banner is not visible but if you go to the the cookies page you should not see any markup in the html relating to the cookie banner.
> 2968 Hide cookie banner on cookie page

- app/controllers/provider_suggestions_controller.rb
- public/robots.txt
- spec/fixtures/api_responses/provider-suggestions.json
- spec/requests/provider_suggestions_spec.rb
The provider autocomplete feature uses a local endpoint ('/provider-suggestions') to query for providers. The autocomplete library is configured to only fire once three characters have been entered in the input field. However because the endpoint is publicly accessible it would be possible to query the endpoint with an invalid query (e.g. less than two characters). 
The provider suggestion query is now validated before passing through to the Teacher Training API. If invalid a 400 response is returned.
> [3004] - Return status 400 (bad request) for invalid provider suggestion query

- app/view_objects/results_view.rb
- spec/features/results_spec.rb
- spec/view_objects/results_view_spec.rb
Modern languages/Philsophy do not have any courses associated with them. To prevent them being counted 
in the "and X more" subjects filter summary, we have subtracted two for now.
- Subtract two from the subject count when all subjects are selected
> [2933] Dont count philsophy/modern languages subjects in total

- app/controllers/sitemaps_controller.rb
- app/views/sitemaps/show.xml.builder
- config/routes.rb
- public/robots.txt
- spec/requests/sitemaps_spec.rb
Sitemap
Add an XML sitemap to replace https://www.find-postgraduate-teacher-training.service.gov.uk/sitemap.txt, not sure why we opted for a TXT version in the c# version when XML is the default.
Note: We need the API to return *all* records and not just the first 10
`/sitemap.xml`
> [3015] Add XML Sitemap

- app/controllers/results_controller.rb
- spec/requests/results_spec.rb
Being able to manually view and test the results page
- Remove redirect to c# results page
`/results`
> [2933] Remove results page redirect

- app/view_objects/results_view.rb
- spec/features/results_spec.rb
- spec/view_objects/results_view_spec.rb
Use Json Api gem's 'total_count' method rather than 'count'. The latter provides the count of the paginated response (i.e. X per page) rather than the total results count
- use of correct method
- added spec
> [3019] - Display correct course count on results page

- app/form_objects/result_filters/location_filter_form.rb
- We do not want to filter geocoding results as there may be users who wish to search for courses near England (e.g Scotland, Wales) within the accepted ranges
- Removes England geocoding restriction
- Brings functionality in line with C# legacy application
> [3041] - Remove England geocoding restriction

- Gemfile.lock
- bin/webpack
- bin/webpack-dev-server
- package.json
- yarn.lock
Dependabot alerted us to a few updates to webpacker and webpack-dev-server. 
Unfortunately dependabot does not follow update paths which this PR does. Here are the instructions (https://github.com/rails/webpacker#upgrading) I followed to update webpacker.
- closes #137 
- closes #134 
- Addresses part of a moderate security vulnerability identified by Github (https://github.com/DFE-Digital/find-teacher-training/network/alert/yarn.lock/serialize-javascript/open)) by updating serialize-javascript v2.1.2 in these dependencies - #136 should fix the outstanding vulnerability.
> Bump @rails/webpacker from 4.0 to 4.2

- app/views/result_filters/provider/new.html.erb
- https://trello.com/c/ZIFxr5BH/3035-provider-search-formatting
- Accessing the non-js page of pick provider
- There were whitespace issues on a text field and submit button below
- This fixes the whitespace between submit button and form field
- Text field was missing wrapping div `govuk-form-group`
- This page is accessible when javascript is disabled
- disable javascript
- navigate to `/results/filter/provider?l=3&query=king`
- open the `Try another provider` details box
- there should be correct spacing between input field and submit button
> [3035] Fix whitespace on pick provider

- app/views/results/index.html.erb
Mobile users would not be able to see or change filters. This bug is in production.
the Filter button that was displayed for mobile users looked broken without any copy. c# version did have some copy
I added the copy which fixed the layout:
> [3043] Fix missing filter button copy for mobile users

- app/controllers/results_controller.rb
- spec/features/results_spec.rb
If provider name is not given fallback to Across England
On clicking the app back button back to the results page
Default to Across England if the provider name is blank
This is to mimic the C# app
- When provider name is blank default to Across England for search results
- Successfully filter to Across England
- Change provider
- Select l3 `By school, university or other training provider`
- Leave this field blank
- Click `Find course`
- Should see validation error
- Click the back button in the app
- Should see Location filtered to `Across England`
> [3023] Fallback to l2 when provider name blank

- config/locales/en.yml
- spec/features/result_filters/provider_spec.rb
Copy update to error message when searching by school, location or other training provider
> [3037] - Provider search validation: copy update

- app/view_objects/results_view.rb
- spec/fixtures/api_responses/courses.json
NB: this fix requires merging https://github.com/DFE-Digital/teacher-training-api/pull/1207
- The 'total_courses' helper method provided by the json_api_client gem is an estimate only (it is calculated by multiplying number of pages by the number per page). This results in course count inaccuracies under certain search conditions
- The course count is now determined by the value provided via the meta object in the API response (See https://github.com/DFE-Digital/teacher-training-api/pull/1207). Doing it in this way also follows the JSON API spec recommendations
- Calculate course count using the value provided in the API response meta object
- Update JSON fixture
> [3057] - Fix course count

- app/helpers/result_filters/location_helper.rb
- spec/helpers/result_filters/location_helper_spec.rb
We agreed that those methods should return `true`/`false` https://github.com/DFE-Digital/find-teacher-training/pull/102#discussion_r379853735. It's making it consistent with the subject_helper methods and adds unit tests.
Errors on location filter page still work 
https://find-teacher-3059-predi-3hvnba.herokuapp.com/results/filter/location
> [3059] Make predicate helper methods consistent and add unit tests

- app/controllers/heartbeat_controller.rb
- config/routes.rb
- spec/requests/heartbeat_spec.rb
DevOps
* [3031] Add a healthcheck endpoint
This new `/healthcheck` endpoint checks whether the dependencies of this
service are up. By implication of having returned a 200 OK status you
can also tell that this service is up.
Failure of dependencies results in a 502 bad-gateway status and a json
body showing which dependencies failed.
Front-door will probably continue to check root `/` for a 200 status as
that doesn't have any dependencies currently, so no need for a ping
endpoint as well.
This code is based on
https://github.com/DFE-Digital/teacher-training-api/pull/1202
:ship:
> [3031] Add a healthcheck endpoint

- app/view_objects/results_view.rb
- app/views/results/_location.html.erb
- spec/features/result_filters/location_spec.rb
- spec/features/results_spec.rb
- spec/view_objects/results_view_spec.rb
- https://trello.com/c/SNDaCBWV/3044-make-find-request-location-filtering
- This hooks up location filtering from backend to the frontend
- Hookup location filtering backend to frontend
- Removed redundant tests, asserting against query parameters
- Rename #distance to #radius
- This PR depends on the backend surfacing the `latitude`, `longitude` and `radius` otherwise this feature will not work
- See https://trello.com/c/UkVHbumo/2835-l-location-filter-add-filtering-to-api
- Should wait for that before this card is tested/merged
- Perform a search with any geocoded location e.g. postcode
- Should see results page
- Correct address shows above google map
- Above google map correct radius should show
- Google maps should show with pin in correct location
- Assuming backend works correctly …
> [3044] Add location filtering

- app/controllers/heartbeat_controller.rb
- config/routes.rb
- spec/requests/heartbeat_spec.rb
Devop
The reason for adding this is because of our other repos publish-teacher-training
and teacher-training-api all have a ping endpoint that azure uses to check
if the service is up and online.
> [3062] Add ping endpoint

- Gemfile
- Gemfile.lock
When running tests the following warning was being logged:
`
WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is
deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.
`
The reason is that chrome-drivers has been deprecated since 2019-03-31.
It is recommended to use `webdrivers` gem (Selenium tests more easily
with automatic installation and updates for all supported webdrivers)
Other references:
stackoverflow.com/questions/55970418/capyabra-selenium-chrome-driver-settings
Replicates this PR https://github.com/DFE-Digital/govuk-rails-boilerplate/pull/197
> [3067] Replace chrome/selenium with webdrivers gem

- Gemfile
- Gemfile.lock
- app/view_objects/results_view.rb
- app/views/results/index.html.erb
- spec/features/result_filters/location_spec.rb
- spec/fixtures/api_responses/two_courses_with_sites.json
- spec/site_prism/page_objects/page/results.rb
- spec/support/results_page_parameters.rb
- spec/view_objects/results_view_spec.rb
When querying courses by location we want course results listings to display the distance to the nearest site and the address of the nearest site.
When displaying the nearest distance the distance is rounded to 0 decimal places if it's less than 1 mile, else it is rounded to 1 decimal place.
- Nearest site and site distance is displayed of user searches by location
- Main address is not displayed if user searches by location
> [3044] - Display distance to nearest site and nearest address

- app/controllers/result_filters/location_controller.rb
- app/view_objects/results_view.rb
- app/views/results/index.html.erb
- spec/features/result_filters/location_spec.rb
- spec/site_prism/page_objects/page/results.rb
- spec/site_prism/page_objects/page/start.rb
- spec/view_objects/results_view_spec.rb
This PR adds a new 'distance' sort by option on the results page
- Distance sort by option only appears if user is searching by location
- Selecting sort by distance returns results ordered by distance to closest site
- in addition to the above this pr also fixes a bug whereby sort params were being appended to the url rather than mutated
- Visit `/location/filter/results` and run a location query (option 1). Once you are on the results page you should see results are automatically sorted by distance. Select other sort options from the drop down and watch the magic show that appears before your eyes.
> [3064] - Add distance to sort by

- app/controllers/sitemaps_controller.rb
- app/models/course.rb
- app/views/sitemaps/show.xml.builder
- spec/factories/courses.rb
- spec/requests/sitemaps_spec.rb
- https://trello.com/c/9oyEkcDp/3066-s-update-find-sitemapcontroller-to-call-the-api-with-the-correct-parameters-to-disable-pagination
- Previously only a subset of courses would show for sitemap as api call was paginated
- This makes the api call with very large pagination window to return full dataset
- This api endpoint has been optimised to only return the data needed to generate the sitemap 
- Make call to optimised endpoint for unpaginated courses
- Changed `last_published_at` to `changed_at`
- `curl http://localhost:3002/sitemap.xml`
- this will make api call and only return needed data
- should return full dataset
- should take under 10 seconds
> [3066] Sitemap is now unpaginated

- app/controllers/result_filters/location_controller.rb
- spec/features/result_filters/location_spec.rb
This fixes a bug where users starting out from the start page
(i.e location page) would be taken straight to the results page if they
search by postcode,town or city. The preferred route was supposed to be
that all location-based search (i.e "search by postcode, town or city"
or "Across the whole of England") should always take the user to the
subjects page to select specific subjects they are interested in.
Provider searches, on the other hand, should take users straight to the
results page.
As the location page (ie "Start page") has a dual purpose if the user
has already searched for some courses but decided to edit the location
then they should not have to go back to the subject page before returning
to the results page.
I found LocationController create method very hard to read …
> [3070] - fix user journey when using the wizard

- app/views/results/index.html.erb
- spec/features/courses/results_spec.rb
The accrediting body on not rendered on the results listing
Fix accrediting body 
/results
> [3095] Fix accrediting body in results

- app/view_objects/results_view.rb
- spec/support/results_page_parameters.rb
The funding option was incorrect on the results by always showing "Student finance if you’re eligible" because we weren't including `subjects` in the API response so each of the `has_scholarship_and_bursary?` and `has_bursary?` was returning false
Include `subjects` in the API response
/results
> [3085] Fix funding option on results page

- app/decorators/course_decorator.rb
- app/view_objects/results_view.rb
- app/views/results/index.html.erb
- spec/decorators/course_decorator_spec.rb
- spec/features/courses/results_spec.rb
- spec/site_prism/page_objects/page/results.rb
- spec/view_objects/results_view_spec.rb
When a candidate filters by courses with and without vacancies we should be showing that information for  each course
Display vacancy info based on the vacancies filter in the params i.e. `hasvacancies=False`
Example - `/results?fulltime=False&hasvacancies=False&l=3&parttime=False&qualifications=QtsOnly%2CPgdePgceWithQts%2COther&query=Berkshire+Teaching+Alliance&senCourses=False`
> [3092]  Show vacancies info when on results page

- app/view_objects/results_view.rb
- spec/features/result_filters/qualifications_spec.rb
- spec/support/results_page_parameters.rb
qualification filter due to mismatch
Fixed qualification filter due to mismatch
`qualifications` vs `qualification`
`QtsOnly` vs `qts`
`PgdePgceWithQts` vs `pgce_with_qts,pgde_with_qts`
`Other` vs `pgce,pgde`
The key & value sent to the `api` was just wrong
Fiddle the qualification filter and look at the rails page
> [3009] Fixed qualification filter due to mismatch

- app/views/result_filters/subject/_form.html.erb
- spec/features/result_filters/subjects_spec.rb
*repro steps*
* selected send from subject list
* visit results page
* then deselect send from subject list
* SEND filter should be removed but was not
https://youtu.be/LAc9KnCSxyU
[3109] Fix inability to de-select SEND subject
:eyes:
> [3109] Fix inability to de-select SEND subject

- app/view_objects/results_view.rb
- spec/view_objects/results_view_spec.rb
- Backend returns all sites including un-geocoded sites for courses
- When calculating nearest site if there is no lat/lng provided it throws an exception
- When working out nearest site for a course
- Ignore any sites that are not geocoded
- These are sites that do not have lat/lng
- Otherwise an exception is thrown
- visit http://localhost:3002/results?fulltime=False&hasvacancies=True&l=1&lat=53.9588365&lng=-1.0794777&loc=York+YO1%2C+UK&lq=York+YO1%2C+UK&parttime=False&qualifications=QtsOnly%2CPgdePgceWithQts%2COther&rad=20&senCourses=False&sortby=2&subjects=31%2C32
- No exception should be thrown and can see results page
- Ordering will be incorrect but will be fixed later by https://github.com/DFE-Digital/teacher-training-api/pull/1240
> [3115] Ignore un-geocoded sites for nearest site

- app/helpers/view_helper.rb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/unprocessable_entity.html.erb
The error page did not have the correct styling or content, it should have looked like: https://www.find-postgraduate-teacher-training.service.gov.uk/xxx
Correct the styling
> [3110] Correct error page styling

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/application_controller_spec.rb
- app/models/base.rb
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/logstash.rb
- config/initializers/semantic_logger.rb
- config/settings.yml
- config/settings/development.yml
- spec/controllers/application_controller_spec.rb
We want to make events log-able and easy to find on Kibana
- Adds `logstash logger` and `rails semantic logger` and configures per environment
- request id logged and sent to V3 API
- Setup 'borrowed' from Publish Teacher Training repo
Note request id logged
Azure config appears to be in place already - https://github.com/DFE-Digital/find-teacher-training/blob/4eb3936c82ad1a12a9be0a61430f01d7f08f528c/azure/template.json#L117
> 3088 logit integration

- app/models/provider_suggestion.rb
- spec/requests/provider_suggestions_spec.rb
NB: this PR depends on https://github.com/DFE-Digital/teacher-training-api/pull/1243
Passing non-ASCII characters into '/provider-suggestions' query params causes the JSONApiClient to throw an `URI::InvalidURIError`:
- Encoding the provider suggestion query prevents the JSONApiClient raising a 'URI::InvalidURIError' if the query contains non-ASCII characters
> [3120] - Encode the provider suggestion query

- app/controllers/result_filters/provider_controller.rb
- spec/features/result_filters/location_spec.rb
Locations page taking users to results page instead of subject page
Ensure the validation does not redirect user away from the url they was submit for
> [3122] Fixed location page validation failure redirects

- app/controllers/result_filters/qualification_controller.rb
- app/view_objects/result_filters/qualification_view.rb
- spec/features/result_filters/qualifications_spec.rb
- spec/view_objects/result_filters/qualification_view_spec.rb
- spec/view_objects/results_view_spec.rb
If the user deselects all qualifications in the qualifications filter, the query parameter is set to `none` and the user is shown a validation failure message. Unfortunately that parameter is also added to the back link on that page. If the user clicks that link, the filter on the results page is empty.
~~To fix this issue `all_qualifications?` returns `true` when the parameter is set to `none`. This is mildly hacky but it would be much more complex to track previous parameters and add logic to manage them so this seems to be a pragmatic approach to this edge case.~~
The parameter has been removed. The results page link passes all three qualifications in the link querystring so the behaviour from there is unaltered. If the user visits the filter directly without querystring params then …
> [3127] Fix qualification backlink after failed validation

- app/webpacker/scripts/autocomplete.js
Sentry errors are being thrown when people include characters which require escaping due to Rack not accepting the request.
- Encode the query in javascript before sending it to the endpoint
- Select "By school, university or other training provider"
- Enter something like "2A%"
- Bonus: We can do wild card queries, and you'll see results that return containing the text "2A"
> [3136] Encode query in javascript for autocomplete

- app/view_objects/results_view.rb
- app/views/results/index.html.erb
- spec/requests/heartbeat_spec.rb
- spec/view_objects/results_view_spec.rb
- Pagination options are missing from results pages under certain conditions
- This add pagination buttons (next/previous) to bottom of results
- The root cause of this regression is not yet known
- This is fixed by explicity calculating total pages and passing to
kaminari view helper
- Fixed deprecation warning
- visit http://localhost:3002/results?fulltime=False&hasvacancies=False&l=3&parttime=False&qualifications=QtsOnly%2CPgdePgceWithQts%2COther&query=Essex+and+Thames+Primary+SCITT&senCourses=False
- there are more than 10 courses so should seen pagination options and able to paginate to second page
> [3134] Fix pagination not showing

- app/views/courses/_apply.html.erb
If a course has no vacancies the "Apply" CTA should not be present
Remove Apply CTA when no vacancies.
`course.has_vanancies` is a decorator method and returns "No" instead of `false`
e.g. http://localhost:3002/course/1HE/368Y#section-apply
> [3145] Remove apply section if no courses

- app/controllers/results_controller.rb
- app/views/layouts/application.html.erb
- azure/template.json
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- spec/requests/results_spec.rb
Being able to manually view and test the results page
- Remove redirect to c# results page
`/results`
> [2933] remove results redirect

- app/controllers/heartbeat_controller.rb
We are getting very voluminous errors being logged to Logit and also into local logs. This is a result of using the gems `rails_semantic_logger` and `httparty`: it seems when `HTTParty` is included into a class/module it defines the method `logger` differently from `ActionController::Base#logger`. SemanticLogger uses this method and as a result an error is raised, and sent to logit with a massive backtrace. (see comment below for a sample)
Don't include `HTTParty` into `HeartbeatController`, use `HTTParty.get` directly instead.
Couldn't find a way to test this, even though we can see this error being logged in `log/test.log` when we run the tests. You might want to truncate that log file on your dev system.
> [3170] don't include HTTParty in heartbeat controller

- config/routes.rb
- config/settings.yml
- config/settings/production.yml
- config/settings/qa.yml
- config/settings/staging.yml
c# (www) is now dead so we need to promote  our new rails app to www instead of www2
Add redirect for www2 and education.gov.uk to www. service
🚢
> [2927] Add redirect for www2 and education to www service

- app/views/errors/unprocessable_entity.html.erb
We seemed to be using a generic error template for 422 errors.
This commit adds a custom error message and provides a contact
email address if users can use if they are experiencing technical
issues with the service
> [3128] Update 422 error page copy

- app/controllers/results_controller.rb
- spec/features/results_spec.rb
- Previously the removed redirect logic was added as there was no validation on the filter form
- Therefore users were able to enter invalid states which would have to be handled in the results page
- As there is now validation on the filter form there is no longer a need to handle these invalid states on the results page
- When provider is blank this previously redirected to `Across England`
- This is no longer needed as filter form now has validation to prevent user from entering this odd invalid state
- Should the user enter this invalid state we still search `Across England` by default
- perform search with blank provider in the form
- should not be able to reach removed redirect logic as form validation prevents user from entering this invalid state
- should be validation that …
> [3178] remove blank provider redirect

- app/views/result_filters/location/_form.html.erb
- app/views/result_filters/qualification/new.html.erb
- app/views/result_filters/study_type/new.html.erb
During migration from c# to Rails, a lot of different developers worked on various pages and were mostly trying to replicate what was done in c#. Unfortunately, this introduced some inconsistency in styling, error messages and interaction when the user clicked on the error summary link.
**Home/Location page**
- Add missing error message when no type of location search is selected [e41e60a]
- reorder the hint/error message so that it matches [govuk-frontend guidelines](https://design-system.service.gov.uk/components/text-input/#error-messages) [40705f1]
- fixes malformed HTML where two elements on the page had the same id. This was done by excluding the keys in the hidden fields. (No visual difference)[d204866]
- fixes an accessibility issue with location/provider labels and text fields …
> [3155] Fix error styling and standardise behaviour across the service

- app/controllers/concerns/filter_parameters.rb
- app/controllers/result_filters/location_controller.rb
- app/controllers/result_filters/provider_controller.rb
- app/views/result_filters/location/_form.html.erb
- app/views/result_filters/provider/new.html.erb
- app/views/shared/_hidden_previous_fields.html.erb
- spec/controllers/concerns/filter_parameters_spec.rb
- spec/features/result_filters/location_back_link_spec.rb
- spec/features/result_filters/location_spec.rb
- spec/views/shared/hidden_previous_fields_spec.rb
When selecting a 'location' filter (or provider filter as they are selected on the same page) there is a back link. We populate the backlink with the values from the original querystring that arrives with the filter page request. When an invalid form is submitted from that page the backlink is rebuilt with the now invalid parameters. If the backlink is clicked a variety of broken results pages are displayed depending on what combination of original and invalid filters are selected. This leads to either an incorrect filter being applied or in some cases no results at all and on '14xxx across England' link being displayed.
Store the parameters from the last valid results page in a set of hidden fields prefixed with `prev_`. In the event of an invalid form being submitted from the location …
> [3125] Backlink on location page returns no results after validation error

- app/controllers/concerns/filter_parameters.rb
- spec/controllers/concerns/filter_parameters_spec.rb
HEAD requests were causing errors as `parameters` was returning `nil`. They should be treated as GET requests in this context.
Treat HEAD requests as GET requests in `FilterParameters`
> [3189] FilterParameters supports HEAD requests

- app/controllers/concerns/filter_parameters.rb
- app/controllers/results_controller.rb
- app/helpers/csharp_rails_subject_conversion_helper.rb
- app/services/convert_deprecated_csharp_parameters_service.rb
- app/services/unescaped_query_string_service.rb
- app/view_objects/result_filters/qualification_view.rb
- app/view_objects/results_view.rb
- app/views/result_filters/study_type/new.html.erb
- app/views/result_filters/vacancy/new.html.erb
- package.json
- spec/controllers/concerns/filter_parameters_spec.rb
- spec/features/result_filters/funding_spec.rb
- spec/features/result_filters/location_spec.rb
- spec/features/result_filters/qualifications_spec.rb
- spec/features/result_filters/study_type_spec.rb
- spec/features/result_filters/subjects_spec.rb
- spec/features/result_filters/vacancy_spec.rb
- spec/features/results_spec.rb
- spec/services/convert_deprecated_csharp_parameters_service_spec.rb
- spec/services/unescaped_query_string_service_spec.rb
- spec/site_prism/page_objects/page/results.rb
- spec/view_objects/result_filters/qualification_view_spec.rb
- spec/view_objects/results_view_spec.rb
- spec/view_objects/suggested_search_link_spec.rb
- yarn.lock
We previously inserted a conversion layer between C# parameters and Rails parameters so that we  would be able to seamlessly redirect between Rails and C# Find. As C# Find has now been retired this functionality is no longer needed.
- Add a conversion and redirection service for C# style parameters in order to avoid breaking bookmarks, and log when C# style parameters are used.  
- Modify existing code to use Rails style parameters. (`parameter_a=True&parameter_b=x,y` to `parameter_a=true&parameter_b[]=x&parameter_b[]=y`)  
- Add some missing tests.  
The following are out of scope for this PR:
- Renaming parameters to use Rails conventions  
- Removing the subject ID/code conversion
> [3157] Remove C# style parameterisation

- app/view_objects/results_view.rb
- app/view_objects/suggested_search_link.rb
- spec/features/suggested_salary_searches_spec.rb
Search suggestions need to appear when searching with salary and getting < 3 results
- Extend current search suggesion logic to encompass salaried searches
> [3028] Add search suggestions when searching with salary

- app/controllers/concerns/filter_parameters.rb
- spec/controllers/concerns/filter_parameters_spec.rb
This resolves the following bug:
Theres a large result set shown on the results page and the user has
used pagination to look through the results. They decide to edit some
filters. After changes to the filter the result set is narrowed down but
the results page tries to take them back to the last set pagination.
This is likely to cause confusion for users or raise errors for us to
investigate. For example the result set is only has 3 courses and the
user was on the 6th page of results.
Search for courses "Across England". Use the pagination and then edit each filter and test the following each time:
1. Try the back link - It should take you back to the page you were last on
2. Update a filter and click "Continue" to go back to the results page - You should be taken to the first page of …
> [3160] Exclude pagination params from filter_parameters

- app/helpers/csharp_rails_subject_conversion_helper.rb
When a non-existent C# subject was specified we raised an error in order to highlight any bugs with the C# conversion. This has ceased to be useful as C# conversion moves towards complete removal.
When trying to convert a C# subject that doesn't exist, return a subject code that cannot exist.
This fix is not nice, this is intentional. It avoids the need for a fix to be implemented outside, which would further embed this code in the system and complicated removing it, because the code outside of this file is correct.
> [3202] Convert to non-existent subject codes to and from C# codes

- app/helpers/csharp_rails_subject_conversion_helper.rb
- spec/controllers/result_filters/subject_controller_spec.rb
- https://trello.com/c/QJ6cXQZU/3212-sentry-error-when-subjects-is-a-string-eg-12
- There fixes an error where users are accessing results with subjects as comma delimited string
- They may be an old style from csharp world
- Handle conversion of comma delimited string of subjects
- visit url seen in sentry. see trello ticket
- previously would throw an error. should now no longer seen an error and see filter page
- can now submit filter page to see results
> [3212] Handle subjects as comma delimited string

- app/view_objects/results_view.rb
- app/view_objects/suggested_search_link.rb
- app/views/results/_try_another_search_text.html.erb
- app/views/results/index.html.erb
- spec/features/suggested_salary_searches_spec.rb
- spec/view_objects/suggested_search_link_spec.rb
- spec/views/results/try_another_search_text_spec.rb
If a user search for salaried courses returns 3 or less results we show them suggested search links. The first link should include salaried and non-salaried courses at a radius that returns more courses than the original search. If widening the radius further returns more results we should show a link to that too. The subsequent links should respect the original filter and only include salaried courses.
If an increment of the radius only returns the same number of courses as the previous radius we don't show the link.
Update the text of the links to better describe the searches that they link to.
> [3029] copy update search suggestion when searching for a salaried course when there are 3 salaried courses

- Dockerfile
Webpacker 5.1.0 removed yarn integrity checker. This commit ensures that
we also use the yarn.lock we generated while developing rather than updating
it. It should also fail if package.json & yarn.lock are out of sync.
Yarn's own maintainer discourages its use:
https://github.com/yarnpkg/yarn/issues/6427#issuecomment-434499073
and suggests the following solution:
Solution
Remove the integrity initializer and the configuration options. Encourage
developers to ensure yarn install in local environments and
yarn install --frozen-lockfile as part of deployment.
Other references:
https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-frozen-lockfile
https://github.com/rails/webpacker/pull/2518
> Add --frozen-lockfile to docker image yarn install

- app/view_objects/results_view.rb
- spec/view_objects/results_view_spec.rb
Vacancies not being shown when user filters by all courses
Fix case of `hasvacancies` param
`https://s121d02-3291-find-as.azurewebsites.net/results?fulltime=false&hasvacancies=false&l=3&parttime=false&qualifications%5B%5D=QtsOnly&qualifications%5B%5D=PgdePgceWithQts&qualifications%5B%5D=Other&query=West+Essex+SCITT&senCourses=false`
> [3291] Show vacancies in results view

- config/routes.rb
- spec/requests/start_spec.rb
This is leftover from c# world, for context there used to be an information page before the location search, that was removed so the homepage became the location search.
Redirect `/start/location` to root
`https://s121d02-3296-find-as.azurewebsites.net/start/location`
> [3296] Redirect start#location to root

- app/controllers/provider_suggestions_controller.rb
- app/models/provider_suggestion.rb
- app/webpacker/scripts/autocomplete.js
- app/webpacker/scripts/autocomplete.spec.js
- spec/requests/provider_suggestions_spec.rb
https://trello.com/c/4nSbRPzG/3276-s-publish-provider-autocomplete-not-encoding-request-correctly
Modify autocomplete encoding to include tests
Linked to https://github.com/DFE-Digital/publish-teacher-training/issues/1025
> Add encoding for autocomplete queries

- azure-pipelines.yml
- terraform/backend.tf
- terraform/provider.tf
- terraform/resources.tf
- terraform/terraform_prod.tfvars
- terraform/terraform_qa.tfvars
- terraform/terraform_staging.tfvars
- terraform/variables.tf
Emit an alert from health-check endpoints on any of the services going down.
Add terraform StatusCake alerts directory in the repo. 
Example: https://dfe-ssp.visualstudio.com/Become-A-Teacher/_releaseProgress?_a=release-environment-logs&releaseId=6131&environmentId=25595
> [3243] Add terraform StatusCake alert directory 

- app/view_objects/results_view.rb
- spec/view_objects/results_view_spec.rb
https://trello.com/c/tWLPyVWv/3260-sset-default-search-radius-if-none-provided
https://sentry.io/organizations/dfe-bat/issues/1590006301/?project=1377944&referrer=slack
* Add default of 20 miles to search radius if it's not included in the query parameters
> Add default radius to location search

- app/controllers/location_suggestions_controller.rb
- config/initializers/handle_bad_encoding.rb
- lib/rack/handle_bad_encoding.rb
- spec/fixtures/api_responses/location-suggestions.json
- spec/lib/rack/handle_bad_encoding_spec.rb
- spec/requests/location_suggestions_spec.rb
- Fix for Sentry issue: https://sentry.io/organizations/dfe-bat/issues/?project=1780060&referrer=slack
- Some requests are being made to the 'location-suggestions' endpoint containing invalid encodings. Rails does not handle this natively and exceptions bubble up
- This new middleware intercepts the request **if** the request path == `/location-suggestions` and drops the query if it contains invalid encodings
- Inspired by: https://jamescrisp.org/2018/05/28/fixing-invalid-query-parameters-invalid-encoding-in-a-rails-app/
- To view the error locally, comment out the `bad_query_encoding` initialiser, and make a request to `/location-suggestions` with a query containing invalid encodings e.g. `BLAH%%fjf%%BLAH` 
- To view the fix, uncomment the initialiser, restart the app, and send the same …
> [3332] - Add bad query encoding middleware

- app/controllers/courses_controller.rb
- app/views/courses/_apply.html.erb
- config/brakeman.ignore
- config/routes.rb
- spec/controllers/courses_controller_spec.rb
- spec/features/courses/show_spec.rb
- https://trello.com/c/wZJSXUte/3304-redirect-pages-for-tracking-usage-of-apply-button
- We want to add reporting for conversions when applying for a course
- Course `Apply` goes thru a redirect
- The additional hop writes to the log for later reporting
- Find any course with a vacancy and visit the course page
- Locate the `Apply` button
- Mouse over it or inspect the element
- Url should remain on the same domain
- Clicking on it should take you to the Apply service and on the correct page
> [3304] Course apply goes thru a redirect

- app/views/courses/_apply.html.erb
- https://trello.com/c/nMi5yG7c/3397-adding-nofollow-to-apply-for-this-course-redirect-link
- We want to reduct false positives on conversion reporting
- Add `rel="nofollow"` to apply links
- Find a course with an apply button
- Link should have `rel` attribute with `nofollow`
> [3397] Add rel nofollow to apply links

- config/settings/research.yml
Almost got it right with a previous PR.
New hostnames for the User Research env are actually prefixed with `s121d03-research-` (not just `s121d03-`).
These will be tested soon as we build out the env anyway.
> [3384] fix hostname settings for research env

- lib/rack/handle_bad_encoding.rb
- spec/lib/rack/handle_bad_encoding_spec.rb
Sentry: https://sentry.io/organizations/dfe-bat/issues/1671504823/?referrer=slack
Add '/provider-suggestions' path to HandleBadEncoding middleware
Curl `/provider-suggestions` endpoint with query containing bad encodings (e.g. `M20%C2%A3@%`). App now returns Bad Request.
> [3332] - Add '/provider-suggestions' path to HandleBadEncoding middleware

- app/helpers/view_helper.rb
- config/settings/development.yml
- config/settings/production.yml
- config/settings/qa.yml
- config/settings/staging.yml
- config/settings/test.yml
- spec/features/courses/show_spec.rb
- spec/helpers/view_helper_spec.rb
https://sentry.io/organizations/dfe-bat/issues/1672714348/?environment=research&project=1780060&referrer=alert_email
We don't need this config setting anymore since we are fully "on the rails"
Remove all traces of "search and compare"
🚢
> [3384] Remove search and compare url

- app/controllers/heartbeat_controller.rb
- spec/requests/heartbeat_spec.rb
This was 502 bad gateway, however 503 service unavailable seems correct, esp
considering this service isn't acting as a proxy/gateway, but as a frontend.
Not a major issue, but since we were revisiting the healthcheck in publish and are using 503 there, it seems to be a good idea to bring other service in-line.
See Publish PR: https://github.com/DFE-Digital/publish-teacher-training/pull/1104
> change healthcheck failure to 503

- app/controllers/courses_controller.rb
- spec/controllers/courses_controller_spec.rb
The University of Bolton don't want candidates to use UCAS APPLY when applying for their courses.
Redirect candidates to their own application service.
- `/course/8N5/V595#section-apply`
- `/course/8N5/Y710#section-apply`
> [3427] Udpate apply link for bolton uni courses

- .gitignore
- terraform/paas/backend.tf
- terraform/paas/data.tf
- terraform/paas/provider.tf
- terraform/paas/resources.tf
- terraform/paas/terraform_qa.tfvars
- terraform/paas/variables.tf
- terraform/paas/versions.tf
Deploying the find webapp and point it to the QA API running on Azure.
Deploy via docker (not via buildpack) as it's DfE strategic direction and our apps are already packaged as docker images. The latest docker image published to dockerhub may be used.
The terraform files should reside in the find repository. We should be able to:
- deploy with the same image: should be no-op
- deploy with a new image: should update the app
- deploy with blue-green strategy should cause no outage
- store terraform state in an Azure storage account
> [3366]-deploy-find-ftt-to-paas-with-terraform

- app/controllers/result_filters/provider_controller.rb
- app/helpers/result_filters/location_helper.rb
- app/views/result_filters/location/_form.html.erb
- config/locales/en.yml
- spec/features/result_filters/location_spec.rb
- spec/features/result_filters/provider_spec.rb
API has been updated to allow for two character provider searches. See https://github.com/DFE-Digital/teacher-training-api/pull/1378
- On the location filter page, a validation error is displayed on the form if the user searches for a provider with a query string containing only one character
- Run this branch against https://github.com/DFE-Digital/teacher-training-api/pull/1378
- Visit `/results/filter/location`. Select other provider and enter a single character in the search field. Validation error should be displayed
- Need some copy guidance on the error message
- In doing this work I noticed that GOVUK form builder needs to be added to this page. Also the ProviderController should be using a form object. Potentially the ProviderController logic should be merged into the …
> [3434] - Location filter provider search with one character

- app/decorators/course_decorator.rb
- spec/decorators/course_decorator_spec.rb
All apprenticeship courses were showing as offering some sort of financial support on the course page on find. They should be showing "Salary". It seems that we forgot to use an existing method in the if statement.
Apprenticeship course
- before
<kbd><img width="662" alt="Screenshot 2020-05-28 at 17 51 48" src="https://user-images.githubusercontent.com/38078064/83170726-e44aac80-a10c-11ea-8f18-a12ca0e15285.png"></kbd>
- after
<kbd><img width="642" alt="Screenshot 2020-05-28 at 17 52 04" src="https://user-images.githubusercontent.com/38078064/83170761-ee6cab00-a10c-11ea-9265-43cd42a5d8b5.png"></kbd>
- all apprenticeship courses should say "Salary" in the Financial support section
> [3421] Show correct financial info for apprenticeships

- .github/workflows/terraform.yml
We need a minimal end-to-end GitHub Actions pipeline to deploy automatically from master to our first paas environment. It should only have the required jobs for deploy. In future sprints we can then iterate and add jobs as required.
We want to explore github actions as it's already used across teacher services, it integrates directly with github and the pipelines are described as code natively.
Any secrets should be stored in github secrets.
We suggest minimal list of jobs:
- build docker image
- push docker image with tag identifying paas (ex: `<commid_id>-paas`)
- deploy the docker image to paas qa with that explicit tag via terraform
> 3446-github-actions-deploy-find-using-terraform

- config/initializers/assets_cache_headers.rb
None of our assets were being cached by the browser because cache-control
was not being set. I set it to a 1 year because our assets use a cache
busting technique so if we were to update their content the filename would
be different and therefore the browser would fetch and use the updated
assets.
Reference:
mikerogers.io/2019/11/02/how-to-set-cache-control-headers-for-rails-webpacker-and-sprockets-assets.html
visit https://s121d02-3409-find-as.azurewebsites.net/
Check asset headers and see if cache control is set to expire in a years time
> [3409] Set cache control in assets header

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/views/courses/_advice.html.erb
- app/views/courses/_apply.html.erb
- app/views/courses/financial_support/_bursary.html.erb
- app/views/courses/financial_support/_loan.html.erb
- app/views/courses/financial_support/_scholarship_and_bursary.html.erb
- app/views/courses/show.html.erb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/unprocessable_entity.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/terms.html.erb
- app/views/result_filters/subject/_form.html.erb
- app/views/results/_provider.html.erb
- app/views/results/_try_another_search_text.html.erb
- app/views/results/index.html.erb
- config/locales/en.yml
- spec/features/result_filters/location_spec.rb
- spec/features/result_filters/provider_spec.rb
- spec/form_objects/result_filters/location_filter_form_spec.rb
- spec/views/results/try_another_search_text_spec.rb
https://smartquotesforsmartpeople.com/
- Improve readability of titles and content by converting quotes to smart quotes, dots to ellipses, and dashes to en and em dashes, using RubyPants
- Fix hardcoded quotes
- Fix casing of Get Into Teaching
Ideally we would fix this upstream, by converting provider names and updating saved content in the database. However we don't know how the old UCAS systems will handle smart quotes in provider and location names.
> Use smart quotes, and other typographical fixes

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
- Convert bullets to asterisks before processing markdown
- Include spaces between asterisks and words when they start a new line
- Add helper spec
| Mistake | Before | After |
|--|--|--|
| No spaces | ![Screen Shot 2020-06-08 at 15 41 20](https://user-images.githubusercontent.com/319055/84049926-f1855800-a9a4-11ea-9f81-18d220fadfa0.png) | ![Screen Shot 2020-06-08 at 15 41 33](https://user-images.githubusercontent.com/319055/84049931-f34f1b80-a9a4-11ea-9bab-cddca858d9e7.png) |
| Using bullets |![Screen Shot 2020-06-08 at 15 42 22](https://user-images.githubusercontent.com/319055/84050023-18438e80-a9a5-11ea-83e5-431aa13a1e03.png) | ![Screen Shot 2020-06-08 at 15 42 31](https://user-images.githubusercontent.com/319055/84050026-1974bb80-a9a5-11ea-84aa-5d835bba1882.png)|
> Fix common mistakes with markdown lists 

- app/helpers/application_helper.rb
- app/lib/govuk/markdown_renderer.rb
- spec/helpers/application_helper_spec.rb
- spec/lib/govuk/markdown_renderer_spec.rb
We don't want to allow providers to mark content in italics, bold or bold italic using markdown.
These are currently undocumented markdown features in Publish, but for any providers who know their markdown, they'll find that they currently work.
This is consistent with how GOV.UK renders content.
> Disable emphasis markdown

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
- https://trello.com/c/FKlI0Stn/3524-sentry-error-nil-for-smart-quotes
- An sentry error was reporting an error around smart quotes when the input was `nil`
- For smart quotes method had nil input and return empty string
- test should pass
- alternatively visit sentry error and run same query on local environment and should not see an error
> [3524] Smart quotes handles nil input

- Gemfile
- Gemfile.lock
- azure-pipelines.yml
We need a way to surface code smells and test coverage. Code climate is used in API and Code Climate was configured to analysis this repo but it did not include the test coverage.
- Adds JavaScript test step to the pipeline so it mirror Publish pipeline
- Reorder tests so linting is run before ruby/JS testing
- Sets simplecov version to 0.17.x so that code climates test reporter will work
- Add new script to the pipeline to push the test coverage score to code climate (This is only run if all our existing tasks pass.
I checked on Code Climate and can confirm that Code climate is receiving the requests sent to it:
Ignore `merge` entries. These are submissions where we run the azure pipeline twice. This is an existing issue where the azure pipeline is run twice, once for the PR and another …
> [3502] Add code climate test coverage

- azure-pipelines.yml
Currently we are not reporting our JavaScript test coverage score. We should
use this new report to improve our test coverage before we look to refactor
our JavaScript.
This does reduce our overall test coverage by 3% leaving us with 95%.
> [3502] Add JavaScript test coverage

- app/decorators/course_decorator.rb
- app/views/courses/_fees.html.erb
- spec/decorators/course_decorator_spec.rb
- https://trello.com/c/lD6tJVsR/3576-s-publish-preview-functionality-should-match-find
- When viewing a course, under the fees section, it is showing the year and not the range of years of the cycle   
- Show year range of course instead of just the starting year
- This matches what is seen in publish when previewing a course
- Find any course
- Navigate to fees section
- For the year it should be a range eg `2019 - 2020` and not a single year `2019`
> [3576] COPY: Course fees now uses year range

- app/services/location_suggestion.rb
- spec/services/location_suggestion_spec.rb
When a user on Find searches for courses by location, currently each result displayed in the autocomplete ends with `, UK`. This is unnecessary because locations should be based in UK.
- Format the response from the google places API to remove "UK" from location suggestions
> [3396] - Remove "UK" from location autocomplete

- app/controllers/heartbeat_controller.rb
- azure-pipelines.yml
- config/routes.rb
- config/settings.yml
- spec/requests/heartbeat_spec.rb
- https://trello.com/c/r3oKBtu9/3579-s-expose-commit-sha-as-sha
- Expose the application SHA at /sha for developer debugging and third party integrations
- At build time append application sha to a file
- This is then part of the docker container where it can be read exposed at /sha
- Visit https://s121d02-3579-find-as.azurewebsites.net/sha
- Should return valid json with correct sha
- Sha should be the merge commit https://github.com/DFE-Digital/find-teacher-training/commit/780f8babae31ab4e0324f93fa16a7498f0701d80
- Checkout this PR
- at the project root directory create a file named `COMMIT_SHA`
- type a random string into this file and save
- visit the app at /sha
- Should return valid JSON with content `{"sha": "the-string-you-entered"}`
> [3579] Expose application SHA at /sha

- app/models/course.rb
- app/view_objects/results_view.rb
- app/views/results/_non_university.html.erb
- app/views/results/_university.html.erb
- app/views/results/index.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/patterns/_definition-list.scss
- spec/factories/courses.rb
- spec/factories/providers.rb
- spec/factories/subjects.rb
- spec/features/result_filters/location_spec.rb
- spec/features/suggested_salary_searches_spec.rb
- spec/features/suggested_searches_spec.rb
- spec/fixtures/api_responses/ten_courses.json
- spec/fixtures/api_responses/two_courses.json
- spec/site_prism/page_objects/page/results.rb
- spec/view_objects/results_view_spec.rb
- spec/views/results/non_university_spec.rb
- spec/views/results/university_spec.rb
based on https://github.com/DFE-Digital/find-teacher-training/pull/295
Added an expand_university filter flag defaulted as `true` for forward motion
Fixed css search results 
Added partial views for non uni vs uni vs fe course results views
Should be review along with https://github.com/DFE-Digital/teacher-training-api/pull/1435, as that should be merge in first due to the boost distance for expanding uni as an area
> 3540 m update find search results for universities as an area

- app/controllers/result_filters/location_controller.rb
- app/controllers/results_controller.rb
- app/services/deprecated_parameters_service.rb
- app/view_objects/results_view.rb
- app/views/result_filters/location/_form.html.erb
- app/views/results/index.html.erb
- spec/features/result_filters/location_spec.rb
- spec/features/suggested_salary_searches_spec.rb
- spec/features/suggested_searches_spec.rb
- spec/services/deprecated_parameters_service_spec.rb
- spec/site_prism/page_objects/page/result_filters/location.rb
- spec/site_prism/page_objects/page/results.rb
- spec/view_objects/results_view_spec.rb
https://trello.com/c/5Sud6IFs/3539-l-remove-radius-from-search-by-location
Users don't need to select a radius, and when they select a small radius of 5 and 10 miles they often filter themselves into a hole – which can lead to the wrong impression that there are no courses near them (eg 0 courses within 5 miles, but actually a good one 5.1 miles away).
- 79% of searches are 20-50 miles
- When users edit the radius, they most commonly switch to a wider radius of 50 miles
- Remove the radius option from location search
- Default to 50 miles
- Remove the sort-by control for location search, replacing with an indicator that results are sorted by distance
- Change "23 courses found" to "23 courses found within 50 miles of you"
* We will want support bookmarked results that use the location …
> 3539 l remove radius from search by location

- .gitignore
- app/views/results/_non_university.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/patterns/_text-ellipsis.scss
- Added an ellipsis to  long location descriptions.
> 3674 truncate location string

- app/views/results/_university.html.erb
- spec/views/results/university_spec.rb
Search results from universities that have multiple locations can be confusing. This [search for example](https://s121d03-research-find-as.azurewebsites.net/results?l=1&lat=51.511408&lng=-0.0251371&loc=E+India+Dock+Rd%2C+London+E14+6JE%2C+UK&lq=East+India+Dock+Road%2C+London+E14+6JE%2C+UK&rad=20&sortby=2&subjects[]=31) returns a result for the University of Cumbria based in Central East London. CUMBRIA IS NO WHERE NEAR EAST LONDON (!!) but they have a location in E London. This confused participants in research.
Where a search returns a course provided by a University with multiple locations we now display `(Nearest of X locations to choose from)`, where `X` is the number of locations (running sites)
- Run the `search for example` above locally to see the changes in the flesh or [see the …
> [3676] - Specify number of locations in search results

- app/view_objects/results_view.rb
- spec/view_objects/results_view_spec.rb
https://trello.com/c/y1qY5V10/3675-sdisplay-instances-of-00-miles-as-01-miles-in-search-results
Used the 'ceil' method to prevent 0.0 miles displaying and added a test.
1) Search Find for a postcode where a school offers training.
2) Ensure that it displays 0.1 miles from you.
> [3675] prevents 0.0 miles displaying + test

- app/services/convert_deprecated_csharp_parameters_service.rb
- spec/services/convert_deprecated_csharp_parameters_service_spec.rb
- https://trello.com/c/9b3X9r0P/3705-nomethoderror-resultscontrollerindex
- https://sentry.io/organizations/dfe-bat/issues/1787111413/?project=1780060&referrer=slack#exception
- Old links to Find were sending subjects as Hash which was not handled correctly
- This fixes old links which send subjects as a hash in the query params
- Visit url in sentry error on localhost
- Should not see error screen or exception
- Should see correct results
> [3705] Handle subjects passed as a Hash

- app/decorators/course_decorator.rb
- spec/decorators/course_decorator_spec.rb
We need to change hyphens to 'to' because it's:
- better/easier for screenreaders to read out "to" than 'dashes'
- recommended in the GDS Style guide https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#dates
- To be consistent with Apply and Publish
The year_range method in course_decorater.rb is using a '-' instead of a 'to'.  year_range is called in one partial about course fees.  
A very simple change of a hyphen to a 'to' in year_range definition
Before
- visit https://www.find-postgraduate-teacher-training.service.gov.uk/course/2AT/AK12#section-fees
After 
- visit https://s121d02-3712-find-as.azurewebsites.net/course/2AT/AK12#section-fees
> [3712] Change '-' to 'to' for year ranges

- app/models/base.rb
- spec/models/base_spec.rb
- https://trello.com/c/2jQCohxd/3684-add-requestid-to-logging-for-find
- Find API client was never adding custom `X-Request-Id` header to api calls
- Previous connection_class was not correctly set therefore the custom request_id header was never sent
- Make API call in review app e.g. https://s121d02-3684-find-as.azurewebsites.net/results?l=2&subjects%5B%5D=31
- Find the request in kibana
- This request will have an associated `request_id`
- Search for this `request_id` in kibana under the api
- It should have correlating log which will be the corresponding API request
> [3684] Add X-Request-Id to API client connection

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
Request ids generated from Find were not showing up in the tags in the error logs in Sentry
[https://trello.com/c/2jQCohxd/3684-add-requestid-to-logging-for-find](url)
Request ids are now assigned to tags section in Sentry
> [3684] Assigns Request_ID to tag in Sentry

- config/initializers/raven.rb
We like to limit exceptions in Sentry to ones that require developer action.
Exclude some errors - see individual commits for detailed explanations.
Trust!
https://trello.com/c/yuYyGcGo/1956-take-ownership-of-the-find-application
- ~[ ] Tested by running locally~
- ~[ ] Product review~
> Only send actionable exceptions to Sentry

- config/webpacker.yml
- Update `webpacker` config to remove deprecation warning - _"The resolved_paths option has been deprecated. Use additional_paths instead."_
> [1969] - Use 'additional_paths' in webpacker config

- app/controllers/courses_controller.rb
- spec/requests/course_spec.rb
- Sentry error: https://sentry.io/organizations/dfe-bat/issues/1816969756/?project=1780060&referrer=slack
- A request to "/course/fonts/Roboto-Regular.ttf" was causing an error to occur because Rails is trying to return the 'not found' page with the wrong content type. It is trying to infer the content type from the bad request, which in this case was `ttf`
- The controller is now hard coded to return in html format.
Not entirely sure if this is the best solution to this problem
> [1971] - Return html format from CoursesController#Show

- config/initializers/raven.rb
- Invalid params being sent to Find endpoints
- https://sentry.io/organizations/dfe-bat/issues/1849156439/?referrer=slack
- Exclude this type of error from Sentry reporting
- It's a client error that we can't do anything about
> [1971] - Exclude "ActionController::BadRequest" errors from Sentry

- app/views/courses/financial_support/_bursary.html.erb
Paul Genders:
> There's a small typo in the 'Financial support' text for certain courses in Find. These courses being: non-salaried ones that don't offer bursaries or scholarships (eg Psychology).
>
> The first line of the text says: "You may also be eligible for a loan while you study – note that you’ll have to apply for undergraduate student finance." The word 'also' should be removed.
>
> eg https://www.find-postgraduate-teacher-training.service.gov.uk/course/B60/33MM
Remove the word as it should work like this in both cases.
Does this make sense?
> Remove "also" from Financial Support section

- app/controllers/courses_controller.rb
- config/initializers/geocoder.rb
- spec/requests/course_spec.rb
- Sentry issue - https://sentry.io/organizations/dfe-bat/issues/1698390575/?project=1780060&referrer=slack
```
DEPRECATION WARNING: render file: should be given the absolute path to a file (called from rescue in show at find-teacher-training/app/controllers/courses_controller.rb:15)
DEPRECATION WARNING: Rails 6.1 will return Content-Type header without modification. If you want just the MIME type, please use `#media_type` instead. (called from block (3 levels) in <top (required)> at find-teacher-training/spec/requests/course_spec.rb:12)
```
- Update Geocoder gem config to automatically rescue any of those things out of our control (e.g. timeouts) but allow to raise for things under our control e.g. if we go over our api limit, or have an incorrect key. See [Geocoder …
> [2001] -Update Geocoder gem configuration | Fix deprecation warnings

- .github/workflows/terraform.yml
GitHub Actions uses the latest available version of terraform if a version is not specified.
Use terraform 0.12 which the terraform files in this repo target.
~- [ ] Tested by running locally~
~- [ ] Product review~
> use terraform 0.12.29 in github actions

- app/views/errors/not_found.html.erb
- app/views/errors/unprocessable_entity.html.erb
- lib/rack/handle_bad_encoding.rb
- spec/lib/rack/handle_bad_encoding_spec.rb
- A large part of find involves building a search query which is then passed on to the Teacher Training API.
- Previously we were sanitising an invalid query, returning all results. Often these errors are triggered by bots and other _evil_ forces 😈 . But rather than being helpful, this may in fact confuse the user who (unmaliciously) passes in an invalid query by accident (e.g. copy and pasting from a word document).
- Example Sentry error - https://sentry.io/organizations/dfe-bat/issues/1778885702/?environment=production&project=1780060&query=is%3Aunresolved
- The middleware has been changed to redirect any invalid requests to the 422 page.
- Update guidance on both the 422 and 404 pages (now more closely in line with Apply's error pages).
- Spin up the app locally and modify your query …
> Create better errors experience - redirect to 422 page when query is invalid

- app/controllers/results_controller.rb
- app/views/errors/unprocessable_entity.html.erb
- app/views/results/index.html.erb
- spec/requests/results_spec.rb
Now that there are less courses active some users are receiving a 500 error on Find when they use bookmarked links for a search query containing an invalid page parameter. I.e they request page 6 of the search query results but there are no longer 6 pages worth of results.
In this situation the Teacher Training API is returning a 400 error but Find is not gracefully handling this and returning a 500.
- Rescue `JsonApiClient::Errors::ClientError` in the `ResultsController` and redirect to the `422` error page.
This is a short term fix. An additional ticket will be created to refactor the `ResultsView` and separate the API query building functionality and subsequent request into separate service.
> Gracefully handle invalid pagination param

- app/controllers/pages_controller.rb
- app/views/pages/cycle_has_ended.html.erb
- config/routes.rb
- config/settings.yml
- spec/requests/end_of_cycle_spec.rb
Find is to be closed on 3rd October (when UCAS stop allowing applications) and will display the interim 'cycle has ended' page.
- Add a new 'cycle has ended' interim page for end of cycle.
- When `Settings.cycle_has_ended` is set to `true`, any requests to the root, search, results and course pages will be redirected to the interim page
- In your `development.local.yml` file, set `cycle_has_ended` to `true`.
- When you try to navigate to root, search, results or course pages, you should be redirected to the interim page
https://trello.com/c/8kQxqDWt/2016-dev-find-cycle-has-ended-interim-page-3oct
> 'Cycle has ended' interim page

- azure/template.json
- config/settings.yml
A number of changes will take place on Find as part of the end of cycle process. To prepare for this we want to be able to toggle end of cycle functionality easily.
- The azure template has been updated so that we can toggle end of cycle functionality via the Azure portal.
- This will be a lot quicker than raising a PR every time we want to update a feature flag.
https://trello.com/c/pF2NLAY9/2070-add-azure-config-for-end-of-cycle-feature-flags
> Update Azure template to include end of cycle feature flags

- app/controllers/pages_controller.rb
- app/views/pages/cycle_ending_soon.html.erb
- config/routes.rb
- spec/requests/cycle_ending_soon_spec.rb
Find to be closed on 3rd October (when UCAS stop allowing applications) and display the interim page shown on [design history](https://bat-design-history.netlify.app/find-teacher-training/end-of-cycle/).
Leading up to the closure we want to show a 'cycle ending soon' interim page
- When Settings.cycle_ending_soon is set to 'true', users will be redirected to the interim page when requesting the root path.
https://trello.com/c/s7Hj3oH0/2058-dev-find-cycle-ending-soon-interim-page
- In your `development.local.yml` file set `cycle_ending_soon` to `true`.
- When you navigate to the the root path you should be redirected to the interim page
- When click the `find courses with vacancies button` you should be taken to `/start/location`.
> 'Cycle ending soon' interim page

- app/views/courses/_apply.html.erb
- app/views/pages/cycle_ending_soon.html.erb
- azure/template.json
- config/settings.yml
- spec/features/courses/show_spec.rb
- As part of the end of cycle process we do not want users to be able to apply for courses from Sep 18th.
- This change allows the button to be toggle on / off via Azure or local settings (default is set to true / display the button).
- To test locally, spin up the app and set the value of `display_apply_button` in your `development.local.yml` to false. When you navigate to a course listing the 'apply for this course' button should not be visible.
https://trello.com/c/vQRmFS25/2067-find-dev-apply-for-this-course-button-changes-18-9-13-10
> End of cycle - remove 'apply for this course' button

- app/views/courses/_apply.html.erb
- spec/features/courses/show_spec.rb
- spec/site_prism/page_objects/page/course.rb
We want users to know why the 'apply for this course' button is disabled as part of the end of cycle process
- Add additional copy for end of cycle. Appears when 'apply for this course' button is disabled.
- Update 'Training locations' heading
- First paragraph under 'Training locations' head disappears when 'apply for this course' button is disabled.
https://trello.com/c/4eMTDtqy/2083-end-of-cycle-copy-changes
> Course page copy updates (end of cycle)

- app/views/layouts/application.html.erb
Small tweak to footer spacing to be consistent with that used by other BAT service footers, and increase space between contact details and support links.
Before:
After:
> Adjust spacing in footer to match that used on other BAT footers

- app/controllers/result_filters/location_controller.rb
- spec/features/result_filters/location_spec.rb
- When `Settings.cycle_ending_soon` is set to `true` the LocationsController was not redirecting back to the ‘start/location’ page when validation errors occur. Instead it was redirecting to the ‘/cycle-ending-soon’ page. This is also causing Find end to end tests to fail ([see related PR](https://github.com/DFE-Digital/find-teacher-training-tests/pull/52)).
- New logic has been added to the LocationsController to detect whether `Settings.cycle_ending_soon` is `true` and if so, will redirect back to ‘/start/location’ when a search validation error occurs.
https://trello.com/c/AidwYrAz/2119-fix-broken-find-end-to-end-tests
> Fix validations on start wizard when nearing end of cycle

- app/views/pages/cycle_ending_soon.html.erb
Some copy updates are required to make it easier for potential candidates to understand the 'end of cycle' event.
Copy changes implemented as per this doc - https://docs.google.com/document/d/1mqgyiSuMag-OHBzMlkiEJCrygEYrm_fVqp_Q1tlHXhM/edit
> Update copy on 'cycle-ending-soon' page

- spec/controllers/result_filters/subject_controller_spec.rb
- spec/decorators/course_decorator_spec.rb
- spec/features/cookie_banner_spec.rb
- spec/features/courses/results_spec.rb
- spec/features/result_filters/funding_spec.rb
- spec/features/result_filters/location_back_link_spec.rb
- spec/features/result_filters/location_spec.rb
- spec/features/result_filters/provider_spec.rb
- spec/features/result_filters/qualifications_spec.rb
- spec/features/result_filters/study_type_spec.rb
- spec/features/result_filters/subjects_spec.rb
- spec/features/result_filters/vacancy_spec.rb
- spec/features/results_spec.rb
- spec/features/suggested_salary_searches_spec.rb
- spec/features/suggested_searches_spec.rb
- spec/models/base_spec.rb
- spec/requests/heartbeat_spec.rb
- spec/requests/results_spec.rb
- spec/support/helpers.rb
- spec/support/stub_subjects_request.rb
- spec/view_objects/results_view_spec.rb
Many of the api test stubs are hard coded to the `2020` cycle year. When stubbing the API we need to concatenate `Settings.current_cycle` into API URL stings so that when the current cycle is updated from `2020` to `2021`, the tests do not break.
- Create [course_url helper](https://github.com/DFE-Digital/find-teacher-training/pull/456/files#diff-3bb5ea059ab3c1c6dbccd241014d50b2) so that it is only defined in one place. 
- Concatenate the settings values for `cycle_year` and `teacher_training_api.base_url` so that any changes in these settings will not break specs
- Lots of file changes sorry, but they're small changes 
- Potentially there is scope to do some more url refactoring but will card this up as priority is to get the specs working …
> Fix broken specs resulting from change in cycle

- app/views/courses/_fees.html.erb
- spec/features/courses/show_spec.rb
Course listings on Find contain section containing information about fees. 
In the fees section:
- Remove EU course fees from table
- Only display a table if UK and International fees are present, else display UK fees inline
**1. A course with UK fees only**
**2. A course with UK and international fees**
https://trello.com/c/UkFQGmVA/2251-add-box-to-display-international-student-fees
> Update course fees display

- app/views/result_filters/subject/_form.html.erb
- Adds information about subject knowledge enhancement courses to `/start/subject`
https://trello.com/c/XLwad9XS/2258-dev-copy-changes-on-find-course-by-subject-page
> Update copy on ‘find course by subject’ page

- config/settings.yml
When Find reopens we need to display courses from the latest cycle
Update app config
When you run the app and search for courses, you should see in the logs that course requests include the 2021 recruitment cycle
https://trello.com/c/usXMOiXv/2177-dev-6th-oct-find-reopens-revert-to-orig-land-page
> Update ‘current_cycle’ to ‘2021’

- app/views/courses/_financial_support.html.erb
- app/views/result_filters/subject/_form.html.erb
- spec/features/courses/show_spec.rb
- The introduction of new course financial incentives is on hold, so in the meantime we need some copy changes to reflect that (as [per this document](https://docs.google.com/document/d/1J98rWHyoRJRM4ozL9HBBhPllWwocFGsrquq8oWV4dzw/edit)).
- Financial incentives info to be reinstated once announced (API work in progress for this)
- Add holding copy to ‘Find a courses by subject’ page and course listing pages
Changes in screenshots below.
https://trello.com/c/YLQfceFb/2290-find-financial-incentive-holding-copy
> Add holding copy for 2021 /20 financial incentives info

- Gemfile
- Gemfile.lock
- azure/template.json
- config/application.rb
- config/settings.yml
- config/skylight.yml
- docs/performance-monitoring.md
```
When I view the Skylight performance monitoring dashboard
I want to see performance monitoring stats per environment (qa, staging, production)
In order to make more informed decisions about performance issues
```
- Configure skylight performance metrics
To run locally, see docs added to this PR
https://trello.com/c/tfpDMdkZ/2295-add-skylight-to-find
> Configure Skylight performance metrics

- .github/workflows/build-deploy.yml
- config/environments/qa_paas.rb
- config/initializers/logstash.rb
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace_variables/qa.tfvars
Write logs to STDOUT and configure logit service in PaaS to send logs to logit.
Use `qa_paas` env for testing in PaaS.
Use `logstash_url` to configure syslog_drain_url
https://trello.com/c/GbIMKsJw/2252-configure-logging-in-paas
> Use syslog_drain to send logs to logstash in PaaS

- .github/workflows/build-deploy.yml
see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
~- [x] Attach to Trello card~
> remove usage of set-env

- app/webpacker/packs/application.js
- app/webpacker/scripts/autocomplete.js
Our autocomplete hammers our server with too many requests.
Use `lodash.throttle` which supports both leading and trailing calls.
Test it in the review app, check the dev console.
https://trello.com/c/FXy5da3M/2299-add-js-autocomplete-back-to-find-provider-and-location-search
> Throttle autocomplete calls

- app/views/courses/_financial_support.html.erb
- app/views/result_filters/subject/_form.html.erb
- spec/features/courses/show_spec.rb
New course financial incentives will be announced on Oct 3.
This PR reverts this financial incentives holding copy
> Revert "Add holding copy for 2021 to 2020 financial incentives info"

- terraform/workspace_variables/qa.tfvars
Set values for `SETTINGS__` variables in PaaS to the same defaults as in Azure.
Change `SETTINGS__` vars to have same values as they are in Azure.
> Make terraform settings vars consistent with other envs

- config/settings/qa_paas.yml
- terraform/modules/paas/data.tf
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
Use find-postgraduate-teacher-training.service.gov.uk domain name in PaaS routes.
Terraform config changes to use `find-postgraduate-teacher-training.service.gov.uk` domain.
https://trello.com/c/aZejdPCE/2327-configure-custom-domain-for-web-app-in-paas
> Change PaaS route to use find-postgraduate-teacher-training.service.gov.uk

- terraform/modules/paas/main.tf
Terraform config uses 0.12.6, change the PaaS module to use the same version.
> Use cf terraform provider v0.12.6

- terraform/modules/paas/main.tf
Fix usage of `routes` inside `for_each` block
> Use correct routes identifier inside for_each

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Split build and deploy jobs into separate actions, 
Deploy job can be reused for all 3 envs.
Trigger smoke tests after deploy action completes.
https://trello.com/c/Zn65eEdu/2349-paas-move-cypress-test-triggers-pipeline-to-github-actions
> Split build & deploy jobs

- app/view_objects/results_view.rb
- config/settings.yml
- spec/features/result_filters/location_spec.rb
- spec/features/suggested_salary_searches_spec.rb
- spec/features/suggested_searches_spec.rb
- Some providers have reported being confused by the ‘boosting’ of HEI search results, whereby their search radius is decreased and promoted higher up in search results.
- Decision has been made to turn this off for now with a view to fixing and turning on again later 🤞 
- Temporarily stop asking the API to increase the radius of HEIs (aka universities)
- Create a flag in settings to easily switch this functionality on / off
> 2378 - Turn off University search results boosting

- .github/workflows/smoke-tests.yml
Checkout find-teacher-training-tests and run the smoke tests workflow in find-teacher-training repo
Create a manual dispatch workflow to run smoke tests for different environments.
> Adding smoke-tests manual dispatch workflow

- config/initializers/semantic_logger.rb
Turns out this approach was not compatible with the standard way of logging and
can result in breaking the indexing for the 'duration' field, breaking
aggregation and other operations reliant on the 'duration' field. The correct
approach is to leave 'duration_ms', fix any discrepencies in the logit filters
to ensure that it's indexed as a number, and then use 'duration_ms' for
aggregation.
> revert duration/duration_ms formatting for logstash

- app/views/layouts/application.html.erb
The Find and Apply Beta banners behave inconsistently. Find prompts users to fill out a Google form and Apply prompts them to raise a support ticket.
Because the services have merged, users don't typically differentiate between them, it doesn't make sense to capture Find satisfaction in a separate Google form. (The inconsistency is also confusing for users who learned to contact support via the Apply beta banner.)
Updates phase banner text to use the same as that used for Apply (except the email subject references Find service not Apply)
https://trello.com/c/RjtSqW9k
> Make Find phase banner consistent with Apply

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/smoke-test.yml
Deployments under [https://github.com/DFE-Digital/find-teacher-training/deployments] was always showing the HEAD ref of master branch, which was not correct.
Tag deployment with the correct commit sha.
Also add turnstyle action on smoke-tests and build workflow to run the workflows sequentially.
> Correct refs for deployments

- .github/workflows/deploy.yml
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
DockerHub requires authentication when pulling images to overcome rate limit restrictions.
Configure PaaS to authenticate with DockerHub before pulling images.
> Authenticate before pulling images from DockerHub

- app/controllers/courses_controller.rb
- config/brakeman.ignore
- spec/controllers/courses_controller_spec.rb
The University of Bolton are only using Apply to manage applications for their courses this year.
Due to this, we should skip the Apply on Apply or UCAS page. This means the candidate should be sent to Apply's sign up page. 
- Send candidates for UOB's courses to the Apply Sign up page
Do you think we should have a before action on Apply to ensure candidates can't access the Apply on Apply/UCAS page in the Apply application? Or is that overkill?
https://trello.com/c/4OiUSedJ/2323-dev-divert-course-pages-for-bolton
> Redirect University of Boltons courses to Apply's sign up page

- azure/template.json
see https://azure.github.io/AppService/2020/10/15/Docker-Hub-authenticated-pulls-on-App-Service.html
Authenticate with DockerHub registry when starting Azure App Service.
Change has been tested in Apply and Find QA.
https://trello.com/c/9hLZbutC/2429-find-pipeline-and-arm-template-changes-to-include-dockerhub-credentials-to-overcome-rate-limit
> Authenticate with DockerHub

- .github/workflows/build.yml
- Dockerfile
- app/controllers/heartbeat_controller.rb
- azure-pipelines.yml
- config/settings.yml
- spec/requests/heartbeat_spec.rb
GET `/sha` to work on PaaS
Set COMMIT_SHA as a docker build arg.
Read `SHA` from env var instead of file.
> COMMIT_SHA as a docker build argument

- terraform/workspace_variables/staging.tfvars
Staging and production should be as similar as possible, to make sure the environments don't differ in subtle ways.
Up the number of instances on staging to 2, like prod.
OK?
N/A
> Use same number of instances on staging as production

- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
Add `www` & `www2` as production hostnames.
Adds support for multiple hostname under the service.gov.uk domain
> Add support for www hostname

- app/controllers/courses_controller.rb
- spec/controllers/courses_controller_spec.rb
Possibly some candidates have bookmarked  course apply links for courses that no longer exist. 
Rescue `JsonApiClient::Errors::NotFound` in `CoursesController#apply` and render the 404 page
Fire up the app locally and try to apply to a non-existent course e.g. http://localhost:3002/course/T92/X13DD/apply.
You should be sent to the 404 page. 
https://trello.com/c/FBdYmobu/2490-small-500-error-occurs-when-candidate-attempts-to-apply-to-a-non-existent-course
> Display 404 page when candidate attempts to apply to non-existent course

- config/settings/qa.yml
- config/settings/qa_paas.yml
- config/settings/research.yml
- config/settings/rollover.yml
- config/settings/staging.yml
Use the prod url for teacher training API, similar to Apply.
Remove not in use environment settings.
> Use prod Teacher training API url across all Find envs

- app/services/location_suggestion.rb
- spec/services/location_suggestion_spec.rb
At the moment, when the locations autocomplete fails, it fails silently. This is because GCP returns errors in the body (see image).
- Check the body for an error_message. If one is present, then send a Sentry error with the GCP error_message.
https://trello.com/c/fH1nK2ko/2498-log-sentry-error-when-autocomplete-fails
> Send a Sentry error when an error is returned in the body of the gcp response

- .github/workflows/deploy.yml
Use the reusable action bat-infrastructure for preparing the environment matrix.
> Use prepare-matrix action from bat-infrastructure

- app/views/result_filters/location/_form.html.erb
- app/views/result_filters/qualification/new.html.erb
- app/views/result_filters/study_type/new.html.erb
- app/views/result_filters/vacancy/new.html.erb
This fixes the fieldset legends, to make sure that they have spacing below them.
> Bugfix: fieldset legend spacing

- app/views/courses/show.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/components/_list.scss
- app/webpacker/styles/components/_map.scss
- app/webpacker/styles/components/_search-results.scss
This moves some CSS which was in `application.scss` into separate partials, named after their components.
`govuk-list--dash` is renamed to `app-list--dash` to follow the [Design System convention](https://design-system.service.gov.uk/get-started/extending-and-modifying-components/) that the `govuk-` prefix is changed to `app-` for app-specific modifiers.
> Move CSS into component partials

- app/webpacker/styles/application.scss
The `.override-button-default` class was added in 70c36ec953f5c12d69670f3fae3a6651ead79dea to style a button as a link, but this got removed in 95559a9a4e9019c1205c00c787ab0a9350b311a6 and so is no longer needed.
> Remove unused CSS style

- .dockerignore
- .github/workflows/build.yml
- Dockerfile
Current docker image size is ~600MB, also there is no caching of the layers in the build pipelines.
Optimise Docker image (introduce layers), this reduces the image size to ~190 MB.
Build time is now ~2.5 mins from 3.5min earlier (without cache).
Use buildx cache in build
https://trello.com/c/pIhqYRLf/2703-find-optimise-dockerfile-use-cache-in-github-actions-workflow
> Optimise Dockerfile and Use buildx in build workflow

- Gemfile
- app/components/feedback_component.html.erb
- app/components/feedback_component.rb
- app/controllers/application_controller.rb
- app/controllers/courses_controller.rb
- app/controllers/results_controller.rb
- app/helpers/view_helper.rb
- app/views/courses/_advice.html.erb
- app/views/layouts/application.html.erb
- app/views/result_filters/provider/new.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/components/_feedback.scss
- spec/features/courses/show_spec.rb
- spec/features/results_spec.rb
- spec/site_prism/page_objects/page/course.rb
- spec/site_prism/page_objects/page/results.rb
We don't have a good mechanism for candidates to provide feedback for the Find service. 
This PR adds a FeedbackComponent which renders on the courses show and results page.
It links to an Apply endpoint and opens in a new tab.
- Add the component
- Add tests
- A bit of a refactor of the view helper
Does this all seem reasonable?
https://trello.com/c/DrnKcnnW/2466-%F0%9F%93%9D-%F0%9F%8F%88-dev-football-add-feedback-prompt-find
> Add feedback component which redirects candidates to apply

- Gemfile
- bin/ruby-version
Dependabot is unable to find the .tool-versions
file when evaluating the Gemfile.
Moving ruby-version script inside bin
> Specify ruby version directly in Gemfile

- app/view_objects/results_view.rb
- app/views/results/index.html.erb
- spec/features/courses/results_spec.rb
- spec/features/result_filters/funding_spec.rb
- spec/features/result_filters/location_spec.rb
- spec/features/result_filters/qualifications_spec.rb
- spec/features/result_filters/study_type_spec.rb
- spec/features/result_filters/subjects_spec.rb
- spec/features/result_filters/vacancy_spec.rb
- spec/features/results_spec.rb
- spec/site_prism/page_objects/page/results.rb
- spec/support/results_page_parameters.rb
- spec/view_objects/results_view_spec.rb
```
As a… user of Find
I need to... see all course with and without vacancies
So that... I can see the full range of courses and providers available in my area
```
- When searching we now display courses with or without vacancies by default
- Always display whether a course has vacancies or not in the course results summary
- Run any search and you will see the search results include courses with and without vacancies
- Regardless of whether you run a search or filter the search by 'vacancies' each course results summary will display a row indicating whether it has vacancies or not
https://trello.com/c/LBpLaXJ2/2693-%F0%9F%97%BA-dev-start-by-showing-all-course-with-and-without-vacancies-by-default
> Change default search results (vacancies)

- app/views/cookie_preferences/_error_message.html.erb
- app/views/shared/_error_message.html.erb
- spec/features/result_filters/location_spec.rb
The DAC December 2020 audit pointed out that we are using titles for error summaries that go against the GDS recommendation.
Changed all occurrences of `You’ll need to correct some information.` to `There is a problem`.
https://trello.com/c/QitTcgV3/2764-dac-quick-wins
> Use standard title for error summaries

- app/webpacker/styles/components/_toggle.scss
- app/webpacker/styles/patterns/_filters.scss
The DAC December 2020 audit reported issues with the contrast of links in the search filters. 
Changed the background colour to use the standard `light-grey` colour from the design system and that we use elsewhere, such as in navigation bars and in the footer.
| - | - |
| ![before](https://user-images.githubusercontent.com/813383/103012769-f8844a00-4533-11eb-8af7-72dbe5fe434b.png) | ![after](https://user-images.githubusercontent.com/813383/103012764-f6ba8680-4533-11eb-8290-9e02e1e8efb0.png)
https://trello.com/c/QitTcgV3/2764-dac-quick-wins
> Lighter background colour for filters to increase contrast for text links

- app/views/results/_try_another_search_text.html.erb
- app/views/results/index.html.erb
A few scenarios on the search results page see `govuk-grid-row` grid container parents added without defining any child columns within them. As this parent class adds a negative margin, this then affects the layout. 
* Remove unnecessary `div`s that apply `govuk-grid-row` styling.
* Fix stray space appearing in message `You can try another search, for example by changing subject or location .` 
| - | - |
| <img width="760" alt="Screenshot 2020-12-23 at 15 54 08" src="https://user-images.githubusercontent.com/813383/103015052-a8a78200-4537-11eb-91a2-15afd5ac3678.png"> | <img width="760" alt="Screenshot 2020-12-23 at 15 53 58" src="https://user-images.githubusercontent.com/813383/103015048-a7765500-4537-11eb-9961-beb534c182f8.png">
https://trello.com/c/JfeBDpdD/
> Fix grid layout on search results page

- app/services/convert_deprecated_csharp_parameters_service.rb
- `Kernel#warn` was being used to log the deprecated c# parameters message, which bypasses JSONification (presumably being preformed by SemanticLogger), and triggering an error with LogStashLogger.
- Use `Rails.logger` instead of `Kernel#warn`
https://trello.com/c/2ZYRIiEs/2773-deprecated-c-parameters-errors-showing-up-in-logit
> Use Rails.logger instead of Kernel#warn

- app/views/result_filters/vacancy/new.html.erb
- Followup to https://github.com/DFE-Digital/find-teacher-training/pull/586
- The C# 'legacy params warning' was firing because the 'has_vacancies' form was using legacy boolean values
- Change form to use Ruby boolean values
https://trello.com/c/2ZYRIiEs/2773-deprecated-c-parameters-errors-showing-up-in-logit
> Ensure form does not use C# legacy boolean values

- app/views/result_filters/subject/_form.html.erb
(Looks like the ID change at some point, but the error summary link wasn't updated.)
There's arguably still an error in that, if the "Primary" accordion section isn't open, then the link doesn't work, and also that the checkboxes themselves aren't shown as being in an error state, with a red line to the left and so on. However if the link was to open the accordion section automatically, then that might be confusing or unexpected, especially for users of assistive technology.
Another alternative considered was to remove the link altogether and just display the text, but this displays as black by default, and the [Design System guidance](https://design-system.service.gov.uk/components/error-summary/) strongly suggests always containing a link, and linking to the first checkbox.
Probably …
> Bugfix: error summary link to first checkbox

- app/helpers/view_helper.rb
- app/views/cookie_preferences/new.html.erb
- app/views/result_filters/location/_form.html.erb
- app/views/result_filters/qualification/new.html.erb
- app/views/result_filters/study_type/new.html.erb
- app/views/result_filters/subject/_form.html.erb
- config/locales/en.yml
This follows the [Design System guidance](https://design-system.service.gov.uk/components/error-summary/) to add a prefix to page titles when there is a validation error so that screen readers read it out as soon as possible.
Implementation [copied](https://github.com/DFE-Digital/apply-for-teacher-training/blob/master/app/helpers/view_helper.rb#L65-L67) from Apply for teacher training codebase.
https://trello.com/c/QitTcgV3/2764-dac-quick-wins
> Add 'Error: ' prefix to page titles when error present

- app/controllers/result_filters/provider_controller.rb
- app/controllers/result_filters/qualification_controller.rb
- app/helpers/result_filters/location_helper.rb
- app/views/result_filters/location/_form.html.erb
- app/views/result_filters/qualification/new.html.erb
- app/views/shared/_error_message.html.erb
- config/locales/en.yml
- spec/features/result_filters/location_spec.rb
- spec/features/result_filters/provider_spec.rb
- spec/form_objects/result_filters/location_filter_form_spec.rb
@gregknight1 reviewed the error message text across the service, to make them more usable and consistent with the GOV.UK Design System.
This also changes the design of the errors within conditionally-revealed fields, to place the red line next to the revealed field only, rather than the whole of the radio fieldset.
https://trello.com/c/i8qZkt3C/2818-improve-error-messages-in-find
https://trello.com/c/QitTcgV3/2764-dac-quick-wins
> Update error message wording

- app/view_objects/results_view.rb
- spec/features/suggested_searches_spec.rb
- A 'suggested search' link is presented to the user when their search query returns no results.
- It is possible for the course count in the search link to be incorrect in instances where the original search query was filtered by location and a course contained multiple sites. This is because distance queries will de-dup courses with multiple sites (reducing the total count). See https://github.com/DFE-Digital/teacher-training-api/blob/master/app/services/course_search_service.rb#L108
- To see this bug in action [view this search query on Find](https://www.find-postgraduate-teacher-training.service.gov.uk/results?fulltime=false&funding=8&hasvacancies=false&l=1&lat=51.553515&lng=-0.1579151&loc=Mansfield+Rd%2C+London+NW3+2HN%2C+UK&lq=NW3+2HN&parttime=true&qualifications%5B%5D=QtsOnly&qualif …
> Fix 'suggested search' link bug

- .github/PULL_REQUEST_TEMPLATE.md
There are some items in the PR template checklist we probably don't need anymore.
Remove the following checklist items:
- 'Make sure all information from the Trello card is in here' -
unnecessary if you're linking the Trello card further up in the
template
- 'Attach to Trello card' - happens automatically via a Trello power-up
- 'Product review' - align Find with Apply's process of doing a product
review post-deploy.
na
> Update Github pull request template

- app/views/result_filters/qualification/new.html.erb
- spec/features/result_filters/qualifications_spec.rb
Changes to Find were agreed following the bug party & design review.
Changed the heading from "**What you will get**" to "**Choose the qualifications to search for**".
Header preview:
https://trello.com/c/lwqKAGF9/2810-dev-find-change-heading-in-filter-by-quals-page
> Updated heading on find: filter by qualification page

- app/views/courses/show.html.erb
- app/views/results/index.html.erb
- app/webpacker/styles/components/_search-results.scss
In a few places, the line height used for provider names creates weird spacing if/when it wraps onto 2 lines. 
This change updates the styles, but also removes the `<br>` character that appears after a provider name; torn on whether that’s a good idea or not… captions in the design system don’t use such a line break, for what it’s worth.
| - | - |
| ![page-title-before](https://user-images.githubusercontent.com/813383/104037332-7ef38980-51cc-11eb-9f0d-1f052bd539d9.png) | ![page-title-after](https://user-images.githubusercontent.com/813383/104038579-34264180-51cd-11eb-902e-f8bf21123332.png)
| ![result-heading-before](https://user-images.githubusercontent.com/813383/104036944-f674e900-51cb-11eb-9294-89d7ef5e5e3d.png) | …
> Fix line-height of provider name in results and page titles

- app/views/result_filters/subject/_form.html.erb
On the find courses by subject page in Find, under the heading 'Get financial support' there is a link to GiT called 'postgraduate loans'
In the bug party it was identified that this link takes the user to a page in GiT that does not mention 'postgraduate' loans.
Changed the link text from "**postgraduate loans**" to "**loans**".
Updated link:
https://trello.com/c/M23yDpb9/2811-dev-find-change-link-text-in-get-financial-support
> Updating the loan link wording on the find course by subject page

- app/decorators/course_decorator.rb
- app/views/courses/show.html.erb
- spec/decorators/course_decorator_spec.rb
When we conducted a design review of Find, we believed the ordering of information and the headings used could be improved, particularly that around locations and placements.
On the course details page the 'How do school/teaching placements work' heading is changed to 'School/Teaching placements'
And the 'School/Teaching placements' heading and content is moved to between 'About this course' and 'Interview process'
New location & text:
https://trello.com/c/iCTm6hlM/2761-%F0%9F%97%BA-dev-find-content-chg-to-school-placements-on-course-dets
> Course page: school/teaching placements header text & location changed

- .rubocop.yml
These were mistakenly overwritten when changing the way we share rules
between Apply and Find in
https://github.com/DFE-Digital/find-teacher-training/pull/602
Just re-adds the lost rules
Does this make sense? Have I missed anything still?
https://trello.com/c/Jc8TqR8u/2825-dev-use-shared-rubocop-config-across-find-and-apply
> Reinstate project specific Rubocop rules

- app/views/pages/privacy.html.erb
The link to the ICO Web site points to a page that no longer exists.
Changed to match the corresponding content in the Apply privacy policy.
Does the content look right?
Does the link work?
https://trello.com/c/fX3reVnJ/2733-broken-link-privacy-policy
> Update link in privacy policy

- Gemfile
- Gemfile.lock
- app/views/courses/_apply.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/cycle_ending_soon.html.erb
The `govuk-components` gem provides component wrappers for some of the standard markup shared across services. This PR explores using these components in Find.
So far:
Not covered here is replacing the Accordion used for subject selection with Accordion component. We have a requirement to render the current selected subject(s) in an expanded section. It doesn't look as though this is possible with the `govuk-components` gem right now, though I think we can raise a PR to add that feature.
All the changes should be invisible except for this one:
Before:
After:
- Per commit recommended
https://trello.com/c/53RWVPVj/2826-dev-use-govuk-view-components-in-find
> Use `govuk-components` gem to replace standard markup

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/initializers/logstash.rb
- config/initializers/semantic_logger.rb
- config/settings.yml
Logstash gem is not used in production,
Logit endpoint is configured as a user_provided_service in PaaS to send logs to logit.
Logstash gem and config are not required.
https://trello.com/c/bvHSkeO4/2859-check-for-api-keys-in-logs-sent-to-logit
> Remove logstash gem

- app/views/courses/qualification/_pgce.html.erb
- app/views/courses/qualification/_pgce_with_qts.html.erb
- app/views/courses/qualification/_pgde.html.erb
- app/views/courses/qualification/_pgde_with_qts.html.erb
- app/views/courses/qualification/_qts.html.erb
- app/views/result_filters/provider/new.html.erb
- app/views/results/_university.html.erb
This is a follow-up to https://github.com/DFE-Digital/find-teacher-training/pull/610 in which we introduced the `govuk-components` gem and began using those components in views. This PR uses the the Details component.
There should be no visible changes as a result of this PR.
https://trello.com/c/53RWVPVj/2826-dev-use-govuk-view-components-in-find
> Use govuk-components `Details` component

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
London Metropolitan University has included a url containing three consecutive dashes ( --- ) inside its 'about course' description. When the url is displayed on Find, RubyPants is converting the three consecutive dashes to an em dash, breaking the link.
[Monster Slack thread](https://ukgovernmentdfe.slack.com/archives/CN1MCQCHZ/p1610725336016200)
The RubyPants config has been updated to ignore three consecutive dashes and therefore not convert to an em dash
https://trello.com/c/mbieHoJC/127-find-url-error
> Update Ruby Pants configuration (dashes)

- Makefile
- config/environments/test.rb
Rspec errors are difficult to find in build results
Setting RAILS_ENV=test and turning off verbose logging in test.rb
use `rspec --format documentation` for better console output
https://trello.com/c/dYRnEQg6/2893-find-github-actions-build-is-not-exporting-rspec-results
> Readable rspec output in build workflow

- Dockerfile
alpine has released version 3.13 with an updated verrsion of node.
Use `ruby-2.7.2:alpine-3.12`
> Fix image to alpine:3.12

- .github/workflows/deploy.yml
- terraform/modules/statuscake/main.tf
- terraform/modules/statuscake/providers.tf
- terraform/modules/statuscake/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace_variables/production.tfvars
- terraform/workspace_variables/qa.tfvars
- terraform/workspace_variables/staging.tfvars
Managing Find StatusCake configuration using terraform.
Find statuscake was managed from Azure pipelines which has now been disabled.
`node_locations` from https://app.statuscake.com/API/Locations/json
Also see https://www.statuscake.com/kb/knowledge-base/my-test-isnt-using-the-locations-i-set/
StatusCake configuration inside terraform
> Manage StatusCake in Terraform

- docs/paas.md
- terraform/modules/paas/data.tf
cf org name is being renamed to dfe
> Rename PaaS org to `dfe`

- .github/workflows/deploy.yml
- terraform/data.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace_variables/production.tfvars
- terraform/workspace_variables/qa.tfvars
- terraform/workspace_variables/sandbox.tfvars
- terraform/workspace_variables/staging.tfvars
Move secrets from GitHub to Azure KeyVault
BAT-INFRA-SECRETS-{ENV} & FIND-APP-SECRETS-{ENV}
stored in Azure KeyVault
Managing secrets in GitHub Secrets makes it difficult to view/edit secrets.
Storing Application Secrets and Infrastructure as separate yaml files in KeyVault 
and accessing them directly using terraform during deployment.
> Manage secrets in KeyVault

- app/views/result_filters/subject/_form.html.erb
- app/webpacker/styles/application.scss
- config/locales/en.yml
- spec/features/result_filters/subjects_spec.rb
```
As a... user looking for teacher training courses
I need to... understand what primary specialisms are
So that... I know which subject options to select
```
- Change page title
- All existing guidance above accordion removed
- Guidance added above primary subject options
- Subject options styles updated
https://trello.com/c/DtWjrwsc/2928-%F0%9F%97%BA-dev-update-guidance-on-subjects-page
> Update subjects filter page guidance

- app/views/courses/_advice.html.erb
- app/views/layouts/application.html.erb
- config/locales/en.yml
Currently the contact information for GIT that we show in the footer differs from the information we show on course pages.
Like we’re doing on Apply (https://github.com/DFE-Digital/apply-for-teacher-training/pull/3995), store common GIT values as localised strings. 
* ~~To render the `nbsp;` in the `opening_times` string, am using `html_safe` method on `t`; is that okay?~~
* Unlike on Apply, have not moved all GIT URLs into the localisation file – should we?
* Noticed that we’re not using `govuk_link_to`; can address in a later PR
https://trello.com/c/wpgn9P98/
> Add localised strings for GIT contact numbers and URLs

- app/views/courses/_apply.html.erb
- app/views/courses/_apply_button.html.erb
- app/views/courses/show.html.erb
- app/webpacker/scripts/locations-map.js
- config/settings.yml
- spec/features/courses/show_spec.rb
We're reworking the locations UX. Part of this design change involves
removing the locations section from the course details page.
- Wrap the `_apply` partial with a new feature flag check.
- Conditionally render the apply button at the bottom of the page if the feature flag is active.
- Conditionally return early from the JS function that initialises the map.
---
---
- Review diff.
https://trello.com/c/h3R0gdap
> Remove location map from course details page

- app/views/courses/_advice.html.erb
- app/views/courses/_apply.html.erb
- app/views/courses/_entry_requirements_qualifications.html.erb
- app/views/courses/_fees.html.erb
- app/views/courses/_fees_and_financial_support.html.erb
- app/views/courses/show.html.erb
```
As a... user looking for teacher training courses
I need to... find out information about a course
So that... I know if I want to apply to it or not
```
- Change ordering of sections
https://trello.com/c/26UU3jvU/2934-%F0%9F%97%BA-dev-update-ordering-of-information-on-course-detail-pages
> Update ordering of information on course detail pages

- app/views/courses/_fees_and_financial_support.html.erb
This is an additional section on the course details page that is being updated to use standardised content, as part of the work to improve guidance for candidates.
The standardised content box has now been added for the 'Financial support' section:
Prototype: https://find-prototype.herokuapp.com/course/1N1/2XT2
This is using the new component & styling added in [#638](https://github.com/DFE-Digital/find-teacher-training/pull/638).
https://trello.com/c/ZX2WSDA1/2938-%F0%9F%97%BA-dev-update-standardised-content-for-financial-support-on-course-detail-pages
> Update financial support partial to use standardised content

- app/views/courses/_apply.html.erb
- app/views/courses/_no_vacancies_warning.html.erb
- app/views/courses/show.html.erb
https://github.com/DFE-Digital/find-teacher-training/pull/655
Refactors:
- Use _apply_button in the _apply partial as well as the root
show.html.erb template
- Make the if branching in show.html.erb clearer
Bug fixes:
- Add a container div with the correct id to fix the 'Apply' link at the
top of the page when ucas_only_locations is switched on
- When the feature is on, show a warning instead of an apply button if
the course has no vacancies
- View diff
https://trello.com/c/oplOt4W5/3005-apply-on-course-details-page-does-not-link-to-new-apply-section
> Refactor apply button rendering based on ucas_only_locations feature

- app/models/course.rb
- app/views/courses/_about_schools.html.erb
- app/views/courses/placement/_hei.html.erb
- app/views/courses/placement/_scitt.html.erb
- app/webpacker/styles/application.scss
- spec/factories/courses.rb
- spec/factories/sites.rb
- spec/features/courses/show_spec.rb
- spec/models/course_spec.rb
In order to improve guidance for candidates trying to understand
how school placements work, standardised content has been added.
As there is a slight difference in the content shown for University
courses and SCITT/School Direct courses, two partials have been added.
|SCITT/School Direct|University|
|-----|-----|
|![SCITT](https://user-images.githubusercontent.com/47917431/107674871-5c530580-6c8f-11eb-8cb4-93b71ef7f242.png)|![University](https://user-images.githubusercontent.com/47917431/107674878-5f4df600-6c8f-11eb-8f75-d4a464252563.png)|
https://trello.com/c/GC2b4xrH/2936-%F0%9F%97%BA-dev-add-standardised-content-for-where-you-will-train-to-course-detail-pages
> Update school placement partials to use standardised content

- docs/feature-flags.md
- terraform/workspace_variables/app_config.yml
This was missing the 'FEATURE_FLAGS' namespace - correct the setting for
QA and update the docs.
> Use correct namespacing for temporary QA feature flag

- app/controllers/results_controller.rb
- app/helpers/result_filters/subject_helper.rb
- app/view_objects/result_filters/new_filters_view.rb
- app/view_objects/results_view.rb
- app/views/new_filters/_all.html.erb
- app/views/new_filters/_hidden_fields.html.erb
- app/views/new_filters/_location_provider_filter.html.erb
- app/views/new_filters/_qualifications_filter.html.erb
- app/views/new_filters/_salary_filter.html.erb
- app/views/new_filters/_send_filter.html.erb
- app/views/new_filters/_study_type_filter.html.erb
- app/views/new_filters/_subjects_filter.html.erb
- app/views/new_filters/_vacancy_filter.html.erb
- app/views/results/index.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/components/_filter.scss
- config/settings.yml
- spec/features/new_results_page_filters/location_and_provider_spec.rb
- spec/features/new_results_page_filters/qualifications_spec.rb
- spec/features/new_results_page_filters/salary_spec.rb
- spec/features/new_results_page_filters/send_spec.rb
- spec/features/new_results_page_filters/study_type_spec.rb
- spec/features/new_results_page_filters/subjects_spec.rb
- spec/features/new_results_page_filters/vacancies_spec.rb
- spec/site_prism/page_objects/page/results_with_new_filters.rb
- spec/view_objects/result_filters/new_filters_view_spec.rb
- terraform/workspace_variables/app_config.yml
```
As a... user searching for teacher training courses
I need to... filter results to only show those that match my requirements
So that... it is easier for to search and compare courses
```
- Add new results page filters as per https://find-prototype.herokuapp.com/results.
- These filters are behind a feature flag (`:new_filters`)
- To see the new features, pull the branch and add `new_filters: true` to your `development.local.yaml`
```
feature_flags:
cycle_ending_soon: false
cycle_has_ended: false
display_apply_button: true
new_filters: true
```
- Please let me know if I have added any HTML, CSS or accessibility violations
- Note that the new filters are not a good candidate for govuk_form_builder, as validations are not required, plus there are some complications around hydrating …
> Add new search filters

- app/views/result_filters/subject/_form.html.erb
Bursary and scholarship info should appear as hint text.
| - | - |
| <img width="620" alt="Screenshot 2021-02-15 at 11 41 00" src="https://user-images.githubusercontent.com/813383/107942204-d41c7b00-6f82-11eb-86d7-693f44a16a7e.png"> | <img width="620" alt="Screenshot 2021-02-15 at 11 40 45" src="https://user-images.githubusercontent.com/813383/107942201-d383e480-6f82-11eb-904c-04c2ab8f65b7.png"> |
> Fix hint text styling on subject options

- app/views/results/index.html.erb
- app/webpacker/styles/components/_search-results.scss
- spec/features/new_results_page_filters/location_and_provider_spec.rb
- spec/features/new_results_page_filters/subjects_spec.rb
- spec/features/result_filters/funding_spec.rb
- spec/features/result_filters/location_spec.rb
- spec/features/result_filters/qualifications_spec.rb
- spec/features/result_filters/study_type_spec.rb
- spec/features/result_filters/subjects_spec.rb
- spec/features/result_filters/vacancy_spec.rb
To make the search result pages more consistent across types of search
(location, across England, provider, no results), and to make it easier
for non-sighted users to know what's changed on the page, we should show
the number of results in the page heading.
- Update markup on results page
- Update all feature specs that look for the heading on the page
> Update search results heading to show number of results

- app/view_objects/results_view.rb
- app/views/new_filters/_location_provider_filter.html.erb
- app/views/new_filters/_subjects_filter.html.erb
- app/views/results/index.html.erb
- app/webpacker/styles/components/_search-results.scss
- app/webpacker/styles/components/_toggle.scss
- spec/site_prism/page_objects/page/results.rb
- spec/site_prism/page_objects/page/results_with_new_filters.rb
Cleans up design, markup and styles around the search results page.
* Use `app-*` prefixed CSS classes
* Refactor classes for search results (list, list item etc.)
* Update markup and review heading sizes for messages that show in different search states
* Remove `rel="prev"` on links to course pages – no idea why that was being used
* Review design of no-JS fallback sort submit button across different viewports
* Use no-visited style for various search UI links
* Fix alignment of ‘New search’ link
* Don’t render `ul` if there are no results to show
* Fix the breakpoint at which toggler shows (for legacy filter sidebar)
| - | - |
| <img width="1038" alt="desktop-before" src="https://user-images.githubusercontent.com/813383/108120851-d1607980-7099-11eb-92d8-738db3ca27db.p …
> Update styles and markup for search results page

- app/views/results/index_new_filters.html.erb
- In https://trello.com/c/Za2awSWs/3050-find-clean-up we forgot to also update the styles in `app/views/results/index_new_filters.html.erb` which is currently feature-flagged
Styles / markup updated
https://trello.com/c/Za2awSWs/3050-find-clean-up
> Fix styling in results page (with new filters)

- app/form_objects/result_filters/location_filter_form.rb
- app/view_objects/results_view.rb
- app/views/results/_no_results.html.erb
- app/views/results/index.html.erb
- config/initializers/devolved_nations.rb
- spec/features/new_results_page_filters/location_and_provider_spec.rb
- spec/features/result_filters/location_spec.rb
- spec/support/geocoder_helper.rb
- spec/view_objects/results_view_spec.rb
- spec/views/results/no_results_spec.rb
We should show different text to users in the devolved nations.
- find the country from the geocode results
- pass it through as a param
- conditionally render different text for each of the devolved nations
- hide search suggestions for devolved nations
- Is it OK to pass the country through as a param?
- I intended to leave all other behaviour unaffected, ie suggested search for England or if you search for Rome etc.
> Show links to relevant teacher training websites

- config/settings.yml
- config/settings/test.yml
- terraform/workspace_variables/app_config.yml
We have created new filters for the search results page
- Turn on `new_filters` feature flag in all deployed environments
- Note that the default for 'test' remains as `false` and is turned on as an where required
- Once the new filters are testing ok a followup PR will be raised to remove the feature flag and any dead code
https://trello.com/c/sZDbLLB9/3059-turn-on-new-filters-feature-flag-in-all-deployed-environments
> Turn on 'new_filters' feature flag on in all deployed environments

- app/views/new_filters/_hidden_fields.html.erb
- config/settings.yml
We forgot to pass lat and long through as hidden fields when someone updates the filters on the results page. As a result of this, if a candidate tries to select additional filters and click apply, no courses are returned as we don't provide the backend with the necessary values for the search.
- Pass lat/long through as hidden fields
I feel like we should be testing that we've got all the required fields before hitting the API.
Not 100% sure where it should live though. Maybe we could add a valid? method to the filter view?
> Fix filters when location is selected

- .github/workflows/deploy.yml
- .gitignore
- Makefile
- terraform/workspace_variables/production.sh
- terraform/workspace_variables/production.tfvars
- terraform/workspace_variables/qa.sh
- terraform/workspace_variables/qa.tfvars
- terraform/workspace_variables/sandbox.sh
- terraform/workspace_variables/sandbox.tfvars
- terraform/workspace_variables/staging.sh
- terraform/workspace_variables/staging.tfvars
Secrets not in correct YAML format might lead to terraform erroring and outputting the values when running the deploy worklow.
To prevent such leaks we validate the secrets for correct YAML before running terraform.
Run secrets validation step before running terraform.
Set key_vault variables as env variables to reuse in make commands.
> Validate secrets in deploy workflow before running terraform

- .rubocop.yml
- app/helpers/view_helper.rb
- app/views/courses/_advice.html.erb
- app/views/courses/_contact_details.html.erb
- app/views/courses/financial_support/_bursary.html.erb
- app/views/courses/financial_support/_loan.html.erb
- app/views/courses/financial_support/_scholarship_and_bursary.html.erb
- app/views/courses/qualification/_qts.html.erb
- app/views/courses/show.html.erb
- app/views/layouts/_cookie_banner.html.erb
- app/views/result_filters/qualification/new.html.erb
- app/views/result_filters/subject/_form.html.erb
- app/views/results/_funding.html.erb
- app/views/results/_location.html.erb
- app/views/results/_no_results.html.erb
- app/views/results/_provider.html.erb
- app/views/results/_qualifications.html.erb
- app/views/results/_study_type.html.erb
- app/views/results/_subjects.html.erb
- app/views/results/_try_another_search_text.html.erb
- app/views/results/_university.html.erb
- app/views/results/_vacancy.html.erb
- lib/rubocop/cop/govuk/govuk_button_to.rb
- lib/rubocop/cop/govuk/govuk_link_to.rb
- lib/rubocop/cop/govuk/govuk_submit.rb
- spec/spec_helper.rb
Follows on from #669.
As Find’s Rubocop inherits from Apply’s config, and now that Apply has added 3 new custom cops to check for various `govuk_` helpers, we need to:
* Add the same custom cops to this project
* Fix the resulting violations
* Disable checks for use of `govuk_submit` (this project doesn’t use the form builder gem)
* Exclude checks for use of `govuk_link_to` in the application layout (footer links don’t use the `govuk-link` class)
For completeness, and given errors will be raised if they are not used, I have also added the following helpers, even though they are currently not used by this project:
* `govuk_button_link_to`
* `govuk_button_to`
Are we fine with this?
https://trello.com/c/Za2awSWs/
> Add custom cops and fix resulting violations

- app/views/results/_no_results.html.erb
- spec/views/results/no_results_spec.rb
Few tweaks to ensure app matches design
* Use medium heading size for heading shown for devolved nation result
* Remove extraneous heading for no results (message already shown in page title)
> Update headings for no result states

- app/view_objects/result_filters/new_filters_view.rb
- app/view_objects/results_view.rb
- app/views/new_filters/_all.html.erb
- app/views/new_filters/_hidden_fields.html.erb
- app/views/new_filters/_study_type_filter.html.erb
- app/views/new_filters/_vacancy_filter.html.erb
- spec/features/new_results_page_filters/location_and_provider_spec.rb
- spec/features/new_results_page_filters/qualifications_spec.rb
- spec/features/new_results_page_filters/salary_spec.rb
- spec/features/new_results_page_filters/send_spec.rb
- spec/features/new_results_page_filters/study_type_spec.rb
- spec/features/new_results_page_filters/subjects_spec.rb
- spec/features/new_results_page_filters/vacancies_spec.rb
- spec/features/result_filters/funding_spec.rb
- spec/features/result_filters/location_spec.rb
- spec/features/result_filters/qualifications_spec.rb
- spec/features/result_filters/study_type_spec.rb
- spec/features/result_filters/subjects_spec.rb
- spec/features/result_filters/vacancy_spec.rb
- spec/features/results_spec.rb
- spec/support/geocoder_helper.rb
- spec/support/results_page_parameters.rb
- spec/view_objects/result_filters/new_filters_view_spec.rb
- spec/view_objects/results_view_spec.rb
This PR addresses a couple of issues as they both related to query. 
The first is ensuring that we only show courses with vacancies by default.
The second is a bug fix that occurs when a candidate searches by location, but subsequently courses in the search results are not sorted by distance. This is because the new filters form was not adding all the location params as hidden fields.
- Change the default behaviour of the search functionality to show courses with vacancies only. 
- Add missing parameters as missing fields and add test missing coverage.
- Review by commit
- Spin up the app and run any search. You should see results are automatically filtered by courses with vacancies. Any subsequent filtering by location should result in the expected behaviour - courses should be ordered …
> Default filters to show courses with vacancies by default | Fix missing params

- app/views/courses/placement/_scitt.html.erb
- spec/features/courses/show_spec.rb
We've received some concerns from providers about the new schools placement guidance on the course show page
- Offending paragraph removed whilst further user testing is undertaken
https://trello.com/c/lpBrddjm/3080-remove-school-placement-guidance-from-find-and-publish
> Remove schools placement guidance

- config/settings/staging.yml
Test connection from Find to TTAPI on PaaS before migrating TTAPI over to PaaS
Point staging to https://teacher-training-api-prod.london.cloudapps.digital (TTAPI Paas Prod) for testing.
> TTAPI PaaS for testing

- app/views/result_filters/provider/new.html.erb
The provider autocomplete is not wired up on the Visit the _try another provider_ page.
Wire up the provider autocomplete using the same markup as elsewhere in the application.
- How should we test this? It's not covered by the JS tests and we don't have JS enabled feature specs?
- Note that the fix applied to the other provider autocomplete in https://github.com/DFE-Digital/find-teacher-training/pull/679 will also apply to this one.
https://trello.com/c/04BwX3x4/2004-find-provider-autocomplete-not-wired-up
> Wire up provider autocomplete on 'pick a provider' page

- app/webpacker/packs/application.js
- app/webpacker/scripts/autocomplete.js
When a user searches for a provider on the initial search page on Find, when they select a provider they are taken to a page where it shows all the providers which contain the search term they were using. e.g. with search term _Oxford University_.
This is happening because of the way the autocomplete works in concert with the ResultFilters::ProviderController. The values displayed in the 'dropdown' are a combination of the provider name and code but only the name is used to populate the text field that is posted to the controller. The controller then uses the name to search for matches, only when there is one exact match do you get the expected behaviour. In the case of Oxford University the name matches two providers (returned by the TTAPI) hence you don't go straight to the courses for …
> Attempt to fix provider autocomplete

- app/views/courses/_advice.html.erb
- app/views/courses/_contact_details.html.erb
- app/views/courses/show.html.erb
- config/locales/en.yml
Update the contact details section to be inline with other copy changes.
- changed "Contact details" to "Contact this training provider"
- updated opening hours from "8am to 8pm" to "8.30am to 5pm"
- changed the opening hours string from "Monday to Friday, 8.30am to 5pm (except public holidays)" to "8am to 8pm, Monday to Friday"
- updated the copy in the "advice about teaching section"
- updated the details in the footer of the page
https://trello.com/c/67mWQbAv/3057-changing-contact-details-section-on-provider-page-in-find
> Update contact section

- app/controllers/sitemaps_controller.rb
Currently Find makes a very expensive call to the API whenever the sitemap is generated - see https://github.com/DFE-Digital/find-teacher-training/blob/master/app/controllers/sitemaps_controller.rb#L1
When the production Teacher Training API was recently migrated over to PAAS this caused outages (502) whenever a call to the sitemap was made on Find.
- Add a 24 hour cache for sitemap requests
https://trello.com/c/sijB88eS/3129-cache-find-sitemap
> Implement a 24 hour cache for sitemap requests

- app/controllers/sitemaps_controller.rb
Currently Find makes a very expensive call to the API whenever the sitemap is generated - see https://github.com/DFE-Digital/find-teacher-training/blob/master/app/controllers/sitemaps_controller.rb#L1
- Previously we were caching the API response used to generate the sitemap, however this can be quite inefficient as we may have up to 4 instances of Find running at one time.
- Instead we now cache the sitemap itself by setting the Cache-Control header, which will be respected by CloudFront
https://trello.com/c/sijB88eS/3129-cache-find-sitemap
> Set Cache-Control header in SitemapsController

- app/helpers/result_filters/subject_helper.rb
- app/views/result_filters/subject/_form.html.erb
- spec/features/result_filters/subjects_spec.rb
- spec/site_prism/page_objects/page/result_filters/subject_page.rb
We have been using `govuk-components` to simplify (and standardise) some of the markup (see https://github.com/DFE-Digital/find-teacher-training/pull/610). Originally we were unable to use the `Accordion` component because it didn't have an `expanded` option. Now that's been added (see https://github.com/DFE-Digital/govuk-components/pull/115) we can used it.
- There should be no visible changes.
- Had to change the `subject_area_is_selected?` helper - I'm not sure how this worked with the old markup either because it was comparing ids with subject codes.
- Also lost a few `data-qa` attributes (because they are not part of the govuk-components markup). This required a few tweaks to the SitePrism page selectors - these are now using a selector based on an existing CSS class rather than a …
> Attempt to use Accordion component for subject selection

- app/components/advice_component.html.erb
- app/views/courses/_about_schools.html.erb
- app/views/courses/_fees_and_financial_support.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/components/_advice.scss
As a... provider
I need to... see where standardised content comes from
So that... I know that this content has not been written by a Publish user
* Added a caption above boxout titles that says _Advice from Get Into Teaching_
* The left border uses GITs green brand colour
| - | - |
| ![Before](https://user-images.githubusercontent.com/813383/110515287-22471900-8100-11eb-9416-07782a6fd8aa.png) | ![After](https://user-images.githubusercontent.com/813383/110515282-2115ec00-8100-11eb-9f61-732308f9bad6.png) |
https://trello.com/c/yabdtxxJ/
> Show ‘Advice from Get Into Teaching’ for headings on structured content

- app/views/courses/_entry_requirements_qualifications.html.erb
- spec/features/courses/show_spec.rb
Under entry requirements, for the qualifications currently both the GIT advice box and the provider content is rendered on the page. So that candidates can better understand the course requirements, it will now render the provider generated content - if they have entered it. If they haven't, then the page will render the standard GIT qualifications advice box.
* Update title from **Qualifications** to **The qualifications you need**
* Page will only render the qualifications boxout if a provider *has not* provided a value for `required_qualifications`.
|Provider generated content|GIT content|
|----|----|
|![Screenshot 2021-03-10 at 14 42 06](https://user-images.githubusercontent.com/47917431/110646496-d99a6900-81ae-11eb-9a07-d6b37d3daf8b.png)|![Screenshot 2021-03-10 at 14 41 …
> Conditionally render course qualification guidance

- app/views/courses/_about_schools.html.erb
- app/views/courses/show.html.erb
- spec/features/courses/show_spec.rb
Some school direct providers allow you to pick a location (and they list all of their locations), but our guidance says you can’t choose, which contradicts this.
Until we have a revised solution, remove this box from School Direct providers.
The ‘Where you will train‘ box does not appear on School Direct or PG apprenticeship courses
https://trello.com/c/ZMzl1hFe/3156-find-remove-where-you-will-train-grey-box-from-school-direct-providers
> Update which placement partial to render for school placements

- app/helpers/view_helper.rb
- app/views/cookie_preferences/new.html.erb
- app/views/courses/_about_schools.html.erb
- app/views/courses/_advice.html.erb
- app/views/courses/_apply_button.html.erb
- app/views/courses/_contact_details.html.erb
- app/views/courses/_no_vacancies_warning.html.erb
- app/views/courses/qualification/_pgce.html.erb
- app/views/courses/qualification/_pgce_with_qts.html.erb
- app/views/courses/qualification/_pgde.html.erb
- app/views/courses/qualification/_pgde_with_qts.html.erb
- app/views/courses/qualification/_qts.html.erb
- app/views/courses/show.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/cycle_ending_soon.html.erb
- app/views/pages/privacy.html.erb
- app/views/result_filters/_vacancy_filter.html.erb
- app/views/result_filters/location/new.html.erb
- app/views/result_filters/provider/new.html.erb
- app/views/result_filters/subject/_form.html.erb
- app/views/result_filters/subject/new.html.erb
- app/views/result_filters/subject/start.html.erb
- app/views/results/_university.html.erb
- app/views/results/index.html.erb
- lib/rubocop/cop/govuk/govuk_link_to.rb
- spec/helpers/view_helper_spec.rb
In addition to individual components, `govuk-components` provides a number of link helpers that replicate those we had created. It also provides helpers that call component rendering methods.
* Remove helpers and tests for `govuk_button_to`, `govuk_link_to` and `govuk_mail_to` helpers
* Replace `govuk_back_link_to` helper with `GovukComponent::BackLink` component (via `govuk_back_link` helper) and remove associated tests
* Use `govuk_skip_link` helper
* Use component helper methods from `govuk-components` instead of rendering components directly
* Refactor `bat_contact_mail_to` helper to call `govuk_mail_to` helper (and use it where it should be used)
* Use consistent syntax style for listing component attributes 
* Fix linting errors
Is using the helper shortcuts instead of calling …
> Use helpers provided by govuk-components

- app/views/results/index.html.erb
- config/initializers/inflections.rb
- spec/features/courses/results_spec.rb
- spec/site_prism/page_objects/page/results.rb
On the results page, we split the course description row into two rows.
Before
After
I've used the `inflections.rb` file so that when we `humanize` the strings like `pgce_with_qts` it knows that they're acronyms and is able to correctly render this as `PGCE with QTS`.
https://trello.com/c/JjxzkEW0/3246-dev-split-course-row-into-qualification-and-study-type-rows
> Split course description row

- config/locales/en.yml
Get into teaching is now out of beta, and so the phone number and URL has changed.
> Update "Get into teaching" URL and phone number

- app/views/courses/_about_schools.html.erb
- app/views/courses/show.html.erb
- spec/features/courses/show_spec.rb
We're adding back in the locations table for courses with multiple sites. It now should be in the where you will train section instead of the Apply section
- Add back in the locations table for course with multiple sites and vacancies available
This sits behind the ucas_only_locations feature flag, as when that is switched on the locations render in the Apply section as before.
We should remove that flag.
> Add the location table back in for courses with multiple locations

- config/environments/production.rb
see https://ukgovernmentdfe.slack.com/archives/CL1ETJHLN/p1619961403012900
Currently logs are being logged to STDOUT and also to {env}.log
Disable file logging in prod
> Don't log to file in production

- app/views/courses/_about_schools.html.erb
- spec/features/courses/show_spec.rb
Some of Beds SCITTs courses program_types are `HEI`. As a result, they're getting incorrect content rendered.
They've contacted us directly to complain about this so we're going to remove the content for now.
We\re going to have to do a data audit at some point too!
- Don't show the HEI guidance for courses with a provider code of 'B31'
> Don't show the default  HEI guidance for Beds SCITT

- app/views/courses/_about_schools.html.erb
- spec/features/courses/show_spec.rb
This provider does not actually find placements for candidates so the guidance is misleading. They've asked us to remove it.
https://www.find-postgraduate-teacher-training.service.gov.uk/results?l=3&query=Educate+Teacher+Training
- Don't show where you will train default scitt content for Educate Teacher Training
> Remove where you will train guidance from Educate Teacher Training

- app/webpacker/scripts/filter-toggle-button.js
_This PR addresses a filter issue on IPhone SE - see https://github.com/DFE-Digital/find-teacher-training-prototype/pull/26_
`addListener` has been deprecated in favour of `addEventListener`, as used in the MOJ frontend version of this component: https://github.com/ministryofjustice/moj-frontend/blob/master/src/moj/components/filter-toggle-button/filter-toggle-button.js#L14
This is because `addEventListener` is only supported in Safari for `MediaQueryList` objects from version 14 onwards: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener – and old iPhones are unable to upgrade to this.
`addListener` seems to have been maintained by browsers for backwards-compatibility, at least for now.
A better longer-term fix might be to feature-detect support for …
> Revert to using addListener

- app/view_objects/results_view.rb
- spec/view_objects/results_view_spec.rb
At the moment, we only filter by whether a sites site status is new or running before calculating things like the nearest site and how many sites are available.
We should also be filtering out sites with no vacancies.
- Only use sites with vacancies for site related info on the results page 
Locations for course
|Before|After|
|------------|-----------|
|![image](https://user-images.githubusercontent.com/42515961/117961905-8c558780-b316-11eb-8b20-15f22a13b1bc.png) |![image](https://user-images.githubusercontent.com/42515961/117961451-0c2f2200-b316-11eb-99e8-aeb76fb8c05d.png)|
I checked with Paul and he agrees with the general approach. Am i missing anything?
https://trello.com/c/1tPhJM0Z/3391-bug-find-locations-returned-incorrectly-searching-by-town-name-but-not-by-postcode
> Only use sites with vacancies for info on results page

- .github/workflows/build.yml
Dependabot PRs don't have access to pipeline secrets.
Don't access secrets when running dependabot PR checks.
> Don't push to DockerHub for dependabot PRs

- app/views/courses/show.html.erb
- spec/features/courses/show_spec.rb
- spec/site_prism/page_objects/page/course.rb
Some providers offer the same course but for different age groups. They input this information on Publish but it is not surfaced on Find automatically. This means that the courses look identical on Find to candidates.
Added the age range metadata to the summary list, on the course details page:
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/47917431/118519567-25c6d400-b731-11eb-9358-d6e025b0b16c.png)|![image](https://user-images.githubusercontent.com/47917431/118780085-9a118c80-b883-11eb-95e8-38f5a998077d.png)|
https://trello.com/c/7GGhiNZp/3387-find-surface-age-range-metadata-from-publish
> Display age range on the course details page

- app/views/layouts/application.html.erb
On Sandbox, show a Sandbox phase banner in the header
> Show a Sandbox phase banner on Sandbox

- app/helpers/view_helper.rb
- app/views/courses/_about_schools.html.erb
- app/views/courses/show.html.erb
- app/views/layouts/application.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/components/_header.scss
Find is increasingly including support for different environments. We should adapt the header as we do on other BAT services so that it’s clear which environment is being shown.
* Updates the header (colour of border, phase tag and phase label) for `development`, `sandbox` and `production` environments
* Updates `bat_contact_mail_to` helper so that can accept `class` and other params available to set on the underlying Rails `mail_to` helper
> Adapt header based on environment

- app/views/courses/_apply.html.erb
Since we decided to always show locations in this section, it is no longer the case that this section shows the button alone. This means we should add a section heading, to differentiate it from the section above.
| - | - |
| <img width="680" alt="Screenshot 2021-06-28 at 13 22 39" src="https://user-images.githubusercontent.com/813383/123636961-59f3e100-d815-11eb-8a24-0f5216f637f7.png"> | <img width="680" alt="Screenshot 2021-06-28 at 13 31 37" src="https://user-images.githubusercontent.com/813383/123636969-5c563b00-d815-11eb-9392-6da3acf1e241.png"> |
| <img width="670" alt="Screenshot 2021-06-28 at 13 23 10" src="https://user-images.githubusercontent.com/813383/123636966-5b250e00-d815-11eb-8558-980fa99b2983.png"> | <img width="680" alt="Screenshot 2021-06-28 at 13 30 …
> Add a heading for Apply section on course pages

- Gemfile
- Gemfile.lock
- app/job/send_event_to_big_query_job.rb
- app/lib/events/web_request.rb
- config/event-schema.json
- config/initializers/big_query.rb
- config/settings.yml
- config/settings/test.yml
- spec/controllers/concerns/emit_request_events_spec.rb
- spec/features/events/send_web_request_to_big_query_spec.rb
- spec/jobs/send_event_to_big_query_job_spec.rb
- spec/lib/events/web_request_spec.rb
- spec/support/big_query_test_helper.rb
- spec/support/json_schema_validator.rb
- update the JSON schema for events sent to BigQuery
- add JSON schema validation
- add setting for BigQuery table name
Changes tested locally. Also this feature hasn't been enabled in any environments so zero impact to this particular changeset.
As the BigQuery event logging hasn't been enabled yet, I've decided to re-use the old Trello ticket number (3512) even though that ticket has been considered "Done".
https://trello.com/c/Fx0UPepe/3512-%F0%9F%8F%88-find-send-page-request-events-to-bigquery
> [3512] update web_request event format

- config/settings/production.yml
- config/settings/qa.yml
- config/settings/staging.yml
in the envs: qa, staging and production
These are currently enabled in the secrets, which isn't the right place to do that.
Move the setting for this feature to the repo, which will allow us to remove it from secrets.
> enable feature send_web_requests_to_big_query

- app/services/cycle_timetable.rb
- spec/services/cycle_timetable_spec.rb
Going forward we want to use a CycleTimetable to control the changes in behaviour in discreet phases of the cycle on Find such as the banners, removing the apply button and restricting access to courses when Find is closed.
This PR adds the CycleTimetable.
Going forward this will be used to implement all 4 cards captured in this epic https://trello.com/c/SZRVll8g/2302-%F0%9F%94%81-eoc-dev-find-changes-required-following-design-review
- Add the cycle timetable 
This needs the following values 
1. find opens
2. apply opens (for content on the banner)
3. deadline banner shows
4. apply 1 deadline 
5. apply 2 deadline
6. find_closes
Does this all make sense? I think you'd probs eed to have a look at the banner cards for context.
https://trello.com/c/3MhlVfCk/3591-%F0%9F%94%81-find-eoc-dev-phase …
> Add an EOC timetable to Find

- app/lib/events/web_request.rb
- config/event-schema.json
- spec/features/events/send_web_request_to_big_query_spec.rb
- spec/lib/events/web_request_spec.rb
We want to have a general sense of the number of unique users in BigQuery events.
Generate `anonymised_user_agent_and_ip` and send to BigQuery.
See Trello cards for further info.
https://trello.com/c/hBfnkeMI/3626-add-user-anonymous-identifier-field-to-event-being-sent-to-bq
> [3626] add anonymised user agent and ip to events

- app/views/layouts/application.html.erb
- spec/features/result_filters/location_and_provider_spec.rb
When a candidate arrives on find, a start wizard is passed into the flash. This is used to retain state on whether a candidate is moving through the initial flow, or whether they are editing a previous selection. 
We need to fix this, but it will take a while so for now, i've remove the start_wizard from the flash before passing it into the deadline banner component. 
- Render the deadline banner if the only flash is the start_wizard
As i've said above, this is a temporary fix. We should rework the way the wizard works. Unfortunately it's not as easy as just passing the params in as they views are completely shared. We can definitely take logic out the partials etc. but it's going to take a bit of time.
> Apply fix for banner not rendering due to start wizard

- app/components/deadline_banner_component.html.erb
- app/services/cycle_timetable.rb
- app/views/pages/cycle_has_ended.html.erb
As part of the changes we're making to Find for EOC, we need to update the content on the cycle has ended page.
This should be done using the CycleTimetable so it is future proof and does not need to be hardcoded.
Update the content on the cycle has ended page
https://trello.com/c/mloDU6fr/3593-%F0%9F%94%81-find-eoc-phase-4-find-is-closed-page-including-content-changes-from-last-year
> Update the content on the cycle has ended page

- app/components/deadline_banner_component.html.erb
- app/components/deadline_banner_component.rb
- app/views/pages/cycle_has_ended.html.erb
- config/initializers/date_formats.rb
We're using quite a bit of strftime throughout the deadline banner component and EOC related views. It would be much nicer to use something similar to apply which allows us to create custom time/date formats based around need.
- Implement a similar date format intialiser to apply
- use it where appropriate
> Add date format initialiser

- app/services/cycle_timetable.rb
- config/application.rb
- spec/features/events/send_web_request_to_big_query_spec.rb
- spec/lib/events/web_request_spec.rb
At the moment, the CycleTimetable is an hour out of date as the zone has not been set to London.
This PR sets Time.zone to London in the application file and sets the timetable to use Time.zone.local
Does this approach seem reasonable?
https://trello.com/c/IxL0GXY0/3634-find-cycletimetable-times-are-an-hour-out-due-to-time-zone
> Default Time to London and update the timetable to use Time.zone.local

- app/models/course.rb
- spec/components/courses/entry_requirements_component_spec.rb
UCL require a 5+ for courses they run/accredit. At the moment we only check if the provider is UCL, not the accredited provider.
https://trello.com/c/jYTgdnjE/3778-fix-issue-with-courses-ucl-accredit-not-showing-5-for-gcses
- Update the `EntryRequirementsComponent` to check whether the accrediting provider is UCL before rendering the required GCSE grade
> Update content for courses accredited by UCL

- Gemfile
- Gemfile.lock
- app/components/summary_list_component.html.erb
- app/components/summary_list_component.rb
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/switcher_controller.rb
- app/forms/change_cycle_form.rb
- app/lib/hosting_environment.rb
- app/lib/redis.rb
- app/models/recruitment_cycle.rb
- app/models/site_setting.rb
- app/services/cycle_timetable.rb
- app/views/switcher/cycles.html.erb
- config/initializers/sanitise.rb
- config/locales/en.yml
- config/routes.rb
- config/settings/development.yml
- config/settings/test.yml
- spec/components/summary_list_component_spec.rb
- spec/features/cycle_switcher_spec.rb
- spec/requests/end_of_cycle_spec.rb
- spec/services/cycle_timetable_spec.rb
- spec/spec_helper.rb
We're no longer using feature flags to move between phases of the cycle on Find to test EoC behaviour & content.
Apply has a switcher which allows you to move between the discreet phases of the cycle – this is to port the behaviour over to Find.
Adds a cycle switcher under the `/cycles` endpoint:
This will jump Find forward/back to different points in the cycle. It can only be used in a non-prod environment.
Similar to the logic on Apply
Using `http://localhost:3002/cycles` locally you can now switch between the different phases and then view the changes.
https://trello.com/c/K8cXWM7N
> Add a cycle switcher to Find

- app/components/courses/entry_requirements_component.html.erb
- app/components/courses/entry_requirements_component.rb
- app/components/courses/international_students_component.html.erb
- app/components/courses/international_students_component.rb
- spec/components/courses/entry_requirements_component_spec.rb
- spec/components/courses/international_students_component_spec.rb
- spec/features/courses/show_spec.rb
After product review, there are some required changes to the `International students` and `Entry requirements` sections of the course page.
1. use positive contractions in the international students component 
2. add copy around the required degree grade i.e. `2:1 or above, or equivalent` => `An undergraduate degree at class 2:1 or above, or equivalent`
3. update copy for equivalencies and pending GCSEs
https://trello.com/c/eHkPZRRx/3787-update-content-on-find-publish-for-structured-quals
> Update the content in the entry requirements section of the course page

- app/controllers/switcher_controller.rb
Original cycle switcher PR [#866](https://github.com/DFE-Digital/find-teacher-training/pull/866) is currently unable to deploy to production due to:
```
2021-08-16T12:46:47.90+0100 [APP/PROC/WEB/0] ERR /app/app/controllers/switcher_controller.rb:3:in `<class:SwitcherController>': undefined local variable or method `root_path' for SwitcherController:Class (NameError)
```
`root_path` is used elsewhere in the codebase but is normally within a private method, this PR will follow that pattern to see if it resolves the issue.
> Move root redirect before action into a private method

- app/views/courses/_advice.html.erb
- config/locales/en.yml
We need to add a new links to the Get into teaching site on the Find course page.
- Is the copy correct and does the link work?
https://trello.com/c/EC0lo4u6/3728-add-git-links-to-apply-find
> Add GiT link to the course page

- app/services/cycle_timetable.rb
- app/views/pages/cycle_has_ended.html.erb
- config/locales/en.yml
- spec/features/cycle_switcher_spec.rb
- spec/services/cycle_timetable_spec.rb
This PR introduces a content change on the 'cycle has ended' page to encourage people to start an application despite Find being unavailable. 
Change content on the cycle has ended page to:
- Is the content and link correct?
- Are the dates correct?
https://trello.com/c/FgUEV9Nv/3852-eoc-con-dev-users-can-start-applying-when-find-is-closed
> Update content on the cycle has ended page

- app/components/deadline_banner_component.html.erb
- spec/components/deadline_banner_component_spec.rb
- spec/features/cycle_switcher_spec.rb
We want to edit the content so that users are encouraged to create an account and start applying anyway once the apply deadline has closed.
https://trello.com/c/16nEVOp9/3857-dev-edit-eoc-banner-the-one-when-apply-1-has-passed-to-give-link-to-apply-sign
> Edit 'Apply 1' deadline banner

- app/services/cycle_timetable.rb
- spec/requests/end_of_cycle_spec.rb
- spec/services/cycle_timetable_spec.rb
Find closes at the end of the day (11:59pm) on 4th October in the 2021 cycle
Make it so.
It should just work ™️ 
https://trello.com/c/y2CZ1eMw/3856-eoc-dev-update-find-closed-date-in-timeline-across-find-apply
> Update 'Find closes' calendar event

- app/components/deadline_banner_component.html.erb
- app/components/deadline_banner_component.rb
- app/views/pages/cycle_has_ended.html.erb
- spec/features/cycle_switcher_spec.rb
[Reinstating earlier changes](https://github.com/DFE-Digital/find-teacher-training/pull/890) but this time editing the correct banner 😄 
Have also updated specs for clarity 
Apply 2 deadline now appears as follows
https://trello.com/c/16nEVOp9/3857-dev-edit-eoc-banner-the-one-when-apply-1-has-passed-to-give-link-to-apply-sign
> Update Apply 2 Deadline Banner

- app/views/courses/show.html.erb
New content encourages candidates to begin preparing to apply even while Find is closed
https://trello.com/c/Nrv8otUv/3846-eoc-con-dev-users-can-still-start-applying-when-applications-are-closed
> Update content on the course show page

- Gemfile
- Gemfile.lock
- Procfile
- config/application.rb
- config/sidekiq.yml
We use in-memory queues for async jobs at the moment, which are ephemeral. Sidekiq uses Redis, which is permanent and therefore more reliable.
Install Sidekiq and use it as the default queue adapter.
> Use sidekiq for async jobs

- app/components/deadline_banner_component.html.erb
- spec/components/deadline_banner_component_spec.rb
- spec/features/courses/show_spec.rb
- spec/features/cycle_switcher_spec.rb
- spec/features/result_filters/location_and_provider_spec.rb
Change content of the apply 2 deadline banner to encourage candidates to begin their application before
find and apply reopen.
- Is the copy correct?
- Do the spec changes make sense?
https://trello.com/c/x0NPUz9I/3858-dev-edit-eoc-banner-the-one-when-apply-2-has-passed-to-include-link-to-sign-in
> Update apply 2 deadline banner for EOC

- app/views/results/_no_results.html.erb
- spec/views/results/no_results_spec.rb
The links on Find that refer to teaching training are linking to the wrong site.
Correct link is: https://educators.wales/teachers
per slack discussion: https://ukgovernmentdfe.slack.com/archives/CP18YJXPY/p1630399478078300
> update link to TT in Wales

- Gemfile
- app/components/location_subject_filter_component.html.erb
Need to update smoke tests due to [#909](https://github.com/DFE-Digital/find-teacher-training/pull/909) but without an id in the new filter line it's hard to pinpoint due to the number of paragraph classes on the page.
Added an id to the filter line
> Add id to the new subject/provider filter line

- app/controllers/courses_controller.rb
- app/controllers/result_filters/provider_controller.rb
- app/controllers/sitemaps_controller.rb
- app/controllers/switcher_controller.rb
- app/models/recruitment_cycle.rb
- app/models/site_setting.rb
- app/view_objects/results_view.rb
- config/brakeman.ignore
- config/locales/en.yml
- config/settings.yml
- spec/controllers/courses_controller_spec.rb
- spec/decorators/course_decorator_spec.rb
- spec/factories/recruitment_cycles.rb
- spec/factories/sites.rb
- spec/features/courses/show_spec.rb
- spec/features/result_filters/location_and_provider_spec.rb
- spec/requests/cycles_spec.rb
- spec/requests/sitemaps_spec.rb
- spec/support/helpers.rb
- spec/support/stubbed_requests/courses.rb
- spec/support/stubbed_requests/providers.rb
We have been adding new search filters to Find but these rely on data that is only available in courses from the next recruitment cycle.
- When the CycleSwitcher is updated to `find_reopens` the TTAPI now returns courses from the next recruitment cycle.
- Update codebase to obtain the 'current_year' from the CycleTimetable class, rather than Settings
- Go to `/cycles` and switch to `find_has_reopened`
- Run a search - you should now see courses from the next recruitment cycle
https://trello.com/c/PmNodHKW/3911-cycleswitcher-add-ability-to-query-next-years-recruitment-cycle-data
> Return next cycle's courses when changing CycleSwitcher to 'find_reopens'

- Gemfile
- Gemfile.lock
- app/components/deadline_banner_component.html.erb
- app/components/summary_list_component.html.erb
- app/components/summary_list_component.rb
- app/helpers/view_helper.rb
- app/views/courses/_apply_button.html.erb
- app/views/courses/_no_vacancies_warning.html.erb
- app/views/courses/qualification/_pgce.html.erb
- app/views/courses/qualification/_pgce_with_qts.html.erb
- app/views/courses/qualification/_pgde.html.erb
- app/views/courses/qualification/_pgde_with_qts.html.erb
- app/views/courses/qualification/_qts.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_prev_page.html.erb
- app/views/layouts/application.html.erb
- app/views/result_filters/provider/new.html.erb
- app/views/result_filters/subject/_form.html.erb
- app/views/results/_university.html.erb
- app/views/results/index.html.erb
- app/webpacker/scripts/cookie-banner.js
- app/webpacker/scripts/cookie-banner.spec.js
- spec/components/summary_list_component_spec.rb
- spec/features/cookie_banner_spec.rb
A new version of [`govuk-components`](https://github.com/DFE-Digital/govuk-components) has been released. It contains a number of breaking changes, so this PR addresses any issues caused by moving to the new version.
* Update Gemfile to point to v2.0.1
* Fix issues arising from breaking changes in the components used by this app
* The cookie banner component is now one component that takes multiple messages; updated the JavaScript (and related tests) to reflect this change. 
Might want to pay particular attention to the changes around the cookie banner component.
FYI @peteryates
> Update govuk-components to v2

- app/view_objects/result_filters/filters_view.rb
- app/view_objects/results_view.rb
- app/views/result_filters/_all.html.erb
- app/views/result_filters/_visa_filter.html.erb
- config/settings.yml
- config/settings/qa.yml
- config/settings/review.yml
- config/settings/test.yml
- spec/features/result_filters/visa_spec.rb
- spec/site_prism/page_objects/page/results.rb
- spec/view_objects/result_filters/filters_view_spec.rb
```
As an... international user of Find
I need to... find courses that can sponsor my visa
So that... I don’t end up making an unsuccessful application
```
- Add 'visa sponsorship' filter to results page, hidden behind feature flag
- [ In the review app](https://find-pr-935.london.cloudapps.digital/results?l=2&subjects%5B%5D=31&subjects%5B%5D=32&subjects%5B%5D=55&subjects%5B%5D=35&subjects%5B%5D=36&subjects%5B%5D=37&subjects%5B%5D=38), update the CycleSwitcher `/cycles` to 'find has reopened' - this will enable you to view 2022 cycle courses
- run a standard search but make sure you choose lots of subjects otherwise you may not get any results once you filter by 'visa sponsorship'
https://trello.com/c/r6Bwj28v/3794-%F0%9F%93%90-dev-find-add-visa-sponsorship-search-filter
> Add visa sponsorship filter to results page

- app/webpacker/scripts/autocomplete.js
The provider search autocomplete makes XHR requests as the user types.
Increasing the throttle wait value from 500 to 2000 results in fewer
requests without impacting usability.
Increase wait value in `throttle` function from 500 to 2000ms.
Can be tested by running this branch locally and viewing network requests in your browser tools as you type in the autocomplete. Can be compared with current master or QA. Should be fewer requests at anything but the slowest of typing speeds.
https://trello.com/c/XecYnOwt
> Increase the throttle on provider autocomplete

- config/initializers/raven.rb
This error makes noise in the Slack channel. We can’t do anything about it, and the client correctly sees a 404 anyway.
> Ignore unactionable error in Sentry

- app/controllers/results_controller.rb
The search results page on Find is slow, high traffic, and changes infrequently. A typical workflow probably involves a lot of back and forth between the results page and individual courses. 
Add client side caching to reduce the number of server calls to Find (and TTAPI), while still providing reasonably up to date information.
- Note that this only appears to work on Firefox. Safari and Chrome appear to ignore the returned cache header and will only cache sub resources, not the main resource. See https://stackoverflow.com/questions/11245767/is-chrome-ignoring-cache-control-max-age
- To test locally, start Firefox, disable the Rack mini profiler (via the initialiser) and run a search e.g. `http://localhost:3002/results?l=2&subjects[]=31&subjects[]=32&subjects[]=55` a few times. 
- You …
> Add client side caching to search results

- app/views/result_filters/_degree_required_filter.html.erb
- spec/features/result_filters/required_degree_spec.rb
The previous labels caused confusion in research, with participants confused by the difference between "Show all courses" and "Only show courses that accept any degree grade"
So far the new, more succinct labelling has tested ok.
> Update degree require radio labels

- config/environments/production.rb
- config/initializers/assets_cache_headers.rb
- config/settings/production.yml
- config/settings/qa.yml
- config/settings/sandbox.yml
- config/settings/staging.yml
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
At present the static assets are being served directly from the rails app server.
We can reduce the number of requests served by the app by serving assets from a different cdn-route instance.
Set RAILS_ASSETS_HOST for different envs in KeyVault secrets
Terraform config for binding assets domain to web app
Set `asset_host` rails property to the assets domain
> Configure assets domain for serving static assets

- config/routes.rb
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
No longer required to support www2 sub-domain
Remove www2 redirect
> Remove www2 sub-domain

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/services/location_suggestion.rb
- config/initializers/sentry.rb
- spec/controllers/application_controller_spec.rb
- spec/services/location_suggestion_spec.rb
The sentry-raven library is deprecated. We need to move to the new version, sentry-ruby.
Replace Raven gem with Sentry
Replace raven methods with sentry methods
https://docs.sentry.io/platforms/ruby/migration/
Correct?
> Migrate to sentry-ruby

- app/views/courses/_no_vacancies_warning.html.erb
- app/views/result_filters/_send_filter.html.erb
- app/views/result_filters/_visa_filter.html.erb
- app/views/result_filters/subject/_form.html.erb
- app/views/results/_funding.html.erb
The copy is wrong on these filters. They should read `Only show x courses`. 
- Update the copy to be inline with other filters
> Update copy on the visa and SEND filter

- app/components/maintenance_banner_component.html.erb
- app/components/maintenance_banner_component.rb
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/pages/maintainance.html.erb
- config/routes.rb
- config/settings.yml
- spec/components/maintenance_banner_component_spec.rb
- spec/features/maintainance_page_spec.rb
- spec/features/maintenance_banner_spec.rb
We're going to have to bring Find down for a set period of time while we upgrade the TTAPI DB. There may well be a few minutes where we're unable to hit the TTAPI so we're going to pop the service into maintenance mode for 30 mins.
- Add maintenance_mode feature flag
- Add a maintenance mode page 
- Redirect to the page when the flag is active
Does this seem about right time wise? Not sure how long the db upgrade will take. Could make it an hour to be safe?
This will have to be manually deployed before we swap the DBs. Is that an issue?
Add banner 
🤢
https://trello.com/c/WPcZ8odw/3970-add-maintenance-page-for-find-for-when-the-ttapi-is-down
> Add maintenance page and flag for when find is down

- app/controllers/result_filters/subject_controller.rb
- app/controllers/results_controller.rb
- app/helpers/csharp_rails_subject_conversion_helper.rb
- app/helpers/result_filters/subject_helper.rb
- app/view_objects/results_view.rb
- app/views/result_filters/subject/_form.html.erb
- spec/features/result_filters/location_and_provider_spec.rb
- spec/features/result_filters/subjects_spec.rb
- spec/features/results_spec.rb
- spec/helpers/result_filters/subject_helper_spec.rb
- spec/view_objects/results_view_spec.rb
The subject filters in Find populate the query string with subject codes. These subject codes are the so-called Csharp subject codes, dating from when Find was a C# app before it was rewritten in Rails.
We would like to remove the Csharp codes and replace them with so-called Rails (ie TTAPI-standard) codes so that every service is using the same codes. Apart from being the right thing to do, this also simplifies our reporting and simplifies Find itself.
**However**, we do need to continue to support the old subject codes, because we want to continue to support users who have bookmarked search result pages. (A quick investigation with @misaka found a few hundred requests lacking `Referer`s a month).
- Change Find subject filters to use the same subject codes as TTAPI does (it doesn't rn)
- …
> Update subject params to use rails subject codes

- app/components/maintenance_banner_component.rb
- spec/features/maintainance_page_spec.rb
Ensure maintenance banner does not render on the maintenance page
- Do not render the maintenance banner if the maintenance_mode feature flag is on.
> Do not show maintenance banner on maintenance page

- app/controllers/results_controller.rb
- app/models/course.rb
- config/environments/test.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/qa.yml
- config/settings/test.yml
- spec/features/courses/results_spec.rb
- spec/spec_helper.rb
We can't cache course details for any significant length of time in
Find, because there's a requirement for Providers to be able to quickly
update course details and issue corrections. However, we probably should
cache these API calls anyway during the opening week of the cycle, to
help the service handle the expected level of load.
Do this via the following:
- Add a feature flag for this caching behaviour
- Use Faraday middleware to write to a cache when making requests in the
Course resource
- Give cache entries written here a 10 minute expiry
- Make the Course connection use a valid cache object if the feature
flag is on, otherwise use a null cache
This will serve requests for the same url, within the expiry, from the
cache.
Alongside these changes, we configure as follows:
- Clear the …
> Add temporary caching of course API requests

- app/models/subject.rb
- app/models/subject_area.rb
We want to speed up Find.
Subjects and subject areas don't change very often, but are requested often from TTAPI during a typical workflow through Find. We can cache these calls.
Cache the API calls for Subject and SubjectArea for an hour.
> Cache subject API calls

- app/lib/redis.rb
- app/models/site_setting.rb
Redis.new was being used to get/set SiteSettings
use Redis.current instead
> Use existing redis connection for checking SiteSettings

- app/controllers/switcher_controller.rb
- app/services/cycle_timetable.rb
This is disabled for Prod so it should also be for our load testing env.
- Disable the cycle switcher in the load testing env
https://trello.com/c/YW5sKe0d/4002-dont-use-redis-on-prod-load-testing-in-find
> Disable cycle switcher on Find for the load test environment

- Gemfile
- config/initializers/big_query.rb
- config/initializers/semantic_logger.rb
JSON logs are for computers, not people.
Only run SemanticLogger in the `production` bundle.
Fix a deprecation warning. (We should move ourselves off the Rails `5.2` defaults (!) at some point)
> Don’t use SemanticLogger in local dev

- Gemfile
Find is neither developed (right now) nor deployed on Windows. Drop this gem, which is never installed.
> Drop Windows timezone support

- app/job/send_event_to_big_query_job.rb
Logit is expensive and most of the logs are because of the BigQuery job. They don't add any value since we use BigQuery as an event log anyway.
Turn off logging for the BigQuery job. Same as teaching vacancies: https://github.com/DFE-Digital/teaching-vacancies/pull/3986/files
Check the BigQuery job doesn't emit any log
https://trello.com/c/7uDtQqB3
> [2261] Stop logging Bigquery job

- Gemfile
- Gemfile.lock
- app/controllers/heartbeat_controller.rb
- app/models/base.rb
- app/services/location_suggestion.rb
Calls to the Google API are quite slow, according to mini profiler:
We can improve this by using persistent HTTP connections: 
- Remove HTTParty gem
- Add persistent http gem
- Use Faraday for connecting to Google API, with net_http_persistent as the adaptor
- Use a simlar approach for making all API calls to TTAPI
> Use net_http_persistent for better performance when making API calls

- config/initializers/sidekiq.rb
We removed logs from inside the BigQuery job but Sidekiq itself logs start and stop events.
Set Sidekiq log level to WARN
Check sidekiq logs
https://trello.com/c/7uDtQqB3/2261-stop-logging-bigquery
> [2261] Set Sidekiq log level to WARN

- app/controllers/result_filters/subject_controller.rb
- app/controllers/results_controller.rb
- app/helpers/csharp_rails_subject_conversion_helper.rb
- app/helpers/result_filters/subject_helper.rb
- app/middleware/csharp_subject_conversion_middleware.rb
- app/view_objects/results_view.rb
- config/application.rb
- config/environments/test.rb
- spec/features/result_filters/subjects_spec.rb
- spec/features/results_spec.rb
When we mapped `subjects[]` to `subject_codes[]` we didn't go on to send the new `subject_codes[]` to BigQuery. This meant that we lost the canonical subject codes for these requests. 
We also did the mapping in two places, in the Results and Subjects controllers, and the mapping in the Subjects controller didn't work.
Map once and finally in middleware so all controllers can benefit, and make sure the query string is updated so we send the `subject_codes[]` on to BigQuery. Remove some unused methods.
> Send subject_code to BigQuery once it's been mapped from C#

- app/views/result_filters/location/_form.html.erb
- app/webpacker/scripts/autocomplete.js
- config/settings.yml
- spec/requests/start_spec.rb
The provider autocomplete on the start page sends requests to TTAPI as
the user types. This gets a bit heavy-going when traffic spikes at start
of cycle.
We're planning on reimplementing it so it uses a locally-stored
providers list for its suggestions. Until that's done, we want to be
able to switch the autocomplete off during peak load.
Wrap the container div for the autocomplete in a feature flag check
Return early from the autocomplete js if this div isn't found on the page
- Can be tested locally by toggling the value of the feature flag and typing a provider name into the third input on the start page
https://trello.com/c/B3FlzE6Z
> Feature flag provider autocomplete

- app/services/location_suggestion.rb
- app/webpacker/scripts/autocomplete.js
- spec/services/location_suggestion_spec.rb
The [location suggestions endpoint](https://www.skylight.io/app/applications/fjR4NhKjEKlK/recent/6h/endpoints/LocationSuggestionsController%23index?responseType=json) gets hit at fairly high volumes as a user types a city, town or post code on the start page. Temporarily caching the results of the endpoint may help improve performance and avoid repeatedly sending the same input queries to the Google API in a short space of time.
- Use debounce instead of throttle in the autocomplete, to improve the quality of search queries sent to the server
- Cache valid results with an expiry, ignoring errors from the Google API
Can be tested locally by navigating to the start page and searching by city, town or post code.
Edit -
Via @duncanjbrown, a demo of the difference between throttle and debounce …
> Cache location suggestions

- app/views/courses/qualification/_qts.html.erb
The QTS-only details component contained some content written pre-Brexit.
This brings it inline with the other qualification statuses in advising candidates to check qualification requirements for overseas teaching.
> Update QTS-only description to reflect UK leaving the EU

- app/views/courses/qualification/_pgce.html.erb
- app/views/courses/qualification/_pgce_with_qts.html.erb
- app/views/courses/qualification/_pgde.html.erb
- app/views/courses/qualification/_pgde_with_qts.html.erb
- app/views/courses/qualification/_qts.html.erb
There's no need to use `&rquo;` when we can encode the `’` character directly, which also makes the source code easier to read.
> Avoid HTML entities for apostrophe character

- app/components/courses/search_result_component.html.erb
- app/views/courses/financial_support/_bursary.html.erb
- app/views/courses/financial_support/_scholarship_and_bursary.html.erb
- app/views/result_filters/subject/_form.html.erb
- config/settings.yml
- config/settings/test.yml
- spec/features/courses/results_spec.rb
- spec/features/result_filters/subjects_spec.rb
We don't have information regarding bursaries of scholarships at the moment. We also need to pull the SKE related stuff out as we're not sure which will have it.
- Put all of the bursary/scholarship/SKE content behind a flag 
- Subject page content
|Before|After|
|-----------|-----------|
|![image](https://user-images.githubusercontent.com/42515961/135849519-75abccf8-b74d-44c2-bfef-08f1fddc4e59.png)|![image](https://user-images.githubusercontent.com/42515961/135849423-dd78476b-fcf1-4f70-aabf-c17d204b48e5.png)|
- Subject page filters
|Before|After|
|-----------|-----------|
|![image](https://user-images.githubusercontent.com/42515961/135849936-467361b9-35a8-4c19-a28d-3242e85f203e.png)|![image](https://user-images.githubusercontent.com/42515961/135850079-cf14f92f-7f75-4691-b021-06c46c8cccf8. …
> Remove bursary and scholarship information and add placeholder guidance

- app/views/result_filters/_hidden_fields.html.erb
- spec/features/result_filters/send_spec.rb
Fix issue with subjects not being retained when filters are applied
- Update the hidden fields to use the new subject_codes field rather than the deprecated params
https://trello.com/c/8sXFu9UP/4014-find-send-filter-bug
> Fix bug with subjects in filters

- app/components/courses/search_result_component.html.erb
- app/decorators/course_decorator.rb
- spec/decorators/course_decorator_spec.rb
- spec/features/courses/results_spec.rb
Currently this is hidden if the bursaries_and_scholarships_announced
feature flag is off. 
Change it so that we at least show either "Salary"
or "Student finance if you're eligible".
na
> Amend how we display financial support info

- app/components/courses/search_result_component.html.erb
- spec/features/courses/results_spec.rb
- spec/features/result_filters/location_and_provider_spec.rb
A [support ticket](https://trello.com/c/pZatjybt/859-find-page-not-showing-location) was raised by a provider on how we render the location information on Find, when a candidate searches with 'Across England'.
We're currently rendering the providers address, rather than the site address. As an interim fix we will no longer render the location row, unless the candidate does a locations search.
If a candidate searches 'Across England' or 'By provider' then don't render the locations row.
This is only an interim fix until we can come up with a reliable solution.
https://trello.com/c/pZatjybt/859-find-page-not-showing-location
> Don't render the location row on a non location search

- app/controllers/switcher_controller.rb
- app/services/cycle_timetable.rb
We have taken down the `load-test` and `loadtest` environments. All terraform configuration for `loadtest` seems to live in a branch, but there are some references in the main application.
Remove references to `loadtest`.
Should be easy.
https://trello.com/c/3l4dR0wC/4429-destroy-load-test-environment
> Remove load-test references from master

- app/views/courses/financial_support/_bursary.html.erb
- app/views/courses/financial_support/_loan.html.erb
- app/views/courses/financial_support/_scholarship_and_bursary.html.erb
At the moment we link to the wrong page for our financial advice for international students.
- Link to the correct gov.uk page
https://trello.com/c/tuYcG846/4108-dev-find-link-update
> Use the correct link to financial info for international students

- app/controllers/results_controller.rb
- spec/features/results_spec.rb
This was taken out in error at ac2464a6b
https://ukgovernmentdfe.slack.com/archives/CP18YJXPY/p1636553342237000?thread_ts=1636551466.234000&cid=CP18YJXPY
Reinstate the link and add a spec (tho specs will be revamped in due course)
> Reinstate feedback link on results page

- config/settings/production.yml
We're going to toggle this off to see if it fixes this bug https://ukgovernmentdfe.slack.com/archives/CP18YJXPY/p1637063118297700
- Switch cache_courses flag off
> Toggle course caching off on prod

- Gemfile
- Gemfile.lock
- app/controllers/feature_flags_controller.rb
- app/job/slack_notification_job.rb
- config/settings/production.yml
- config/settings/test.yml
- spec/features/feature_flags_spec.rb
- spec/jobs/slack_notification_job_spec.rb
Send slack notifications when feature flags are upated on `/feature-flags`. The channel the notification is sent to is dependent on the environment (see changes proposed). 
- Link slack text to `/feature-flags` page
- Add `http` gem
- Add `SlackNotificationJob` class
- Dynamic `webhook_url` based on the environment (Uses `Settings`)
- Post to `#twd_apply_tech` if production else post to `#twd_apply_test`
- Replace `Settings.STATE_CHANGE_SLACK_URL` in `app/job/slack_notification_job.rb` with the equivalent secret in `QA`. Feel free to ask me. 
- Fire up the app and navigate to `/feature-flags`
- Flip a few of the feature flags and admire the notifications on `#twd_apply_test`
- Ensure the secrets have been added correctly to Find production
> [4125] Add slack notification when feature flag updated

- app/components/hidden_fields_component.html.erb
- app/components/hidden_fields_component.rb
- app/components/search/primary_subject_selection_component.html.erb
- app/components/search/primary_subject_selection_component.rb
- app/components/search/secondary_subject_selection_component.html.erb
- app/components/search/secondary_subject_selection_component.rb
- app/controllers/result_filters/location_controller.rb
- app/controllers/search/age_groups_controller.rb
- app/controllers/search/subjects_controller.rb
- app/form_objects/search/age_groups_form.rb
- app/form_objects/search/subjects_form.rb
- app/lib/feature_flags.rb
- app/views/result_filters/subject/start.html.erb
- app/views/search/age_groups/new.html.erb
- app/views/search/subjects/new.html.erb
- config/locales/age_groups.yml
- config/locales/subjects.yml
- config/routes.rb
- spec/features/search/new_flow/across_england/further_education_spec.rb
- spec/features/search/new_flow/across_england/primary_spec.rb
- spec/features/search/new_flow/across_england/secondary_spec.rb
- spec/features/search/new_flow/editing_a_search_spec.rb
- spec/form_objects/search/age_groups_form_spec.rb
- spec/form_objects/search/subjects_form_spec.rb
Find currently asks users to select a subject using an Accordion which groups checkboxes by Primary, Secondary, Secondary: Modern languages, Further education and SEND.
Depending on what you select:
* Primary takes you to a page listing all the primary subjects - there is also some updated content on this page
* Secondary takes you to a list of all secondary subjects in alphabetical order
* Further Education takes you straight to results.
SEND is no longer asked as part of the initial flow, as this is included as a filter instead.
- Visit '/feature-flags' and turn on the 'new_search_flow' feature flag
- IMPORTANT - this new flow currently works for 'searching by location' / 'across England' only. New flow for 'searching by provider' will be done in a followup PR …
> [3928] - new search flow

- .github/workflows/smoke-test.yml
Remove slack channel notifications from smoke test or deploy failures for review environments.
[https://trello.com/c/i9GEROze/472-remove-notifications-from-smoke-test-or-deploy-failures-for-review-app](url)
in smoke-test.yml
line 58: if: failure()
change to
line 58: if: failure() && github.event.inputs.pr == ''
No notification step in deploy.yml, so no change required.
> Remove notifications from smoke test for review

- app/controllers/result_filters/provider_controller.rb
- spec/features/search/location_and_provider_spec.rb
- spec/features/search/new_flow/location_spec.rb
- spec/features/search/new_flow/provider_spec.rb
- spec/features/search/subjects_spec.rb
We have wired up searching by 'location' and 'across England' to the new search flow. We now need to do the same for searching by 'provider'. 
- Wire up provider search to the new flow
- Add fix so the the provider search value is rehydrated on the start page when clicking back 
- Visit '/feature-flags' and activate the 'new_search_flow' feature flag 
https://trello.com/c/coZ9yN3R/4209-primary-secondary-fe-flow-apply-to-provider-search-journey
> [4209] - Wire up provider search to the new flow

- .github/workflows/deploy.yml
The timeout was set to 15 minutes at the job level but this is often reached when multiple PRs are merged quickly.
We now use the same configuration as in the other services: set it to 30 minutes at the wait step level and only lock the workflow runs when on the same branch.
Same configuration as Register, etc
https://trello.com/c/GS44pWv6
> [487] Increase deploy workflow timeout

- config/locales/en.yml
The footer for find has the wrong opening hours for contact centre features. This amends it.
changing 5 -> 5.30
> Update opening hours

- terraform/workspace_variables/production.tfvars
- terraform/workspace_variables/qa.tfvars
- terraform/workspace_variables/sandbox.tfvars
- terraform/workspace_variables/staging.tfvars
Alerts are currently routed to BAT-DevOps-Slack-Prod (Slack & email) or BAT-DevOps-Slack-All (just email).
Alerts will be routed to Slack-Apply-Tech webhook instead of BAT-DevOps-Slack-Prod or just email.  Updated contact groups in workspace variable files for production, sandbox, staging and qa.  
Do the channels match the expected channels.
https://trello.com/c/q3F2WvuS
> Update StatusCake contact groups

- .tool-versions
- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- package.json
- yarn.lock
(Also move `yarn` into the `engines` section of the `package.json` as it's not a strict dependency.)
This brings the versions up to date with the same ones used in Apply.
> Upgrade node from 12 to 16 and ruby from 2.7.2 to 2.7.5

- app/controllers/feature_flags_controller.rb
- spec/features/feature_flags_spec.rb
The wording of the slack notification that fires when a feature flag is deactivated was inaccurate because it was hardcoded. This makes PR ensures `activated` or `deactivated` is rendered depending on which is happening.  
- Use the `action` instead of hard coding `activated`
- Replace `Settings.STATE_CHANGE_SLACK_URL` in `app/job/slack_notification_job.rb` with the equivalent secret in `QA`. Feel free to ask me. 
- Fire up the app and navigate to `/feature-flags`
- Flip a few of the feature flags and check the wording of the notifications on `#twd_apply_test` when activating and deactivating the flags.
> Fix feature flag wording when deactivated

- app/views/layouts/application.html.erb
Combine both telephone and online chat, as both are free and have the same opening hours.
This change was already made in the Apply for teacher training service.
> Simplify support links in footer

- app/form_objects/search/subjects_form.rb
- spec/features/search/new_flow/across_england/secondary_spec.rb
Since moving to the new search flow, 2 subjects have reappeared that [were previously ignored](https://github.com/DFE-Digital/find-teacher-training/blob/main/app/views/result_filters/subject/_form.html.erb#L37), "Modern Languages" and "Philosophy". These don't return any courses.
In addition, "Ancient Hebrew" has recently been added as subject but does not yet have any courses associated with it.
We can drop these 3 checkboxes for now.
In future we could look at a way of perhaps moving this logic into the teacher training API itself.
[Trello card](https://trello.com/c/KjU8xdRc/4309-remove-modern-languages-from-the-find-filter-options)
> Drop 3 of the subject checkboxes

- app/components/courses/financial_support/bursary_component.html.erb
- app/components/courses/financial_support/scholarship_and_bursary_component.html.erb
- app/views/courses/_advice.html.erb
- app/views/courses/financial_support/_bursary.html.erb
- app/views/courses/financial_support/_loan.html.erb
- app/views/courses/financial_support/_scholarship_and_bursary.html.erb
- app/views/result_filters/subject/_form.html.erb
- config/locales/en.yml
@EllieNodder @avinhurry and @EmmaFrith  reviewed links to the Get into teaching service, discovering some that have changed and others that have moved. This updates the links and improves the link text.
Additionally, all the URLs have been moved to the `en.yml` locale file, to make it easier for us to audit where we are linking to in future.
[Trello card](https://trello.com/c/Ihs4Ib6P/4318-edit-links-from-find-and-apply-to-git)
> Update links to Get into teaching

- app/views/courses/_advice.html.erb
We found a typo, this PR fixes it: 
https://trello.com/c/mW7JxuV2
> Fixing a typo in our copy talking about advisers

- .github/workflows/build-nocache.yml
- .github/workflows/build.yml
- Dockerfile
- docs/deployment.md
https://trello.com/c/UdUEnOJu/511-reload-docker-image-cache
Schedule a weekly refresh of the docker image cache, so that we pick up updates to the base images
New workflow for weekly docker image cache refresh
Add SNYK scan to build workflow
Bump GMP version as not yet in base image
Run workflow against branch
Run review app
> Add worklow to refresh docker cache weekly

- .github/workflows/build.yml
Dependabot does not have access to github secrets,
so its unable to connect to az and run the SNYK scan
Update build.yml to exclude dependabot from steps it shouldnt run
Check build workflow runs as expected
> Stop dependabot builds from running the SNYK scan

- app/components/courses/financial_support/scholarship_and_bursary_component.html.erb
we removed this sentence elsewhere because it's confusing. but we forgot this instance of it.
> confusing sentence that was removed elsewhere

- app/components/search/secondary_subject_selection_component.html.erb
This simplifies the heading structure of the page, reducing the duplication.
🗂️  [Trello card](https://trello.com/c/HQrIlDpQ/4385-heading-hint-text-and-label-all-repeat-one-another)
> Merge checkbox legend with the h1 for secondary subjects

- .github/workflows/build-nocache.yml
- .github/workflows/build.yml
- Makefile
- docker-compose.yml
- docs/deployment.md
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
Containers for this repo are currently published to Dockerhub.  Publishing images to GitHub container registry is simpler and more secure.
This commit migrates workflows from Dockerhub to the GitHub Container Packages registry.
- Confirm that image is being published as a GitHub Container Package
- Confirm that deployment is using the correct GitHub Container Package
https://trello.com/c/wVT0QcJ4
> Migrate to GitHub container registry

- app/components/courses/financial_support/bursary_component.html.erb
- app/components/courses/financial_support/bursary_component.rb
- spec/components/courses/financial_support/bursary_component_spec.rb
https://trello.com/c/ZPdtoydi/4382-dev-find-repeated-content-on-fees-and-financial-support-section
* New method which stops double rendering of same requirement in financial support section
* Unit test in component
Visit course with a bursary and verify that it does not render 'a degree of 2:2 or above in any subject' twice
> Add check to bursary component

- app/views/layouts/application.html.erb
This makes it clearer that the link will open an email client, which might otherwise be unexpected and annoying, for example if the link opens Outlook but you use Gmail.
Using the email address as link text makes it easier for users to copy and paste the email address into their preferred email app if needed.
> Use email address as link text for mailto

- .github/workflows/build.yml
Currently builds on dependabot raised PR fail if the deploy label is added because the GHCR login step is skipped.
Remove the condition on the GHCR login step.  This allow the image to be pushed by a later step if the deploy label is added to the PR.  
- In order to test this change a dependabot PR will need to be triggered with this change already in the main branch.  It's therefore not possible to test it fully prior to merging.  The documentation that this change is based on should be reviewed to check that it has been understood correctly - https://docs.github.com/en/actions/security-guides/automatic-token-authentication#how-the-permissions-are-calculated-for-a-workflow-job
> Allow dependabot triggered PRs to login into GHCR

- .github/actions/deploy/action.yml
- .github/workflows/build.yml
- .github/workflows/delete-review-app.yml
- .github/workflows/deploy.yml
The workflows that initiate a deployment use workflow_dispatch, this can result in unnecessary failures when subsequent workflow doesn't wait and makes logs harder to read.
This change refactors the workflow to use reusable actions.
- Confirm that workflow conditions and results remain the same.
https://trello.com/c/grpMynpF
> Refactor deployment workflows

- .github/actions/deploy/action.yml
- .github/workflows/build.yml
The smoke test results are uploaded even if a previous step fails, this is desirable if that step is the smoke test execution but if  an earlier step fails the reported results are confusing.  If the smoke test fails but the upload succeeds the `job.status` is successful, as this context property is used to report on whether the deployment has succeeded deployments with failed tests are reported as successful.
This change ensures that the results are uploaded only if the tests are executed and deployment outcomes are correctly reported:
- the `outcome` property of the `run_cypress` step is used as the condition for the upload step
- a step is added to evaluate the outcome of all preceding steps
- all steps prior to this are given an `id` to ensure that their `outcome` property is …
> Refine conditions for smoke test execution

- .github/workflows/build.yml
This fixes an issue where the docker image tag wasn't getting passed to the deploy_all job in the build-and-deploy workflow which was then defaulting to the main tag.
Add out to test job
Use output from test job in deploy_all instead of output from build
> deploy_all job uses output from test job

- app/controllers/concerns/http_auth_concern.rb
- app/lib/feature_flags.rb
- config/settings/test.yml
- spec/features/feature_flags_spec.rb
- spec/requests/basic_auth_spec.rb
Dropping the basic auth feature flag as this doesn't serve any real purpose.
- Remove the feature flag logic
- Remove the feature flag
- Remove the setting
- Rework the feature test, to authorise the user in order to test `/feature-flags`
Anything missing?
https://trello.com/c/aBrwB5XP/4537-remove-basicauth-feature-flag
> Drop basic auth enabled feature flag

- .github/actions/deploy/action.yml
The deployment status update task by default (in version 1.1.0) actively marks previous deployments as inactive, this results in a large number of API calls which in turn causes a rate limiting failure.
This change disables that function and explicitly enables the builtin GitHub behaviour that marks all previously successful deployments as inactive.
> Stop deployment status marking deployment inactive

- app/components/courses/financial_support/bursary_component.html.erb
- app/components/courses/financial_support/scholarship_and_bursary_component.html.erb
- app/components/courses/financial_support/scholarship_and_bursary_component.rb
- app/controllers/result_filters/location_controller.rb
- app/views/courses/financial_support/_loan.html.erb
- config/locales/en.yml
- spec/components/courses/fees_and_financial_support_component_spec.rb
- spec/components/courses/financial_support/bursary_component_spec.rb
- spec/components/courses/financial_support/scholarship_and_bursary_component_spec.rb
There are 3 versions of the financial support section on Find course pages:
* scholarships, bursaries and loans are available
* bursaries and loans are available
* loans are available
We need to correct inaccuracies in all three cases.
Updates to the content in the _Fees and financial support_ section of the course show page.
Per comment may help.
https://trello.com/c/WbRMUPAi/4498-dev-update-the-financial-support-section-on-find-course-pages
> Update the financial support section on find course pages

- .github/actions/deploy/action.yml
- .github/workflows/build.yml
- .github/workflows/deploy.yml
The bobheadxi/deployments GitHub Action is used to update deployment statuses, this is ineffective when deploying to persistent environments such as qa or prod.
This change removes that action from non-review app deployment workflows and uses the built in functionality instead.  Review apps continue to use the bobheadxi/deployments action.
https://trello.com/c/5M0gehU9
> Use job environment property for non-review app deployment

- .github/workflows/delete-review-app.yml
A previous commit changed the naming convention for review app environments in GitHub. 
This change updates the delete-review-app workflow to align with that change.
- Check that review app environments are getting deleted after PR close
https://trello.com/c/5M0gehU9
> Fixes deletion of review app GitHub environment

- app/form_objects/search/subjects_form.rb
There are [no courses for this subject](https://www.find-postgraduate-teacher-training.service.gov.uk/results?hasvacancies=false&fulltime=true&parttime=true&qualifications%5B%5D=QtsOnly&qualifications%5B%5D=PgdePgceWithQts&qualifications%5B%5D=Other&degree_required=show_all_courses&l=2&subject_codes%5B%5D=A1) so we can remove this checkbox.
See #1189
In future we might want to make the list of subjects dynamic, based upon course availability.
> Remove 'Ancient Greek' subject checkbox

- app/components/courses/contents_component.html.erb
- app/views/courses/show.html.erb
- spec/components/courses/contents_component_spec.rb
Moving the warning text which appears if a course does not have vacancies to help make this more clear, earlier on to candidates but keeping the Apply button at the bottom for now.
- Move warning text to the top
- Keep the apply button and end of cycle text at the bottom
Is the logic all correct?
https://trello.com/c/XIgsStek/4570-design-move-course-full-warning-to-top-of-find-pages
> Move warning text to the top

- app/components/results/results_component.html.erb
- config/locales/en.yml
- spec/components/results/results_component_spec.rb
Help to promote GIT event attendance by displaying a link on the results page, using inset text.
https://trello.com/c/BfJWB9FI/4631-promote-ttt-events-in-find-results-pages
> Add inset text to results page

- app/components/results/results_component.html.erb
- app/webpacker/styles/application.scss
- app/webpacker/styles/components/_promoted-link.scss
Move this above the "Sorted by" component, and redesign to use a background colour instead of inset text.
This promoted event link was added as an experiment, to see if it made an impact.
The inset text component is known to sometimes be ignored by users, and should probably be reserved for introducing alternative "voices" (for example quoting a message from another organisation).
Moving the link up also brings the "Sorted by" component back closer to the content it describes.
🗂️  [Trello card](https://trello.com/c/HgsSuqHr/2971-update-find-banner-for-event-promotion)
> Redesign promoted event link

- Makefile
The maintenance page initially failed during last incident with TTAPI
Fix the mismatch between "prod" and "production"
See output with "echo":
```
% make qa enable-maintenance
make: Nothing to be done for `qa'.
cf target -s bat-qa
API endpoint:   https://api.london.cloud.service.gov.uk
API version:    3.115.0
user:           116032152152065013267
org:            dfe
space:          bat-qa
echo "cd service_unavailable_page && cf push"
cd service_unavailable_page && cf push
echo cf map-route find-unavailable find-postgraduate-teacher-training.service.gov.uk --hostname qa
cf map-route find-unavailable find-postgraduate-teacher-training.service.gov.uk --hostname qa
echo Waiting 5s for route to be registered... && sleep 5
Waiting 5s for route to be registered...
echo cf unmap-route find-qa …
```
> [584] Fix maintenance page for prod

- .gitignore
- app/services/cycle_timetable.rb
Cycles timetable for 2022/2023
Amended cycles timetable for 2022/2023
Are the dates correct?
Based of https://ukgovernmentdfe.slack.com/archives/CAHBLU6ET/p1653912945018849?thread_ts=1653911776.836699&cid=CAHBLU6ET
https://trello.com/c/hhz0C73A/93-verify-the-cycle-timetable-dates-used-in-find
> [0093] Amended cycles timetable for 2022/2023

- .gitignore
- .tool-versions
- app/components/courses/fees_and_financial_support_component.html.erb
Fees and financial support sections
Move fees and financial support sections the other way around
> [0132] Move fees and financial support sections the other way around

- app/components/courses/entry_requirements_component.html.erb
- app/components/courses/entry_requirements_component.rb
- spec/components/courses/entry_requirements_component_spec.rb
When structured entry requirements was released during rollover in 2021, provider free text descriptions of entry requirements was replaced with content rendered based on questions that providers answered, plus some free text fields. We state on Publish that "Candidates will be advised that their degree subject should match or be closely related to [subject]", however, we did not release the required change to present this guidance on Find. 
Candidate team omitted to include the text detailed in the (design write up)[https://bat-design-history.netlify.app/find-teacher-training/standardised-entry-requirement-descriptions/].
"Your degree subject should be in [course subject] or a similar subject. Otherwise you’ll need to prove your subject knowledge in some other way."
It DOES render on the …
> #103 Entry requirements standard 'subject knowledge' text not appearing on course page

- config/settings/development.yml
This was missing for some reason, which prevented access to the feature flags interface.
> Add default username and password in development mode

- .github/workflows/build-and-deploy.yml
Run qa/staging and sandbox/rollover deployments in parallel, to speed up the deployment process
For the build-and-deploy workflow, create before-prod and after-prod deploy steps, with
max-parallel unset
fail-fast set to false
deploy-prod set to need the qa and staging deploys to complete successfully
deploy-after-prod set to need the prod deploy to complete successfully
Check workflow syntax
https://trello.com/c/j67sFGQJ/606-parallel-deployments
> Run selected deployments in parallel

- .github/workflows/build-and-deploy.yml
fix prod AZ secret in deploy workflow, caused by parallel deploy PR
**Required to unblock prod deploy**
remove matrix.environment references in prod deploy step
check workflow config
> Fix prod AZ credential in deploy workflow

- .github/actions/deploy/action.yml
- .github/workflows/build-nocache.yml
- app/job/slack_notification_job.rb
To help keep channel messages relevant we want to move the Slack messages created by various workflows to the twd_findpub_tech channel
- Update Slack channel references to use twd_findpub_tech
- Update SLACK_WEBHOOK repo secret with webhook for twd_findpub_tech Slack channel
- Update SETTINGS__STATE_CHANGE_SLACK_URL value in the FIND-APP-SECRETS-PRODUCTION secret in key vault
> Update workflows to use findpub Slack channel

- .github/actions/deploy/action.yml
- .github/workflows/delete-review-app.yml
- .tool-versions
- docs/deployment.md
- terraform/.terraform.lock.hcl
- terraform/modules/statuscake/providers.tf
- terraform/terraform.tf
To align with other BAT services we should keep the Terraform versions the same.
> Upgrade Terraform to 0.14.11

- package.json
- yarn.lock
Reverts DFE-Digital/find-teacher-training#1388.
This bump requires a few changes before going in:
```shell
Cypress version 10.0.0 no longer supports cypress.json.
Please run cypress open to launch the migration tool to migrate to cypress.config.***js,ts,mjs,cjs***.
https://on.cypress.io/migration-guide
```
> Revert "Bump cypress from 9.6.0 to 10.3.0"

- Dockerfile
Fix vulnerability in the base image
update library in the Dockerfile
check build scan is clear
> Fix ncurses-terminfo-base vulnerability

- app/helpers/current_point_in_recruitment_cycle_helper.rb
- app/services/cycle_timetable.rb
- app/views/switcher/cycles.html.erb
The dates on the `Current point in the recruitment cycle` are incorrect. This is because we did not know the dates at the time and used random ones. 
- Update these dates to the real dates that we use in production. 
- Remove todays date.
- Update hint text under ` Current point in the recruitment cycle` for each option to include the new two dates they are now referring to.
https://trello.com/c/7FoKmr6z/246-update-dates-on-current-point-in-the-recruitment-cycle-page
> 246 update dates on current point in the recruitment cycle page

- terraform/workspace_variables/production.tfvars.json
- terraform/workspace_variables/qa.tfvars.json
- terraform/workspace_variables/rollover.tfvars.json
- terraform/workspace_variables/sandbox.tfvars.json
- terraform/workspace_variables/staging.tfvars.json
Remove the StatusCake alerts before creating them again with the new StatusCake Terraform provider.
> Remove StatusCake alerts

- Gemfile
This allows us to send the correct IPs to the analytics platform.
> load cloudfront-rails in envs that use CloudFront

- .tool-versions
- README.md
For those using asdf, the `.tool-versions` file needs to reflect the ruby upgrade
> Update ruby version in asdf config

- app/views/layouts/_add_js_enabled_class_to_body.html.erb
- app/views/layouts/application.html.erb
- config/initializers/content_security_policy.rb
The Git Into Teaching marketing team would like to setup google ads to point to the Find website instead of the current Get into teaching website to improve conversation tracking.
We should setup a content security policy on Find to make sure it only executes script we expect.
What needs to be done
Add a CSP for Find which whitelists scripts from:
Google analytics
Google tag manager
Success
We have a CSP setup
Tech notes
The teaching vacancies app is a good source for an example as they've had to accommodate a similar need for marketing [teaching-vacancies/content_security_policy.rb at main · DFE-Digital/teaching-vacancies](https://github.com/DFE-Digital/teaching-vacancies/blob/main/config/initializers/content_security_policy.rb)
Add CSP
NB self does not include subdomains, eg. …
> 346 csp external scripts v2

- Dockerfile
The base package has been updated with r3 therefore we no longer need to
manually add this.
> Remove manual add of zlib r3

- docs/deployment.md
- terraform/.terraform.lock.hcl
- terraform/modules/statuscake/providers.tf
- terraform/terraform.tf
Update the StatusCake provider to ensure it is not using a preview
version.
> Update Terraform StatusCake provider to 2.0.3

- Gemfile
- Gemfile.lock
Reverts DFE-Digital/find-teacher-training#1482 as it breaks build with:
> Revert "Bump dfe-analytics from v1.3.2 to v1.4.0"

- app/components/courses/contact_details_component.html.erb
https://trello.com/c/vJRKI35V/614-stop-gap-ucl-is-moving-away-from-using-email
> [614] Put stop gap for UCL's contact form

- .github/actions/deploy/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/build-nocache.yml
- .github/workflows/delete-review-app.yml
- .github/workflows/deploy.yml
Dependabot is creating too many distracting PRs
Pin to the major version and let the workflow use the latest minor version
Check the workflow run
https://trello.com/c/BYSSVCNY
> [701] Pin Github actions to the major version

- .github/actions/deploy/action.yml
The set-output command is being deprecated soon.
Resolution is to use $GITHUB_OUTPUT as per the workflow commands docs.
Confirm updated workflows tested where possible:
- [] Deploy Review
https://trello.com/c/3s3iC7UV
> Stop using set-output in workflows

- app/components/courses/entry_requirements_component.rb
- app/decorators/course_decorator.rb
- spec/components/courses/entry_requirements_component_spec.rb
- spec/decorators/course_decorator_spec.rb
Use subject name not course title for qualifications needed to satisfy entry requirements. (This has been done for the new find too [here](https://github.com/DFE-Digital/publish-teacher-training/pull/3077).
The reason for this change is because if support changes the course title, the sentence may not make sense to the candidate.
Added a new method for this to handle courses with two subjects.
- Find a course
- Check the name in this section: `course/{PROVIDER_CODE}/{COURSE_CODE}#section-entry`
- Change the name in support and check the correct subject names still appear. 
- Experiment with multiple subjects
https://trello.com/c/rfYBAaP2/732-pull-through-subject-rather-than-title-into-qualifications-needed-section
> Use subject name not course title for qualifications needed

- app/view_objects/result_filters/filters_view.rb
- app/view_objects/results_view.rb
- app/views/result_filters/_all.html.erb
- app/views/result_filters/_engineers_teach_physics_filter.html.erb
- spec/features/result_page_filters/engineers_teach_physics_spec.rb
- spec/support/page_objects/page/results.rb
- spec/support/page_objects/page/search/age_group.rb
- spec/support/page_objects/page/search/subject_page.rb
In line with the "Engineers teach physics" work, we are adding a filter on Find to search for only these courses. This filter will appear when searching for the "Physics" subject.
These are the frontend changes, see: https://github.com/DFE-Digital/publish-teacher-training/pull/3086 for the backend changes.
- Add UI for filter checkbox
- Only render the checkbox if the "Physics" subject has been chosen
- Checkout this branch along with the respective branch on the TTAPI [here](https://github.com/DFE-Digital/publish-teacher-training/pull/3086)
- Perform a search for a Physics course on Find
- Try out the new filter
https://trello.com/c/BkHrpSF2/733-add-etp-filter-to-find
> Implement engineers teach physics filter on Find

- app/views/result_filters/_engineers_teach_physics_filter.html.erb
Enable ETP checkbox to work when clicking on the text
> Enable ETP checkbox to work when clicking on the text

- app/components/courses/international_students_component.html.erb
- app/components/courses/international_students_component.rb
- app/decorators/course_decorator.rb
- spec/components/courses/international_students_component_spec.rb
- spec/decorators/course_decorator_spec.rb
State the 3-year residency rule for apprenticeship courses.
- Change the `apprenticeship?` method to return true or false (previously unused)
- Utilise this in the view component to render the 3-year text if the course is an apprenticeship
- Add the word `also` if the course is an apprenticeship (as there is content before this now).
- Check `#section-international-students` for apprenticeship courses and ensure the new content is there and is correct.
- Repeat for fee paying and salaried courses and ensure the new content is not present. 
https://trello.com/c/ib4fAScn/756-update-guidance-for-international-candidates
> State the 3-year residency rule for apprenticeship courses

- app/form_objects/search/subjects_form.rb
- spec/features/search/new_flow/across_england/secondary_spec.rb
Remove Ancient greek, Hebrew and Philosophy from the ignored list. We handle empty states on the course list, not by hiding subjects.
- Remove the `IGNORED_SUBJECTS` array and only reject modern languages.
- Perform a search on Find and ensure that you now see Ancient greek, Hebrew and Philosophy (you should see no courses with these subjects).
- Create these courses and search for them and ensure the courses created appear in the search.
https://trello.com/c/sm9C5o55/776-add-ancient-greek-ancient-hebrew-and-philosophy-back-to-subjects-list-in-find
> Remove subjects from ignored list

- app/components/results/sort_by_component.html.erb
- app/view_objects/results_view.rb
- app/webpacker/packs/application.js
- app/webpacker/scripts/sort-by.js
- app/webpacker/scripts/sort-by.spec.js
- spec/features/results_spec.rb
Sort by training provider in search results not working
Fixed js issues
Amended course ordering
When sorting by training provider ascending
Then sort by provider ascending (a to z)
and sort by course name ascending (a to z)
When sorting by training provider descending
Then sort by provider descending (z to a)
and sort by course name ascending (a to z)
See 
https://find-pr-1600.london.cloudapps.digital/results?age_group=secondary&fulltime=false&hasvacancies=true&l=2&parttime=false&qualifications%5B%5D=QtsOnly&qualifications%5B%5D=PgdePgceWithQts&qualifications%5B%5D=Other&senCourses=false&subject_codes%5B%5D=08&subject_codes%5B%5D=11&sortby=1
Uses 
https://github.com/DFE-Digital/publish-teacher-training/pull/3128
> [0780] Sort by training provider in search results not working

- app/components/courses/entry_requirements_component.rb
- app/decorators/course_decorator.rb
- spec/decorators/course_decorator_spec.rb
In the entry requirements section, subjects which are also not a language should not be capitalised. 
- Add the subject codes which are a language to an array.
- Use this array to downcase all other subject names in the view.
- Ensure modern languages is not capitalised (using gsub).
- View the entry requirements on courses with the following criteria, and ensure the capitalisation is correct.
- A course with a single language subject, e.g https://find-pr-1591.london.cloudapps.digital/course/2CG/W273#section-entry
- A course with a single non language subject, e.g https://find-pr-1591.london.cloudapps.digital/course/2CG/Q774#section-entry
- A course with two subjects, one language and one non language, e.g: https://find-pr-1591.london.cloudapps.digital/course/M80/2N9G#section-entry
- A …
> Don't capitalise subjects unless the subject is a language

- app/webpacker/scripts/filter-toggle-button.js
https://trello.com/c/dFIVoAea/822-close-filters-button-should-include-visually-hidden-text-close-filter-menu
Adds a visually hidden text to the button markup
- Inspect the markup on the results page
- Test with a screen reader
> [822] Make close filter button more accessible

- app/views/layouts/application.html.erb
- app/views/pages/privacy.html.erb
- config/routes.rb
- spec/features/view_pages_spec.rb
https://trello.com/c/KabFoz5k/799-update-the-privacy-notice-for-find-and-publish
Updates the privacy notice as per the docs in the ticket above.
https://find-pr-1604.london.cloudapps.digital/privacy-policy
> [799] Update the privacy notice

- app/components/location_subject_filter_component.html.erb
Add a non breaking space to the visually hidden span for the change link on the results page.
https://trello.com/c/bhhQCnd6/826-add-non-breaking-space-between-change-and-the-visually-hidden-text-on-the-search-results-page
> Add a non breaking space

- Gemfile.lock
- app/views/result_filters/location/_form.html.erb
https://trello.com/b/yOZLQ2IK/find-pub-sprint-board
- Adds visually hidden text to inline error message when linked to no fields (eg submitting without an option on start page)
https://find-pr-1618.london.cloudapps.digital/
- Submit without entering a value on start page and check markup (do the same for other forms)
Corresponding find migration PR https://github.com/DFE-Digital/publish-teacher-training/pull/3146
> [825] Add visually hidden text to errors linked to no keys

- app/components/courses/financial_support/scholarship_and_bursary_component.rb
- config/locales/en.yml
- spec/components/courses/financial_support/scholarship_and_bursary_component_spec.rb
- spec/factories/subjects.rb
Information about bursaries and scholarships
Added scholarships info for applicable subjects
It shoud show up for 
- Chemistry
- https://find-pr-1641.london.cloudapps.digital/course/2CG/Q774#section-financial-support
- Computing
- https://find-pr-1641.london.cloudapps.digital/course/2CG/D526#section-financial-support
- Mathematics
- https://find-pr-1641.london.cloudapps.digital/course/2CG/A949#section-financial-support
- Physics
- https://find-pr-1641.london.cloudapps.digital/course/2CG/M064#section-financial-support
- French
- https://find-pr-1641.london.cloudapps.digital/course/2CG/A568#section-financial-support 
- German
- https://find-pr-1641.london.cloudapps.digital/course/2AL/L288#section-financial-support
- Spanish
- https://find-pr-1641.london.cloudapps.digital/course/2CG/Z848#sect …
> [0866] Updating information about bursaries and scholarships

- app/components/courses/summary_component.html.erb
- app/components/courses/summary_component.rb
- app/decorators/course_decorator.rb
- spec/components/courses/summary_component_spec.rb
- spec/decorators/course_decorator_spec.rb
Course level and age range
Add level next to age range if a secondary course
`secondary` should show up on courses that has level secondary
https://find-pr-1654.london.cloudapps.digital/course/2E1/Z785
> [0892] Add level next to age range if a secondary course

- app/components/courses/summary_component.html.erb
- app/components/courses/summary_component.rb
- spec/components/courses/summary_component_spec.rb
- spec/features/courses/show_spec.rb
A recent accessibility update on Find to expand PGCE, PGDE and QTS abbreviations has meant we have removed the study mode (full-time and part-time) from the lede paragraph.
Add the study mode tadjacent to the course length in the summary list on the course details.
Take a look at the show page for various study modes and course lengths.
https://trello.com/b/yOZLQ2IK/find-pub-sprint-board
> Add study_mode to course show page

- app/views/layouts/_gtm.html.erb
- app/views/layouts/application.html.erb
- config/settings.yml
- config/settings/production.yml
- config/settings/qa.yml
The marketing team would like to test the new tags before they go live.
This PR extracts some of work from this one https://github.com/DFE-Digital/find-teacher-training/pull/1437 (specifically adding the GTM script itself).
Maheera has clarified that the marketing team are able to test the tags without enabling them live on their end via GTM
> [940] Setup GTM

- app/components/results/sort_by_component.html.erb
- app/view_objects/results_view.rb
- spec/features/results_spec.rb
- spec/support/page_objects/page/results.rb
- spec/support/results_page_parameters.rb
- spec/view_objects/results_view_spec.rb
We are adding the ability to sort the results page on Find by course name.
- **Add course ordering (A-Z)**
If identical course, ordering falls back to the provider, if identical providers, ordering falls back to the course code
- **Add course ordering (Z-A)**
If identical course, ordering falls back to the provider, if identical providers, ordering falls back to the course code
- **Update provider ordering (A-Z)**
If identical provider, ordering falls back to the course, if identical courses, ordering falls back to the course code
- **Update provider ordering (Z-A)**
If identical provider, ordering falls back to the course, if identical courses, ordering falls back to the course code
Search for a few courses and check that the hierarchy above is correct. …
> Update results page ordering options

- app/components/location_subject_filter_component.html.erb
- cypress/e2e/find-teacher-training/geocoding.cy.ts
A small content tweak.
Search for a course by location and check that the new content shows.
https://trello.com/c/BEJgDPUb/972-wording-change-on-search-results-page-re-location
> Content tweak

- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace_variables/qa.tfvars.json
For the find migration to publish
Routes will be removed from find tf state and code so they can be managed from publish instead
Steps are 
- take a note of the route guids as they will be used for import in publish
- remove routes from tf state (terraform state rm) 
- remove route mappings from webapp in tf state (terraform pull, edit, terraform push)
- merge this pr
Add variable disable_routes
If variable not null for an env, then routes will not be created
make qa deploy-plan
https://trello.com/c/txVxNL4S/744-findpub-merge
> Remove qa routes from code

- terraform/workspace_variables/production.tfvars.json
- terraform/workspace_variables/qa.tfvars.json
- terraform/workspace_variables/sandbox.tfvars.json
- terraform/workspace_variables/staging.tfvars.json
Find is currently using the apply statuscake contact group,
so sends email and alerts to the wrong group
Update to the same contact group as publish
Check statuscake alerts
> Change statuscake contact group

- terraform/workspace_variables/staging.tfvars.json
For the findpub merge, remove find routes from staging
To be merged AFTER the routes have been removed from terraform state and moved to publish
Set "disable_routes": true in staging tfvars.json
deploy-plan
> Remove routes from staging

- terraform/workspace_variables/production.tfvars.json
For the findpub merge, remove find routes from production
To be merged AFTER the routes have been removed from terraform state and moved to publish
Set "disable_routes": true in production.tfvars.json
deploy-plan
> remove prod routes 

- terraform/workspace_variables/sandbox.tfvars.json
For the findpub merge, remove find routes from sandbox
To be merged AFTER the routes have been removed from terraform state and moved to publish
Set "disable_routes": true in sandbox.tfvars.json
deploy-plan
> remove sandbox routes
